-- =========================================================
-- Migration 0066 — SĂMÂNȚĂ DE DATE: Simularea din 10 mai 2026 (Grila nr. 1),
-- primii 50 de itemi (Limba română), transcriși din PDF-ul scanat.
--
-- NEPUBLICAȚI (published = false), cu cheia de răspunsuri dată de Marius
-- (22 iul 2026) inclusă. Publici din grilă când ești mulțumit. Formatarea folosește
-- marcajele rich-text ale băncii: <i> pentru enunțurile citate, <u> pentru
-- cuvintele subliniate din subiect.
--
-- Re-rulabilă: șterge întâi itemii acestei sesiuni, apoi îi inserează.
-- =========================================================

delete from public.tests_items
 where exam = 'admitere-drept' and year = 2026 and session = 'Simulare mai - G1';

insert into public.tests_items
  (exam, year, session, item_no, question, option_a, option_b, option_c, option_d, correct, published)
select 'admitere-drept', 2026, 'Simulare mai - G1', v.item_no, v.q, v.a, v.b, v.c, v.d, v.k, false
from (values
  (1, 'În fraza: <i>N-ai cum te mai scuza, așa că să mă mai cauți nu are rost.</i>, a doua propoziție, în ordinea succesiunii predicatelor, este:',
   'completivă directă;',
   'subiectivă intercalată într-o principală;',
   'consecutivă;',
   'altă interpretare.',
   'D'),
  (2, 'Fie fraza: <i>Odată ce m-ai ajutat și unde nu m-ai certat pentru ce gafă am făcut, îți voi fi mereu recunoscător, mai ales că ai făcut-o dezinteresat.</i> Numărul propozițiilor circumstanțiale de cauză este:',
   'două;',
   'patru;',
   'trei;',
   'altă interpretare.',
   'B'),
  (3, 'În fraza: <i>Neconvenindu-mi ce am auzit despre tine, se impune ca de acum înainte să-ți intre bine în cap că regulile sunt reguli, precum și că oricine le încalcă va fi pedepsit.</i>, numărul propozițiilor subiective este:',
   'trei;',
   'două;',
   'cinci;',
   'altă interpretare.',
   'D'),
  (4, 'În fraza: <i>Întrebarea este dacă se va afla cine a greșit.</i>, propozițiile subordonate sunt, în ordinea succesiunii predicatelor:',
   'subiectivă, completivă directă;',
   'predicativă, subiectivă;',
   'predicativă, completivă directă;',
   'altă interpretare.',
   'A'),
  (5, 'Fie fraza: <i>Era stabilit de mult că va pleca în vacanță, dar nu-și puseseră problema dacă vor mai avea sau nu cu ce își cumpăra biletele, dată fiind scumpirea biletelor de avion.</i> Felul propozițiilor, în ordinea succesiunii predicatelor, este:',
   'principală + subiectivă + principală + atributivă + atributivă;',
   'principală + compl. directă + principală + circ. condițională + compl. directă;',
   'principală + subiectivă + principală + atributivă + compl. directă;',
   'altă interpretare.',
   'B'),
  (6, 'Fie fraza: <i>Ca veche prietenă, din moment ce mă preocupă nu doar supărarea ta de acum, ci și ce poți face în viitor, voi veni să îți fiu alături și poate că nici nu singură.</i> Felul propozițiilor, în ordinea succesiunii predicatelor, este:',
   'circ. de cauză + subiectivă + principală + circ. de scop + principală + subiectivă;',
   'circ. de cauză + subiectivă + circ. de cauză + subiectivă + compl. directă + principală + circ. de scop + principală;',
   'circ. de timp + circ. de timp + subiectivă + principală + principală;',
   'altă interpretare.',
   'B'),
  (7, 'Fie fraza: <i>Deșteaptă cum ești, ai reușit în viață și te admir pentru cât muncești, dar să îți disprețuiești acum prietenii de-o viață, când știi clar cât te-au ajutat, asta nu se cade.</i> Felul propozițiilor, în ordinea succesiunii predicatelor, este:',
   'circ. de cauză + principală + principală + compl. indirectă (prepozițională) + compl. directă + circ. de timp + compl. directă + principală;',
   'circ. de cauză + principală + principală + circ. de cauză + subiectivă + circ. condițională + compl. directă + principală;',
   'circ. de mod + principală + principală + circ. de cauză + subiectivă + circ. concesivă + compl. directă + principală;',
   'altă interpretare.',
   'A'),
  (8, 'Fie frazele: <i>(1) Dacă te-am însoțit mereu, am făcut-o ca să te protejez. (2) Spune-mi cum de te-ai răzgândit. (3) Respectă-i pe care te-au crescut! (4) Neștiind unde să te găsească, se poate ușor rătăci.</i> Există o completivă directă:',
   'în toate;',
   'numai în (2), (3) și (4);',
   'numai în (1) și (2);',
   'altă interpretare.',
   'C'),
  (9, 'Fie următoarele afirmații despre <u>complementul indirect</u> (în dativ): <i>(1) poate avea ca termeni regenți verbe, adjective, adverbe și anumite interjecții; (2) se dublează prin forme neaccentuate (clitice) ale pronumelui personal sau reflexiv; (3) poate fi exprimat prin substantive, pronume, numerale și anumite adverbe.</i> Sunt corecte:',
   'toate;',
   'numai (2);',
   'numai (1) și (2);',
   'altă interpretare.',
   'B'),
  (10, 'Dintre următoarele afirmații referitoare la <u>predicat</u>: <i>(1) nu admite coordonarea în limitele unei propoziții; (2) poate să conțină forme pronominale neaccentuate (clitice); (3) poate avea realizare propozițională.</i>, nu sunt corecte:',
   'numai (3);',
   'niciuna;',
   'toate;',
   'altă interpretare.',
   'A'),
  (11, 'Fie următoarele afirmații referitoare la <u>atribut</u>: <i>(1) poate avea ca termen regent un numeral; (2) se poate subordona regentului prin joncțiune; (3) când este realizat propozițional, poate fi introdus prin conjuncții, adverbe relative, pronume și adjective pronominale relative, pronume și adjective pronominale nehotărâte.</i> Dintre acestea, sunt corecte:',
   'numai (1) și (3);',
   'numai (1) și (2);',
   'toate;',
   'altă interpretare.',
   'A'),
  (12, 'Fie următoarele afirmații: <i>(1) nu toate pronumele cunosc realizarea de adjectiv pronominal, dar toate adjectivele pronominale pot apărea și în ipostază pronominală; (2) atât pronumele, cât și adjectivele pronominale pot ocupa poziția de nume predicativ; (3) orice adjectiv pronominal precedat de o prepoziție are cazul impus de aceasta.</i> Sunt corecte:',
   'toate;',
   'numai (1);',
   'numai (2) și (3);',
   'altă interpretare.',
   'A'),
  (13, 'Fie afirmațiile: <i>(1) pot să nu aibă funcție sintactică; (2) pot fi precedate de prepoziții; (3) pot fi termen regent pentru un complement indirect; (4) unele pot avea omonime substantivale.</i> Dintre acestea, sunt corecte atât referitor la adverb, cât și la interjecție:',
   'toate;',
   'numai (1) și (3);',
   'numai (2), (3) și (4);',
   'altă interpretare.',
   'C'),
  (14, 'Se dau afirmațiile: <i>Prezintă flexiune în raport cu categoria gramaticală a genului: (1) toate substantivele, în afara formelor invariabile; (2) toate pronumele; (3) o parte dintre numerale.</i> Sunt incorecte:',
   'numai (1) și (2);',
   'niciuna;',
   'numai (1) și (3);',
   'altă interpretare.',
   'B'),
  (15, 'Se dau afirmațiile: <i>(1) unele locuțiuni conjuncționale subordonatoare cuprind (ca formant) și conjuncții subordonatoare; (2) în structura unor locuțiuni conjuncționale subordonatoare pot intra substantive, articulate sau nearticulate; (3) conjuncția subordonatoare poate fi uneori elidată.</i> Sunt corecte:',
   'toate;',
   'numai în (2);',
   'numai (1) și (3);',
   'altă interpretare.',
   'C'),
  (16, 'Dintre enunțurile: <i>(1) Ție îți place gramatica, iar mie, matematica. (2) Fii mereu tânăr și neliniștit! (3) Îmi place nu numai vinul, ci și berea.</i>, există elipsă verbală:',
   'în toate;',
   'numai în (1);',
   'numai în (1) și (3);',
   'altă interpretare.',
   'C'),
  (17, 'Dintre enunțurile: <i>(1) Ai mei îl votează pe care ei cred că îi va ajuta. (2) În viața lui se iviseră la probleme de nu mai știa ce să facă. (3) I-a crezut pe cei care, de fapt, doar profitau de el, deși l-au avertizat și dintre ai mei.</i>, nu conțin subiecte în alt caz decât nominativ:',
   'numai (2) și (3);',
   'numai (2);',
   'numai (1);',
   'altă interpretare.',
   'C'),
  (18, 'Fie enunțurile: <i>(1) N-are pe cine conta. (2) Mizez pe toți care și-au dovedit buna-credință. (3) Pe cine nu lași să moară, nu te lasă să trăiești.</i> Prepoziția <u>pe</u> însoțește un complement direct:',
   'în toate;',
   'numai în (3);',
   'în niciuna;',
   'altă interpretare.',
   'C'),
  (19, 'În exemplul: <i>Au anunțat la radio că vremea se va încălzi.</i>, subiectul primului predicat este:',
   'subînțeles;',
   'inclus;',
   'nedeterminat;',
   'altă interpretare.',
   'B'),
  (20, 'Se dau enunțurile: <i>(1) Rămâne de văzut ce va fi cu noi. (2) Părând că va ploua, nu-i cum mai pleca în drumeție. (3) Nefiind înțeles de cei din jur, e mereu ironizat.</i> Conțin cel puțin un verb copulativ:',
   'niciunul;',
   'numai (1) și (2);',
   'numai (2) și (3);',
   'altă interpretare.',
   'A'),
  (21, 'În enunțul: <i>Las-<u>o</u> (1) baltă, că nici nu mai sper că <u>o</u> (2) să îți dai vreodată seama cum, într-<u>o</u> (3) singură clipă de neatenție, ai distrus munca de <u>o</u> (4) viață a tuturor.</i> Cuvântul subliniat are funcție sintactică:',
   'numai în (1), (3) și (4);',
   'numai în (1) și (3);',
   'numai în (2) și (4);',
   'altă interpretare.',
   'C'),
  (22, 'În enunțul: <i>Meritul e doar al tău, ai ajuns ce ai ajuns doar prin forțele tale, rămânând, însă, mereu același, așa că modestia ta e de prisos.</i>, cazul adjectivelor cu funcție de nume predicativ este, în ordine:',
   'G, N, N, A;',
   'N, N, N;',
   'N, N, A;',
   'altă interpretare.',
   'D'),
  (23, 'Fie enunțul: <i>S-a amăgit crezându-te și, pentru că nu acum mai are ce face, a spus adio și visului de a revedea Parisul.</i> Numărul complementelor directe este:',
   'două;',
   'trei;',
   'patru;',
   'altă interpretare.',
   'D'),
  (24, 'Fie enunțul: <i>Copiii vecinilor și ai mei țipă adesea în fața mea și nu știu ce minune speri să apară, încât să se cumințească.</i> Cazul pronumelor este, în ordine:',
   'G, A, N, A;',
   'N, G, A;',
   'N, A;',
   'altă interpretare.',
   'D'),
  (25, 'În enunțul: <i>Învățând constant, a reușit la examen și de aceea acum radiază de bucuroasă ce e, așa că nu văd de ce nu i-ai urma exemplul.</i>, circumstanțialul de cauză este exprimat, în ordine, prin:',
   'verb, locuțiune adverbială, adjectiv, pronume;',
   'pronume, pronume;',
   'verb, pronume, adjectiv;',
   'altă interpretare.',
   'C'),
  (26, 'Fie enunțul: <i>Mereu <u>răsplătită fie</u>-ți bunătatea!</i> Secvența subliniată este:',
   'verb copulativ (imperativ) + nume predicativ (adj., N) / pred. nominal;',
   'verb predicativ, imperativ, diateză (construcție) pasivă / pred. verbal;',
   'verb copulativ (conj., prez.) + nume predicativ (adj., N) / pred. nominal;',
   'altă interpretare.',
   'B'),
  (27, 'Fie enunțul: <i>După ce am plecat de la tine, i-am vizitat și pe toți <u>ceilalți</u>.</i> Cuvântul subliniat este:',
   'adj. pron. dem., A / atr. adj.;',
   'adj. pron. nehot., A / atr. adj.;',
   'pron. dem., A / compl. direct;',
   'altă interpretare.',
   'A'),
  (28, 'Fie enunțul: <i>Nu ați fost în cea mai bună formă la maratonul de ieri, dar nu m-au impresionat nici dintre <u>ai lor</u>.</i> Cuvântul subliniat este:',
   'pron. pos., G / subiect;',
   'pron. pers., G / atr. pron. prep.;',
   'pron. pers., G / subiect (excepție de la N subiectului);',
   'altă interpretare.',
   'C'),
  (29, 'Fie enunțul: <i><u>Războiul</u> părând pe sfârșite, zâmbetul reapărea pe fața oamenilor.</i> Cuvântul subliniat este:',
   'subst., N / subiect;',
   'subst., A / circ. de cauză;',
   'subst., N / nume predicativ;',
   'altă interpretare.',
   'C'),
  (30, 'Fie enunțul: <i><u>Fiind de înțeles</u> de către oricine că nu va renunța la obiceiurile sale, ajunseseră să îl ocolească.</i> Secvența subliniată este:',
   'verb pred., gerunziu, diateză (construcție) pasivă / circ. de cauză;',
   'verb cop. (gerunziu) + nume predicativ (verb pred., supin) / circ. de cauză;',
   'verb copulativ / circ. de cauză + verb pred., supin / subiect;',
   'altă interpretare.',
   'D'),
  (31, 'Fie enunțul: <i>Libertatea ne-o datorăm curajului <u>cărora</u> și-au apărat țara cu prețul vieții.</i> Cuvântul subliniat este:',
   'adj. pron. rel., D / atr. adj.;',
   'pron. rel., D / subiect (excepție reală de la nominativul subiectului);',
   'pron. rel., G / atr. pron. gen.;',
   'altă interpretare.',
   'A'),
  (32, 'Fie enunțul: <i>Nu prea știu ce <u>carte</u> de gramatică li se pare lor că ți-ar fi utilă.</i> Cuvântul subliniat este:',
   'subst., N / subiect;',
   'subst., A / compl. direct;',
   'subst., N / nume predicativ;',
   'altă interpretare.',
   'B'),
  (33, 'În enunțul: <i>Uneori, diminețile, de exemplu, mă trezesc într-adevăr cu o stare nașpa, de mai-mai că îmi vine să mă pun iar în pat fuga-fuguța.</i>, există:',
   'trei adverbe și patru locuțiuni adverbiale;',
   'patru adverbe și trei locuțiuni adverbiale;',
   'patru adverbe și două locuțiuni adverbiale;',
   'altă interpretare.',
   'B'),
  (34, 'În enunțul: <i>Îi venea greu să se desprindă din negura veșnicului ieri, care îl înconjura precum un tot.</i>, există:',
   'trei adverbe și un substantiv;',
   'un adverb și două substantive;',
   'două adverbe și trei substantive;',
   'altă interpretare.',
   'B'),
  (35, 'În enunțul: <i>E greu de înțeles cum am răcit, de îmi curge nasul și tușesc întruna, mai ales că se simte adiind un vânt cald de primăvară.</i>, numărul subiectelor exprimate este:',
   'două;',
   'patru;',
   'unu;',
   'altă interpretare.',
   'A'),
  (36, 'Adverbele din enunțul: <i>Iarna mă sperie frigul și aseară m-am supărat foc auzind la știri că poate va începe să ningă viscolit.</i> sunt, în ordinea dată, obținute prin:',
   'conversiune, compunere, conversiune, conversiune, conversiune;',
   'conversiune, compunere, conversiune;',
   'conversiune, conversiune;',
   'altă interpretare.',
   'C'),
  (37, 'Fie enunțul: <i>Deși a ajuns celebru în <u>showbizul</u> (1) românesc, postează adesea <u>selfie-uri</u> (2) din zboruri <u>low cost</u> (3).</i> Dintre cuvintele subliniate, nu sunt forme corecte ale unor substantive:',
   'niciunul;',
   'numai (3);',
   'numai (1) și (2);',
   'altă interpretare.',
   'A'),
  (38, 'Dintre cuvintele subliniate din enunțul: <i>Deși <u>súntem</u> (1) prieteni de o viață și ar trebui să te porți cu mine ca un <u>protéctor</u>, de o vreme ai mai degrabă o atitudine de <u>despót</u>.</i>, sunt corect accentuate:',
   'toate;',
   'niciunul;',
   'numai (1);',
   'altă interpretare.',
   'A'),
  (39, 'Dintre cuvintele subliniate din enunțul: <i><u>Nou-aleasa</u> (1) directoare își savura <u>mic-dejunul</u> (2) pe terasă, îmbrăcată într-o superbă rochie <u>nouă-nouță</u> (3).</i>, sunt corecte:',
   'toate;',
   'numai (1) și (2);',
   'numai (2) și (3);',
   'altă interpretare.',
   'B'),
  (40, 'Formele verbale din enunțul: <i>Cum nu-mi place nici să mă târgui, dar nici să îți zgândăr rănile din trecut și nici nu mă amestec în treburi care îmi excedează competențele, ia ghici ce am să fac!</i> sunt:',
   'toate corecte;',
   'toate corecte, în afară de una;',
   'patru corecte și restul incorecte;',
   'altă interpretare.',
   'C'),
  (41, 'Dintre cuvintele subliniate în enunțul: <i><u>Acuma</u> (1) îmi dau seama că <u>nicăierea</u> (2) nu e ca aici, acasă, unde ne place <u>tuturora</u> (3).</i>, sunt adverbe cu formă corectă:',
   'numai (1) și (2);',
   'numai (1) și (3);',
   'toate;',
   'altă interpretare.',
   'B'),
  (42, 'Se dau următoarele definiri/explicări de cuvinte: <i>(1) amintire vagă a unor fapte aproape dispărute din memorie; (2) urmă (abia perceptibilă); (3) obiceiuri proaste păstrate din trecut.</i> Care dintre acestea poate/pot constitui sensul/sensurile cuvântului <u>reminiscență</u>, în diferite contexte și expresii?',
   'toate;',
   'numai (1) și (2);',
   'numai (2) și (3);',
   'altă interpretare.',
   'A'),
  (43, 'Se dau următoarele definiri/explicări de cuvinte: <i>a merge fără a se opri (1); a depăși, a lăsa în urmă (2); a dispărea, a pieri (3); a începe să se ocupe cu altceva (4); a susține cu succes un examen (5).</i> Care dintre acestea poate/pot constitui sensul/sensurile verbului tranzitiv <u>a trece</u>, în diferite contexte și expresii?',
   'toate;',
   'numai (1), (2) și (5);',
   'numai (1), (2), (3) și (5);',
   'altă interpretare.',
   'B'),
  (44, 'Din punct de vedere ortografic, structura ... <u>li-i vedea</u> ... este:',
   'corectă, indiferent de context;',
   'incorectă, indiferent de context;',
   'corectă doar în anumite contexte;',
   'altă interpretare.',
   'A'),
  (45, 'Fie secvențele: <i>(1) aceleiași întrebări; (2) o puzderie de aștri argintii; (3) mi-i că m-i desconsidera; (4) un du-te-vino continuu; (5) or să vină.</i> Sunt corecte:',
   'toate;',
   'numai (1), (3) și (4);',
   'toate, în afară de (5);',
   'altă interpretare.',
   'C'),
  (46, 'În enunțul: <i>Fiind un om care te respecți, nu vei da niciodată curs unei aluzii răutăcioase și, cred eu, pe deplin nemeritată, așa că e binevenită și atitudinea ta rezervată, și, lucru tot mai rar în zilele noastre, dorința ta continuuă de a fi în relații bune cu nu prea integrii tăi colegi.</i> Numărul greșelilor din enunț este de:',
   'două;',
   'patru;',
   'una;',
   'altă interpretare.',
   'B'),
  (47, 'În enunțul: <i>Ai răbdare și nu da pacea pe rușine, că tinerețea nu trebuie să însemne și comoditate.</i>, numărul substantivelor defective de plural este:',
   'unu;',
   'trei;',
   'cinci;',
   'altă interpretare.',
   'A'),
  (48, 'Fie următoarele exemple: <i>(1) Mi-a dăruit o floare. (2) Și-a jertfit viața. (3) Își dă mereu cu părerea. (4) Nu mai lovi cu pumnul în masă. (5) Au ieșit mugurii.</i> Pentru contextele date, este corectă afirmația:',
   'unul dintre verbe poate fi sinonimul celorlaltor patru;',
   'unul dintre verbe poate fi antonimul celorlaltor patru;',
   'cel puțin două dintre verbe au în flexiune variante literare libere;',
   'niciuna dintre afirmații nu este corectă.',
   'B'),
  (49, 'Fie cuvintele: <i><u>domnia-sa</u> (1); <u>punct-și-virgulă</u> (2); <u>Calea-Lactee</u> (3); <u>afterschool</u> (4); <u>site-uri</u> (5).</i> Sunt cuvinte compuse scrise corect:',
   'toate;',
   'numai (1), (2) și (5);',
   'toate, în afară de (5);',
   'altă interpretare.',
   'B'),
  (50, 'Dintre substantivele: <i><u>mătușii</u> (1), <u>terorii</u> (2), <u>sortii</u> (3), <u>păpușii</u> (4), <u>cenușii</u> (5)</i>, au și o altă formă de genitiv-dativ, în variație liberă:',
   'niciunul;',
   'numai (2), (3) și (5);',
   'numai (3);',
   'altă interpretare.',
   'A')
) as v(item_no, q, a, b, c, d, k);
