-- =========================================================
-- Migration 0067 — SĂMÂNȚĂ DE DATE: EXAMENUL DE ADMITERE din 22 iulie 2026
-- (Grila nr. 1), primii 50 de itemi (Limba română), transcriși din scan.
--
-- NEPUBLICAȚI (published = false), cu baremul oficial dat de Marius
-- (22 iul 2026). Publici din grilă după corectură. Marcaje:
-- <i> enunțurile citate, <u> cuvintele subliniate în subiect.
--
-- Re-rulabilă. Ștergerea acoperă și rândurile intrate din greșeală sub
-- „Iulie - G1" pe vremea când sub eticheta asta stătea simularea din mai.
-- =========================================================

delete from public.tests_items
 where exam = 'admitere-drept' and year = 2026 and session = 'Iulie - G1';

insert into public.tests_items
  (exam, year, session, item_no, question, option_a, option_b, option_c, option_d, correct, published)
select 'admitere-drept', 2026, 'Iulie - G1', v.item_no, v.q, v.a, v.b, v.c, v.d, v.k, false
from (values
  (1, 'În fraza: <i>Când râde, când plânge și nu prea are nimeni ce-i face, în consecință se feresc de el.</i>, numărul propozițiilor subordonate este:',
   'două;',
   'patru;',
   'trei;',
   'altă interpretare.',
   'D'),
  (2, 'Fie fraza: <i>Fiind recomandat să nu se întârzie cu decizia, ci să se rezolve totul cât mai repede, zău că nu-mi vine în minte niciun motiv serios pentru a tot tergiversa lucrurile.</i> Felul propozițiilor subordonate, în ordinea succesiunii predicatelor, este:',
   'compl. directă, circ. cauză, compl. directă, atributivă;',
   'subiectivă, subiectivă, subiectivă;',
   'subiectivă, subiectivă, circ. scop;',
   'altă interpretare.',
   'B'),
  (3, 'Fie enunțurile: <i>(1) N-are ce se mai afla de la noi. (2) Părea că se aștepta la reacția mea, de aceea nu a părut surprins. (3) Era de bănuit tot ce a ieșit la iveală azi, doar că acum s-a și dovedit a cui era vina.</i> Conțin cel puțin o subordonată subiectivă:',
   'toate;',
   'doar (1) și (3);',
   'doar (1) și (2);',
   'altă interpretare.',
   'D'),
  (4, 'Fie fraza: <i>Continuă cu minciunile, unde știe că îl cunosc prea bine și când, și dacă și-ar da cuvântul, tot nu l-aș mai crede vreodată, măcar că îmi pusesem toate speranțele în el.</i> Felul propozițiilor, în ordinea succesiunii predicatelor, este:',
   'principală + circ. concesivă + compl. directă + circ. concesivă + circ. concesivă + circ. concesivă;',
   'principală + circ. concesivă + compl. directă + circ. condițională + circ. de timp + circ. concesivă;',
   'principală + circ. de timp + compl. directă + circ. condițională + circ. de loc + circ. de cauză;',
   'altă interpretare.',
   'A'),
  (5, 'În fraza: <i>Cum a fost atât de ușor acest examen, asta nici nu-mi vine să cred, de vreme ce mai că am putut rezolva totul perfect.</i>, propozițiile subordonate sunt, în ordinea succesiunii predicatelor:',
   'compl. directă, compl. directă, circ. cauză, compl. directă;',
   'compl. directă, subiectivă, circ. cauză, subiectivă;',
   'circ. cauză, compl. directă, circ. cauză;',
   'altă interpretare.',
   'B'),
  (6, 'Fie frazele: <i>(1) Părând că doarme, am rămas unde eram, evitând să fac zgomot. (2) Noi plecăm, că nu mai e ce face aici. (3) Rămâne de văzut, că până acum a fost ce a fost, dar acum nu se mai face ce trebuie în țara asta.</i> Există o predicativă:',
   'în toate;',
   'numai în (1);',
   'numai în (2) și (3);',
   'altă interpretare.',
   'B'),
  (7, 'Fie fraza: <i>A fost atât de cald în vara care a trecut că, în momentul în care ieșeai din casă, nu știai ce mijloc de transport să iei mai repede, că n-aveai ce căuta pe stradă.</i> Propozițiile introduse prin pronume relative sunt, în ordinea succesiunii predicatelor:',
   'atributivă, atributivă;',
   'circ. de timp, atributivă, compl. directă, compl. directă;',
   'atributivă, compl. directă, compl. directă;',
   'altă interpretare.',
   'A'),
  (8, 'Fie enunțurile: <i>(1) A trecut pe lângă noi ca și când nu ne cunoștea. (2) Pe lângă faptul că sunteți deștepți, mai sunteți și bine pregătiți. (3) Fii atent, chiar dacă ai emoții! (4) Dat fiind că ai învățat, vei reuși.</i> Conțin propoziții subordonate introduse prin locuțiuni conjuncționale:',
   'toate;',
   'toate, în afară de (3);',
   'numai (1) și (3);',
   'altă interpretare.',
   'C'),
  (9, 'Fie următoarele afirmații: <i>(1) poate avea ca regent forme nepersonale (infinitiv, gerunziu, supin); (2) se poate realiza prin clitic pronominal; (3) admite dublarea printr-o formă neaccentuată (clitică) de pronume personal sau reflexiv.</i> Dintre acestea, sunt corecte atât pentru <u>complementul direct</u>, cât și pentru <u>complementul indirect</u>:',
   'niciuna;',
   'toate;',
   'numai (2) și (3);',
   'altă interpretare.',
   'B'),
  (10, 'Dintre următoarele afirmații referitoare la <u>numele predicativ</u>: <i>(1) este neomisibil; (2) poate avea ca regent orice formă verbală nepersonală (non-finită), cu excepția supinului; (3) poate fi exprimat (realizat) prin orice formă verbală nepersonală (non-finită), fără excepție.</i>, nu sunt corecte:',
   'numai (2) și (3);',
   'niciuna;',
   'numai (1) și (3);',
   'altă interpretare.',
   'A'),
  (11, 'Fie următoarele afirmații referitoare la <u>circumstanțialul de timp</u>: <i>(1) poate avea ca termen regent un verb, un adjectiv participial sau propriu-zis, o interjecție (predicativă); (2) poate fi exprimat (realizat) prin substantive, pronume sau numerale, numai dacă acestea sunt însoțite de prepoziție; (3) când este realizat propozițional, poate fi introdus numai printr-un adverb relativ sau printr-un pronume relativ precedat de prepoziție.</i> Dintre acestea, sunt corecte:',
   'numai (1);',
   'numai (1) și (2);',
   'numai (2) și (3);',
   'altă interpretare.',
   'A'),
  (12, 'Fie următoarele afirmații despre <u>adjective</u>: <i>(1) unele pot accepta un complement indirect; (2) cazul acestora este întotdeauna rezultatul acordului cu un nominal, fără excepții; (3) două adjective cu același substantiv regent sunt întotdeauna coordonate.</i> Dintre acestea, sunt corecte:',
   'numai (1);',
   'numai (1) și (2);',
   'numai (2) și (3);',
   'altă interpretare.',
   'A'),
  (13, 'Fie următoarele afirmații: <i>(1) nu cunosc categoria numărului; (2) pot avea funcția sintactică de subiect; (3) pot fi precedate (însoțite) de prepoziții.</i> Dintre acestea, sunt corecte atât pentru <u>numeral</u>, cât și pentru <u>adverb</u>:',
   'toate;',
   'numai (1);',
   'numai (1) și (3);',
   'altă interpretare.',
   'C'),
  (14, 'Fie următoarele afirmații: <i>(1) cazul poate fi impus substantivului de prepoziții și, uneori, de adverbe; (2) marcarea cazului poate fi uneori făcută exclusiv prin intonație; (3) una și aceeași prepoziție impune întotdeauna același caz, indiferent de cuvântul pe care îl însoțește.</i> Sunt corecte:',
   'toate;',
   'numai (1) și (2);',
   'niciuna;',
   'altă interpretare.',
   'B'),
  (15, 'Se dau următoarele afirmații referitoare la <u>interogative</u>: <i>(1) toate pronumele pot funcționa și cu valoare adjectivală; (2) au funcție sintactică exclusiv în propoziția pe care o introduc; (3) nici pronumele, nici adjectivele pronominale nu utilizează realizări prin locuțiuni.</i> Dintre acestea, sunt corecte:',
   'numai (2) și (3);',
   'numai (1) și (2);',
   'niciuna;',
   'altă interpretare.',
   'C'),
  (16, 'Se dau următoarele afirmații referitoare la formele <u>verbale nepersonale (non-finite)</u>: <i>(1) au întotdeauna același subiect cu al verbului-predicat din propoziție; (2) se subordonează regentului prin atașare directă, prepoziții sau conjuncții subordonatoare; (3) nu cunosc forme flexionare de număr și persoană.</i> Sunt corecte:',
   'toate;',
   'numai (1) și (2);',
   'numai (3);',
   'altă interpretare.',
   'C'),
  (17, 'Se dau următoarele afirmații: Relația de subordonare se poate exprima prin: <i>(1) conjuncții subordonatoare; (2) pronume, adjective și adverbe relative; (3) prepoziții; (4) caz; (5) acord; (6) juxtapunere.</i> Sunt corecte:',
   'toate, în afară de (6);',
   'numai (1), (2), (3) și (5);',
   'toate;',
   'altă interpretare.',
   'C'),
  (18, 'În enunțul: <i>Deși în politică se minte mult, mie mereu mi-a păsat cu adevărat de oameni, așa că, draga mea, hai și tu alături de mine!</i>, există:',
   'un subiect subînțeles și un subiect inclus;',
   'două subiecte subînțelese și un subiect inclus;',
   'un subiect exprimat;',
   'altă interpretare.',
   'C'),
  (19, 'Dintre enunțurile: <i>(1) Eforturile mele și ale tale vor fi răsplătite. (2) Contra alor mei prieteni nu e bine să fii! (3) Nefiind ale mele, nu pot să îți împrumut cărțile pe care mi le ceri.</i>, conțin pronume posesive în genitiv:',
   'toate;',
   'niciunul;',
   'numai (2);',
   'altă interpretare.',
   'B'),
  (20, 'În enunțul: <i>Sincer cum am fost mereu și, cum situația o impunea, le-am spus clar că, unde nu își văd de treabă, voi fi nevoit să îi trimit unde le e locul.</i>, adverbele relative au, în ordine, funcțiile sintactice de:',
   'nume predicativ, circ. de loc;',
   'circ. de mod, circ. de cauză, circ. de loc, circ. de loc;',
   'circ. de loc;',
   'altă interpretare.',
   'A'),
  (21, 'În succesiunea din enunțul: <i>Anunțând la televizor că poate ajunge și la noi furtuna, am închis toate geamurile.</i>, primul subiect este:',
   'exprimat - prin verbul <i>(a) ajunge</i>;',
   'exprimat - prin substantivul <i>furtuna</i>;',
   'nedeterminat;',
   'altă interpretare.',
   'C'),
  (22, 'În enunțul: <i>Sigur știi rezolva grila, la câte ai făcut până acum la pregătire și ce dorință de a reuși ai, așa că simt apropiindu-se un mare succes și deja mă pot bucura pentru tine!</i>, numărul cuvintelor cu funcția de complement direct este:',
   'trei;',
   'patru;',
   'două;',
   'altă interpretare.',
   'D'),
  (23, 'Fie enunțul: <i>Încă nu-ți dai seama cât de importante sunt eforturile acestea ale tale, dar mă gândesc că într-o zi vei conștientiza ce mare lucru ai realizat.</i> Cazul pronumelor cu funcție sintactică este, în ordine:',
   'D, N, A, A;',
   'D, A;',
   'N, A;',
   'altă interpretare.',
   'D'),
  (24, 'În enunțul: <i>Făcând abstracție de emoții, aș zice că a fost un examen ușor, încât, în caz de reușită, voi sărbători împreună cu voi, că altminteri, singură, nu voi simți pe deplin bucuria.</i>, circumstanțialul condițional este exprimat, în ordine, prin:',
   'substantiv, adverb, adjectiv;',
   'verb, substantiv;',
   'substantiv, adjectiv;',
   'altă interpretare.',
   'D'),
  (25, 'În enunțurile: <i>(1) Ce important e să ai măcar un prieten adevărat! (2) Nefiind niște începători, mă așteptam la mai mult de la voi. (3) O zi liberă e tot ce vreau.</i>, funcțiile sintactice ale substantivelor nearticulate sunt:',
   'compl. direct în (1), nume predicativ în (2) și (3);',
   'compl. direct în toate;',
   'compl. direct în (1), subiect în (3);',
   'altă interpretare.',
   'C'),
  (26, 'Fie enunțurile: <i>(1) Eu îmi doresc să devin avocat și tu, profesor. (2) Vreau să merg nu la munte, ci la mare. (3) Cine crezi că va reuși, tu fiind pregătit, iar ei nu? (4) Noi stăteam liniștiți pe plajă, iar el țuști în apă.</i> Conțin elipse verbale:',
   'toate;',
   'numai (1) și (3);',
   'numai (1), (2) și (4);',
   'altă interpretare.',
   'B'),
  (27, 'Fie enunțurile: <i>(1) Iar mă doare capul când văd că ajuți pe cine te-a înșelat de atâtea ori. (2) M-am oprit în fața cui mă invitase. (3) Oare nu dai prea multă atenție cui nu merită?</i> Conțin subiecte în alt caz decât nominativ:',
   'toate;',
   'numai (2);',
   'numai (1) și (3);',
   'altă interpretare.',
   'A'),
  (28, 'Fie enunțurile: <i>(1) Sunt niște oameni de nimic. (2) Ochelarii de citit sunt pe masă. (3) După o zi de alergat în mall după cumpărături, nu mai voiam decât să mă odihnesc.</i> Există substantive cu funcția sintactică de atribut, al căror caz e impus de prepoziția <u>de</u>:',
   'în toate;',
   'numai în (1) și (3);',
   'în niciunul;',
   'altă interpretare.',
   'C'),
  (29, 'În enunțul: <i>Ce crezi că mi-a putut povesti despre tine sora ta?</i>, regentul pronumelui interogativ este:',
   'verbul <i>a crede</i>;',
   'verbul <i>a putea</i>;',
   'verbul <i>a povesti</i>;',
   'altă interpretare.',
   'C'),
  (30, 'Fie enunțul: <i><u>Ce</u> visezi să ajungi peste trei ani?</i> Secvența subliniată este:',
   'pron. interogativ, A / compl. direct;',
   'pron. relativ, N / nume predicativ;',
   'pron. interogativ, N / subiect;',
   'altă interpretare.',
   'D'),
  (31, 'Fie enunțul: <i>Mereu am căutat să fiu în preajma <u>lui</u>.</i> Cuvântul subliniat este:',
   'pron. pers., G cu loc. prep. / circ. de loc;',
   'pron. pers., G cu loc. prep. / nume predicativ;',
   'pron. pers., G / atr. pron. gen.;',
   'altă interpretare.',
   'A'),
  (32, 'Fie enunțul: <i>Anul <u>când</u> am intrat la facultate a fost cel mai frumos din viața mea.</i> Cuvântul subliniat este:',
   'adv. rel. / atribut adverbial;',
   'adv. rel. / circ. de timp;',
   'adv. rel. / fără funcție sintactică;',
   'altă interpretare.',
   'B'),
  (33, 'Fie enunțul: <i>În locul <u>tău</u>, n-aș fi acceptat așa ceva.</i> Cuvântul subliniat este:',
   'adj. pos., A / atr. adj.;',
   'adj. pos., A / circ. condițional;',
   'pron. pos., G cu loc. prep./ circ. condițional;',
   'altă interpretare.',
   'B'),
  (34, 'Fie enunțul: <i>Oare am putea <u>fi primiți</u> și noi în clubul vostru select?</i> Secvența subliniată este:',
   'verb copulativ + nume predicativ (adj., N) / pred. nominal;',
   'verb predicativ, diateză (construcție) pasivă / compl. direct;',
   'verb predicativ, diateză (construcție) pasivă / predicat verbal;',
   'altă interpretare.',
   'B'),
  (35, 'Fie enunțul: <i><u>Aproape</u> că retrăiesc emoțiile pe care le-am avut și eu la admitere, cu foarte mulți ani în urmă.</i>',
   'adverb predicativ / pred. verbal;',
   'adverb de mod / circ. de mod;',
   'adverb de mod / nume predicativ;',
   'altă interpretare.',
   'A'),
  (36, 'Fie enunțul: <i>Odată anunțate <u>baremele</u> (1) și, ulterior, puse <u>afișele</u> (2) cu rezultatele finale, vei ști dacă ai făcut primul pas înspre a deveni o <u>doctoră</u> (3) de succes, ba chiar, într-o zi, una <u>omoloagă</u> (4) marilor nume ale medicinei românești.</i> Dintre cuvintele subliniate, nu sunt forme corecte ale unor substantive:',
   'niciunul;',
   'numai (2), (3) și (4);',
   'numai (3) și (4);',
   'altă interpretare.',
   'C'),
  (37, 'Dintre cuvintele subliniate din enunțul: <i>Devenise o (1) <u>pictoriță</u> celebră, iar în luna (2) <u>februarie</u> urma să expună la Paris, așa că (3) <u>spuneți</u>-mi voi dacă nu e chiar de admirat!</i>, au accentul corect pe prima silabă:',
   'numai în (1) și (3);',
   'numai în (3);',
   'numai în (1) și (2);',
   'altă interpretare.',
   'A'),
  (38, 'Dintre cuvintele subliniate din enunțul: <i><u>Azi-mâine</u> (1) te văd și pe tine student și <u>poate-poate</u> (2) într-o zi vei deveni și <u>primul-ministru</u> (3) al țării.</i>, sunt corecte:',
   'toate;',
   'numai (1) și (2);',
   'numai (1) și (3);',
   'altă interpretare.',
   'A'),
  (39, 'Formele verbale din enunțul: <i>Așază-te cu noi la masă și nu mai fă atâta caz dintr-un nimic, că eu, unul, chiar mă străduiesc să îmi păstrez calmul și de mult vroiam, oricum, să continui discuția cu tine.</i> sunt:',
   'toate corecte;',
   'toate corecte, în afară de două;',
   'toate corecte, în afară de una;',
   'altă interpretare.',
   'B'),
  (40, 'Dintre cuvintele subliniate în enunțul: <i>Era o atmosferă <u>propice</u> (1) luării unei decizii, așa că nu mai plec <u>de-aicea</u> (2) până nu hotărâm ce facem cu acest <u>așa-zis</u> (3) medic.</i>, sunt adverbe cu formă corectă:',
   'numai (1) și (3);',
   'toate;',
   'niciunul;',
   'altă interpretare.',
   'C'),
  (41, 'Se dau următoarele definiri/explicări de cuvinte: <i>(1) surpriză, plăcută sau neplăcută; (2) nedumerire amestecată cu mâhnire și cu indignare; (3) stupoare.</i> Care dintre acestea poate/pot constitui sensul/sensurile cuvântului <u>consternare</u>, în diferite contexte și expresii?',
   'toate;',
   'numai (2) și (3);',
   'numai (1) și (3);',
   'altă interpretare.',
   'B'),
  (42, 'Se dau următoarele definiri/explicări de cuvinte: <i>(1) a ajunge sau a face să ajungă; (2) a deveni conștient; (3) a ajunge deodată undeva; (4) a-și pierde tăria, gustul, aroma; (5) a se lămuri.</i> Care dintre acestea poate/pot constitui sensul/sensurile verbului <u>a (se) trezi</u>, în diferite contexte și expresii?',
   'toate;',
   'numai (2) și (5);',
   'toate, în afară de (4);',
   'altă interpretare.',
   'A'),
  (43, 'Se dau următoarele definiri/explicări de cuvinte: <i>(1) a nu vedea cu ochi buni pe cineva; (2) a-și da consimțământul; (3) a accepta un reprezentant diplomatic; (4) a simpatiza.</i> Care dintre acestea poate/pot constitui sensul/sensurile verbului <u>a agrea</u>, în diferite contexte și expresii?',
   'toate;',
   'toate, în afară de (1);',
   'numai (2) și (4);',
   'altă interpretare.',
   'B'),
  (44, 'Fie secvența <i>...<u>nu i-i-n fire</u>...</i> Din punct de vedere ortografic, aceasta este:',
   'corectă, indiferent de context;',
   'incorectă, indiferent de context;',
   'corectă doar în anumite contexte;',
   'altă interpretare.',
   'A'),
  (45, 'Fie enunțurile: <i>(1) Deși le-au acordat votul acelor miniștri notorii, acum regretă. (2) Tare li-i că l-i uita curând pe cel care te-a iubit atât de mult. (3) Nu mă speriu eu așa de ușor, dar mă înnebunește ideea că or să ajungă să ne conducă aceiași ageamii pe care niciodată nu i-am agreat.</i> Numărul greșelilor de ortografie din acestea este:',
   'câte una, în (1), (2) și (3);',
   'una în (1), câte două în (2) și (3);',
   'niciuna în (1) și (2), două în (3);',
   'altă interpretare.',
   'C'),
  (46, 'În enunțul: <i>Nu mai am răbdare cu el, de când a avut îndrăzneala să ia decizii fără acceptul meu, așa că mă tem că în curând ne vom lua rămas-bun.</i>, numărul substantivelor defective de plural este:',
   'unu;',
   'două;',
   'patru;',
   'altă interpretare.',
   'B'),
  (47, 'Dintre cuvintele subliniate în enunțurile: <i>Toată viața mi-ai făcut numai <u>bine</u> (1), iar acest <u>bine</u> (2) ți-l voi întoarce într-o zi, căci un <u>bine</u> (3) nu trebuie uitat niciodată, iar <u>binele</u> (4) cu bine se răsplătește.</i>, sunt obținute prin conversiune:',
   'toate;',
   'numai (3) și (4);',
   'toate, în afară de (1);',
   'altă interpretare.',
   'A'),
  (48, 'În enunțul: <i>Avea un <u>background</u> (1) solid, din moment ce lucrase deja în mai multe <u>call-centere</u> (2) și, mai mult, avea <u>know-how-ul</u> (3) de a utiliza <u>pass-worduri</u> (4) complexe.</i>, dintre cuvintele subliniate sunt corecte:',
   'toate;',
   'numai (1) și (3);',
   'toate, în afară de (1);',
   'altă interpretare.',
   'B'),
  (49, 'Fie cuvintele: <i><u>corectitudinii</u> (1), <u>aptitudinii</u> (2), <u>savorii</u> (3), <u>candorii</u> (4)</i>. Sunt substantive care au formă de plural, dar nu și o altă formă de genitiv-dativ, aflată în variație liberă:',
   'toate;',
   'numai (2), (3), și (4);',
   'numai (2);',
   'altă interpretare.',
   'B'),
  (50, 'În enunțul: <i>Protestele lor au fost reprimate violent, dar, în schimb, tu fiind un specialist care ești ascultat în sferele înalte ale politicii, ai reușit să îi convingi pe guvernanți că ar trebui auzită și vocea rațiunii, și cea a celor mulți.</i>, există:',
   'patru greșeli;',
   'trei greșeli;',
   'o greșeală;',
   'altă interpretare.',
   'A')
) as v(item_no, q, a, b, c, d, k);
