-- =========================================================
-- 0097a · LICEU: planificarea clasei 9B, pe orarul din 21 septembrie
--
-- Una din cinci. Se rulează în ordine: 0097a, 0097b, 0097c, 0097d, 0097e.
-- Ultima ține paza pe toate cinci deodată.
--
-- DE CE CINCI FIȘIERE, NU UNUL. Întregul făcea 297 KB, iar SQL Editor îl
-- refuză: „request entity too large". Pe clasă iese vreo 53 KB și intră.
--
-- Punctul de pornire e `Diverse/ORAR 21 SEPT/Planificatoare/`, exportul din
-- planificatorul lui Marius. El e adevărul; documentele Word se nasc din el.
--
-- CE SE SCHIMBĂ, la toate cinci (comparat amprentă cu amprentă, nu din ochi):
--   · 9B și 11D — neschimbate. Intră totuși, ca regula să n-aibă excepții de
--     ținut minte, iar ce iese e la fel cu ce era.
--   · 11C și 11D — își mută ora de vineri, de pe 21 sept. încolo (11C de la
--     11:25 la 10:35, 11D de la 10:35 la 11:25).
--   · 10D — recapitularea inițială scade de la 4 ore la 3, „Unitatea 1. Basmul
--     cult" începe la ora 4 în loc de 5, iar cele două lecții care stăteau
--     împreună la ora 6 se despart în orele 5 și 6.
--   · 11B — se schimbă unitățile 2 și 3 (orele 21–56). Primele 20 rămân.
--   · 11C — plan nou din temelii: are acum exact planul lui 11D.
--
-- 12C ȘI 12D NU SE ATING: ele merg pe planificarea de bacalaureat (0093).
--
-- ZIUA SE SCRIE FĂRĂ DIACRITICE („marti"), ca în orar: îmbinarea dintre
-- planificare și orar se face pe ea, iar o literă deosebită ar fi rupt-o în
-- tăcere.
--
-- `blocuri` SE ȚINE CIUNTIT: rămân numele, sursa, unitatea și competențele; se
-- lasă afară `notiuni`, `activitati` și `ideeaDeRetinut` — materialul de predare,
-- nouă zecimi din greutate, pe care modulul nu-l citește nicăieri. El rămâne
-- întreg în JSON-urile din `Diverse/ORAR 21 SEPT/`.
--
-- SE ȘTERGE ȘI SE SCRIE LA LOC. Un `update` rând cu rând ar fi lăsat în urmă
-- orele care nu mai există, iar cheia unică (clasă, an, dată, ceas) s-ar fi
-- lovit de ele la 11C și 11D, unde ceasul se mută.
-- =========================================================

delete from public.school_plan where clasa = '9B' and an_scolar = '2026-2027';

insert into public.school_plan
  (clasa, an_scolar, nr, saptamana, zi, data, ora, fel, unitatea, titlu, blocuri) values
  ('9B','2026-2027',1,1,'marti','2026-09-08','16:35','bloc propriu','Recapitulare inițială','Recapitulare','[{"id": "m:1", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('9B','2026-2027',2,1,'joi','2026-09-10','13:10','bloc propriu','Recapitulare inițială','Recapitulare','[{"id": "m:2", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('9B','2026-2027',3,1,'joi','2026-09-10','14:00','bloc propriu','Recapitulare inițială','Evaluare','[{"id": "m:4", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('9B','2026-2027',4,2,'marti','2026-09-15','15:40','lectie','Unitatea 1. Literatura ca poveste despre lume','Cultura orală și cultura scrisă - Literatura populară și literatura cultă - Literatura ca reprezentare a realității - Literatura ca instituție culturală - Literatura ca spațiu de creație. Biografia și opera','[{"id": "u1:1", "fel": "lecție", "titlu": "Cultura orală și cultura scrisă", "titluOriginal": "Cultura orală și cultura scrisă", "sursa": "manual, pp. 12–13", "lectia": 1, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "2.2"]}, {"id": "u1:2", "fel": "lecție", "titlu": "Literatura populară și literatura cultă", "titluOriginal": "Literatura populară și literatura cultă", "sursa": "manual, pp. 12–13 și 15", "lectia": 2, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3", "2.2"]}, {"id": "u1:3", "fel": "lecție", "titlu": "Literatura ca reprezentare a realității", "titluOriginal": "Literatura ca reprezentare a realității", "sursa": "manual, pp. 14–16", "lectia": 3, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.2"]}, {"id": "u1:4", "fel": "lecție", "titlu": "Literatura ca instituție culturală", "titluOriginal": "Literatura ca instituție culturală", "sursa": "manual, pp. 14–16", "lectia": 4, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "2.1"]}, {"id": "u1:5", "fel": "lecție", "titlu": "Literatura ca spațiu de creație. Biografia și opera", "titluOriginal": "Literatura ca spațiu de creație. Biografia și opera", "sursa": "manual, pp. 14–16", "lectia": 5, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',5,2,'marti','2026-09-15','17:25','lectie','Unitatea 1. Literatura ca poveste despre lume','Literatura ca parcurs istoric: epocă, perioadă, școală literară - Cum se schimbă înțelegerea unei teme în timp','[{"id": "u1:6", "fel": "lecție", "titlu": "Literatura ca parcurs istoric: epocă, perioadă, școală literară", "titluOriginal": "Literatura ca parcurs istoric: epocă, perioadă, școală literară", "sursa": "manual, pp. 17–21", "lectia": 6, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "2.1", "2.2"]}, {"id": "u1:7", "fel": "lecție", "titlu": "Cum se schimbă înțelegerea unei teme în timp", "titluOriginal": "Cum se schimbă înțelegerea unei teme în timp", "sursa": "manual, pp. 17–21, grupaj de texte", "lectia": 7, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',6,2,'joi','2026-09-17','13:10','lectie','Unitatea 1. Literatura ca poveste despre lume','Genurile literare, un sistem variabil în timp - Forme ale literaturii de astăzi','[{"id": "u1:8", "fel": "lecție", "titlu": "Genurile literare, un sistem variabil în timp", "titluOriginal": "Genurile literare, un sistem variabil în timp", "sursa": "manual, pp. 17–21", "lectia": 8, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.3", "2.2"]}, {"id": "u1:9", "fel": "lecție", "titlu": "Forme ale literaturii de astăzi", "titluOriginal": "Forme ale literaturii de astăzi", "sursa": "manual, pp. 22–23, grupaj de texte", "lectia": 9, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',7,3,'marti','2026-09-22','15:40','lectie','Unitatea 1. Literatura ca poveste despre lume','Cititorul, creator de sens - Monomitul. Modelul lui Joseph Campbell','[{"id": "u1:10", "fel": "lecție", "titlu": "Cititorul, creator de sens", "titluOriginal": "Cititorul, creator de sens", "sursa": "manual, pp. 22–23; Rui Zink, „Cititorul din peșteră”", "lectia": 10, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}, {"id": "u1:11", "fel": "lecție", "titlu": "Monomitul. Modelul lui Joseph Campbell", "titluOriginal": "Monomitul. Modelul lui Joseph Campbell", "sursa": "manual, pp. 24–26", "lectia": 11, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',8,3,'marti','2026-09-22','17:25','lectie','Unitatea 1. Literatura ca poveste despre lume','Atelier de limbă română: etimologia unui cuvânt','[{"id": "u1:12", "fel": "lecție", "titlu": "Atelier de limbă română: etimologia unui cuvânt", "titluOriginal": "Atelier de limbă română: etimologia unui cuvânt", "sursa": "manual, pp. 24–25", "lectia": 12, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["3.1"]}]'::jsonb),
  ('9B','2026-2027',9,3,'joi','2026-09-24','13:10','lectie','Unitatea 1. Literatura ca poveste despre lume','Aceeași aventură, două povești: „Prâslea” și mitul lui Faeton - Petre Ispirescu și basmul popular','[{"id": "u1:13", "fel": "lecție", "titlu": "Aceeași aventură, două povești: „Prâslea” și mitul lui Faeton", "titluOriginal": "Aceeași aventură, două povești: „Prâslea” și mitul lui Faeton", "sursa": "manual, pp. 24–26", "lectia": 13, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.2", "2.2"]}, {"id": "u1:14", "fel": "lecție", "titlu": "Petre Ispirescu și basmul popular", "titluOriginal": "Petre Ispirescu și basmul popular", "sursa": "manual, pp. 26–29", "lectia": 14, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',10,4,'marti','2026-09-29','15:40','lectie','Unitatea 1. Literatura ca poveste despre lume','Lectura textului. Primele impresii. Jurnalul de reflecție - Călătoria eroului în „Greuceanu”. Fabulosul','[{"id": "u1:15", "fel": "lecție", "titlu": "Lectura textului. Primele impresii. Jurnalul de reflecție", "titluOriginal": "Lectura textului. Primele impresii. Jurnalul de reflecție", "sursa": "manual, pp. 26–29", "lectia": 15, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}, {"id": "u1:16", "fel": "lecție", "titlu": "Călătoria eroului în „Greuceanu”. Fabulosul", "titluOriginal": "Călătoria eroului în „Greuceanu”. Fabulosul", "sursa": "manual, pp. 29–30", "lectia": 16, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "2.2"]}]'::jsonb),
  ('9B','2026-2027',11,4,'marti','2026-09-29','17:25','lectie','Unitatea 1. Literatura ca poveste despre lume','Atelier de limbă română: limba standard și oralitatea basmului','[{"id": "u1:17", "fel": "lecție", "titlu": "Atelier de limbă română: limba standard și oralitatea basmului", "titluOriginal": "Atelier de limbă română: limba standard și oralitatea basmului", "sursa": "manual, p. 31", "lectia": 17, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2"]}]'::jsonb),
  ('9B','2026-2027',12,4,'joi','2026-10-01','13:10','lectie','Unitatea 1. Literatura ca poveste despre lume','Eroul și relațiile lui: ajutoare, adversari, obiecte','[{"id": "u1:18", "fel": "lecție", "titlu": "Eroul și relațiile lui: ajutoare, adversari, obiecte", "titluOriginal": "Eroul și relațiile lui: ajutoare, adversari, obiecte", "sursa": "manual, p. 32", "lectia": 18, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.2"]}]'::jsonb),
  ('9B','2026-2027',13,5,'marti','2026-10-06','15:40','lectie','Unitatea 1. Literatura ca poveste despre lume','Atelier de comunicare orală: planificarea și susținerea unui discurs','[{"id": "u1:19", "fel": "lecție", "titlu": "Atelier de comunicare orală: planificarea și susținerea unui discurs", "titluOriginal": "Atelier de comunicare orală: planificarea și susținerea unui discurs", "sursa": "manual, p. 33", "lectia": 19, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.3", "3.3"]}]'::jsonb),
  ('9B','2026-2027',14,5,'marti','2026-10-06','17:25','lectie','Unitatea 1. Literatura ca poveste despre lume','Ion Creangă și basmul cult - Călătoria lui Harap-Alb și construcția personajului','[{"id": "u1:20", "fel": "lecție", "titlu": "Ion Creangă și basmul cult", "titluOriginal": "Ion Creangă și basmul cult", "sursa": "manual, pp. 34–37", "lectia": 20, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}, {"id": "u1:21", "fel": "lecție", "titlu": "Călătoria lui Harap-Alb și construcția personajului", "titluOriginal": "Călătoria lui Harap-Alb și construcția personajului", "sursa": "manual, pp. 38–39", "lectia": 21, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',15,5,'joi','2026-10-08','13:10','lectie','Unitatea 1. Literatura ca poveste despre lume','Atelier de limbă română: regionalismele - Interpretarea textului. Reflectează și argumentează','[{"id": "u1:22", "fel": "lecție", "titlu": "Atelier de limbă română: regionalismele", "titluOriginal": "Atelier de limbă română: regionalismele", "sursa": "manual, pp. 38–39", "lectia": 22, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2"]}, {"id": "u1:23", "fel": "lecție", "titlu": "Interpretarea textului. Reflectează și argumentează", "titluOriginal": "Interpretarea textului. Reflectează și argumentează", "sursa": "manual, pp. 40–41", "lectia": 23, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "3.3"]}]'::jsonb),
  ('9B','2026-2027',16,7,'marti','2026-10-20','15:40','lectie','Unitatea 1. Literatura ca poveste despre lume','Extinderi: monomitul în literatura, filmul și jocurile de azi - Atelier de redactare: eseul de opinie','[{"id": "u1:25", "fel": "lecție", "titlu": "Extinderi: monomitul în literatura, filmul și jocurile de azi", "titluOriginal": "Extinderi: monomitul în literatura, filmul și jocurile de azi", "sursa": "manual, pp. 43–44", "lectia": 25, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.3", "2.2"]}, {"id": "u1:24", "fel": "lecție", "titlu": "Atelier de redactare: eseul de opinie", "titluOriginal": "Atelier de redactare: eseul de opinie", "sursa": "manual, pp. 41–42", "lectia": 24, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.3", "3.3"]}]'::jsonb),
  ('9B','2026-2027',17,7,'marti','2026-10-20','17:25','lectie','Unitatea 1. Literatura ca poveste despre lume','Recapitulare','[{"id": "u1:26", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "manual, pp. 45–47", "lectia": 26, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',18,7,'joi','2026-10-22','13:10','lectie','Unitatea 1. Literatura ca poveste despre lume','Evaluare sumativă: eseul de opinie, comprehensiunea textului','[{"id": "u1:28", "fel": "lecție", "titlu": "Evaluare sumativă: eseul de opinie, comprehensiunea textului", "titluOriginal": "Evaluare sumativă: eseul de opinie sau prezentarea orală", "sursa": "manual, p. 47", "lectia": 28, "unitate": "Unitatea 1. Literatura ca poveste despre lume", "unitateId": "p1", "competenteSpecifice": ["1.3", "2.2", "3.3", "3.4"]}]'::jsonb),
  ('9B','2026-2027',19,8,'marti','2026-11-03','15:40','lectie','Unitatea 2. Începuturile scrisului în limba română','Secolele XVI–XVII: țările române între imperii - Primele instituții ale scrisului: mănăstirea, cancelaria, tiparul - Manuscrisul, tipăritura, traducerea: cum circula o carte','[{"id": "u2:1", "fel": "lecție", "titlu": "Secolele XVI–XVII: țările române între imperii", "titluOriginal": "Secolele XVI–XVII: țările române între imperii", "sursa": "manual, pp. 50–51", "lectia": 1, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1", "2.2"]}, {"id": "u2:2", "fel": "lecție", "titlu": "Primele instituții ale scrisului: mănăstirea, cancelaria, tiparul", "titluOriginal": "Primele instituții ale scrisului: mănăstirea, cancelaria, tiparul", "sursa": "manual, pp. 52–53", "lectia": 2, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1"]}, {"id": "u2:3", "fel": "lecție", "titlu": "Manuscrisul, tipăritura, traducerea: cum circula o carte", "titluOriginal": "Manuscrisul, tipăritura, traducerea: cum circula o carte", "sursa": "manual, pp. 52–53", "lectia": 3, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1", "3.1"]}]'::jsonb),
  ('9B','2026-2027',20,8,'marti','2026-11-03','17:25','lectie','Unitatea 2. Începuturile scrisului în limba română','Umanismul și ecourile Renașterii în cultura română - Imaginarul medieval: cum vedeau lumea oamenii epocii - Timpuri, oameni, întâmplări (grupaj de texte)','[{"id": "u2:4", "fel": "lecție", "titlu": "Umanismul și ecourile Renașterii în cultura română", "titluOriginal": "Umanismul și ecourile Renașterii în cultura română", "sursa": "manual, pp. 54–55", "lectia": 4, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1", "2.2"]}, {"id": "u2:5", "fel": "lecție", "titlu": "Imaginarul medieval: cum vedeau lumea oamenii epocii", "titluOriginal": "Imaginarul medieval: cum vedeau lumea oamenii epocii", "sursa": "manual, pp. 54–55", "lectia": 5, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.2"]}, {"id": "u2:6", "fel": "lecție", "titlu": "Timpuri, oameni, întâmplări (grupaj de texte)", "titluOriginal": "Timpuri, oameni, întâmplări (grupaj de texte)", "sursa": "manual, pp. 56–57", "lectia": 6, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "1.2", "2.2"]}]'::jsonb),
  ('9B','2026-2027',21,8,'joi','2026-11-05','13:10','lectie','Unitatea 2. Începuturile scrisului în limba română','Conexiuni cu spațiul românesc (grupaj de texte)','[{"id": "u2:7", "fel": "lecție", "titlu": "Conexiuni cu spațiul românesc (grupaj de texte)", "titluOriginal": "Conexiuni cu spațiul românesc (grupaj de texte)", "sursa": "manual, pp. 58–59", "lectia": 7, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',22,9,'marti','2026-11-10','15:40','lectie','Unitatea 2. Începuturile scrisului în limba română','Grigore Ureche și cronica moldovenească - Lectura textului: „De moartea lui Ștefan vodă celui Bun”','[{"id": "u2:8", "fel": "lecție", "titlu": "Grigore Ureche și cronica moldovenească", "titluOriginal": "Grigore Ureche și cronica moldovenească", "sursa": "manual, pp. 60–61", "lectia": 8, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1"]}, {"id": "u2:9", "fel": "lecție", "titlu": "Lectura textului: „De moartea lui Ștefan vodă celui Bun”", "titluOriginal": "Lectura textului: „De moartea lui Ștefan vodă celui Bun”", "sursa": "manual, pp. 60–63", "lectia": 9, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.2", "3.1"]}]'::jsonb),
  ('9B','2026-2027',23,9,'marti','2026-11-10','17:25','lectie','Unitatea 2. Începuturile scrisului în limba română','Cronica: discurs istoric, adevăr și interpretare','[{"id": "u2:10", "fel": "lecție", "titlu": "Cronica: discurs istoric, adevăr și interpretare", "titluOriginal": "Cronica: discurs istoric, adevăr și interpretare", "sursa": "manual, pp. 60–63", "lectia": 10, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',24,9,'joi','2026-11-12','13:10','lectie','Unitatea 2. Începuturile scrisului în limba română','Arta portretului: cum se construiește o figură istorică','[{"id": "u2:11", "fel": "lecție", "titlu": "Arta portretului: cum se construiește o figură istorică", "titluOriginal": "Arta portretului: cum se construiește o figură istorică", "sursa": "manual, pp. 62–63", "lectia": 11, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.2", "1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',25,10,'marti','2026-11-17','15:40','lectie','Unitatea 2. Începuturile scrisului în limba română','Atelier de limbă română: arhaismele - Atelier de limbă română: cum se leagă ideile într-un text. Coerența și coeziunea','[{"id": "u2:12", "fel": "lecție", "titlu": "Atelier de limbă română: arhaismele", "titluOriginal": "Atelier de limbă română: arhaismele", "sursa": "manual, p. 64", "lectia": 12, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["3.1", "3.2"]}, {"id": "u2:13", "fel": "lecție", "titlu": "Atelier de limbă română: cum se leagă ideile într-un text. Coerența și coeziunea", "titluOriginal": "Atelier de limbă română: cum se leagă ideile într-un text. Coerența și coeziunea", "sursa": "manual, pp. 65–66", "lectia": 13, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["3.2"]}]'::jsonb),
  ('9B','2026-2027',26,10,'marti','2026-11-17','17:25','lectie','Unitatea 2. Începuturile scrisului în limba română','Atelier de redactare: conspectul','[{"id": "u2:14", "fel": "lecție", "titlu": "Atelier de redactare: conspectul", "titluOriginal": "Atelier de redactare: conspectul", "sursa": "manual, p. 67", "lectia": 14, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["3.3"]}]'::jsonb),
  ('9B','2026-2027',27,10,'joi','2026-11-19','13:10','lectie','Unitatea 2. Începuturile scrisului în limba română','Atelier de comunicare orală: coerența și coeziunea în vorbire','[{"id": "u2:15", "fel": "lecție", "titlu": "Atelier de comunicare orală: coerența și coeziunea în vorbire", "titluOriginal": "Atelier de comunicare orală: coerența și coeziunea în vorbire", "sursa": "manual, pp. 68–69", "lectia": 15, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["3.2", "3.3"]}]'::jsonb),
  ('9B','2026-2027',28,11,'marti','2026-11-24','15:40','lectie','Unitatea 2. Începuturile scrisului în limba română','Extinderi: Neculce, Groșan și portretul în artele plastice','[{"id": "u2:16", "fel": "lecție", "titlu": "Extinderi: Neculce, Groșan și portretul în artele plastice", "titluOriginal": "Extinderi: Neculce, Groșan și portretul în artele plastice", "sursa": "manual, p. 70", "lectia": 16, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',29,11,'marti','2026-11-24','17:25','lectie','Unitatea 2. Începuturile scrisului în limba română','Recapitulare','[{"id": "u2:17", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "manual, pp. 70–71", "lectia": 17, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "1.2", "3.1"]}]'::jsonb),
  ('9B','2026-2027',30,11,'joi','2026-11-26','13:10','lectie','Unitatea 2. Începuturile scrisului în limba română','Evaluare sumativă: test - Evaluare sumativă: conspect sau prezentare orală','[{"id": "u2:18", "fel": "lecție", "titlu": "Evaluare sumativă: test", "titluOriginal": "Evaluare sumativă: test", "sursa": "manual, p. 71", "lectia": 18, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.1", "1.2", "2.1", "3.1"]}, {"id": "u2:19", "fel": "lecție", "titlu": "Evaluare sumativă: conspect sau prezentare orală", "titluOriginal": "Evaluare sumativă: conspect sau prezentare orală", "sursa": "manual, p. 71", "lectia": 19, "unitate": "Unitatea 2. Începuturile scrisului în limba română", "unitateId": "p2", "competenteSpecifice": ["1.3", "2.2", "3.3", "3.4"]}]'::jsonb),
  ('9B','2026-2027',31,12,'joi','2026-12-03','13:10','bloc propriu','Unitatea 3. Afirmarea conștiinței culturale','Recapitulare','[{"id": "m:8", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('9B','2026-2027',32,13,'marti','2026-12-08','15:40','bloc propriu','Unitatea 3. Afirmarea conștiinței culturale','Teză','[{"id": "m:9", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('9B','2026-2027',33,13,'marti','2026-12-08','17:25','lectie','Unitatea 3. Afirmarea conștiinței culturale','Secolul al XVIII-lea: fanarioți, Ardeal, idei noi - Secolul Luminilor: rațiunea, Enciclopedia, toleranța','[{"id": "u3:1", "fel": "lecție", "titlu": "Secolul al XVIII-lea: fanarioți, Ardeal, idei noi", "titluOriginal": "Secolul al XVIII-lea: fanarioți, Ardeal, idei noi", "sursa": "manual, pp. 73–75", "lectia": 1, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "1.2", "2.1"]}, {"id": "u3:2", "fel": "lecție", "titlu": "Secolul Luminilor: rațiunea, Enciclopedia, toleranța", "titluOriginal": "Secolul Luminilor: rațiunea, Enciclopedia, toleranța", "sursa": "manual, pp. 76–77", "lectia": 2, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1"]}]'::jsonb),
  ('9B','2026-2027',34,13,'joi','2026-12-10','13:10','lectie','Unitatea 3. Afirmarea conștiinței culturale','Școala Ardeleană: latinitate, istorie, deșteptare națională','[{"id": "u3:3", "fel": "lecție", "titlu": "Școala Ardeleană: latinitate, istorie, deșteptare națională", "titluOriginal": "Școala Ardeleană: latinitate, istorie, deșteptare națională", "sursa": "manual, pp. 78–79", "lectia": 3, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1", "3.1"]}]'::jsonb),
  ('9B','2026-2027',35,14,'marti','2026-12-15','15:40','lectie','Unitatea 3. Afirmarea conștiinței culturale','Sub lentila rațiunii și a ironiei (grupaj de texte)','[{"id": "u3:4", "fel": "lecție", "titlu": "Sub lentila rațiunii și a ironiei (grupaj de texte)", "titluOriginal": "Sub lentila rațiunii și a ironiei (grupaj de texte)", "sursa": "manual, pp. 80–81", "lectia": 4, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',36,14,'marti','2026-12-15','17:25','lectie','Unitatea 3. Afirmarea conștiinței culturale','Repere ale gândirii iluministe românești (grupaj de texte)','[{"id": "u3:5", "fel": "lecție", "titlu": "Repere ale gândirii iluministe românești (grupaj de texte)", "titluOriginal": "Repere ale gândirii iluministe românești (grupaj de texte)", "sursa": "manual, pp. 80–81", "lectia": 5, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',37,14,'joi','2026-12-17','13:10','lectie','Unitatea 3. Afirmarea conștiinței culturale','Dinicu Golescu și cea dintâi carte de călătorie - Lectura textului. Admirația și comparația','[{"id": "u3:6", "fel": "lecție", "titlu": "Dinicu Golescu și cea dintâi carte de călătorie", "titluOriginal": "Dinicu Golescu și cea dintâi carte de călătorie", "sursa": "manual, pp. 82–83", "lectia": 6, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1"]}, {"id": "u3:7", "fel": "lecție", "titlu": "Lectura textului. Admirația și comparația", "titluOriginal": "Lectura textului. Admirația și comparația", "sursa": "manual, pp. 84–85", "lectia": 7, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',38,15,'marti','2026-12-22','15:40','lectie','Unitatea 3. Afirmarea conștiinței culturale','Privirea străinului: „Scrisori persane” de Montesquieu - Atelier de redactare: jurnalul imersiv','[{"id": "u3:8", "fel": "lecție", "titlu": "Privirea străinului: „Scrisori persane” de Montesquieu", "titluOriginal": "Privirea străinului: „Scrisori persane” de Montesquieu", "sursa": "manual, pp. 84–85", "lectia": 8, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.2", "2.1", "2.2"]}, {"id": "u3:9", "fel": "lecție", "titlu": "Atelier de redactare: jurnalul imersiv", "titluOriginal": "Atelier de redactare: jurnalul imersiv", "sursa": "manual, p. 86", "lectia": 9, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["3.3", "3.4"]}]'::jsonb),
  ('9B','2026-2027',39,15,'marti','2026-12-22','17:25','lectie','Unitatea 3. Afirmarea conștiinței culturale','Mijloace de transport în epocă. Franklin și entuziasmul tehnic','[{"id": "u3:10", "fel": "lecție", "titlu": "Mijloace de transport în epocă. Franklin și entuziasmul tehnic", "titluOriginal": "Mijloace de transport în epocă. Franklin și entuziasmul tehnic", "sursa": "manual, pp. 87–88", "lectia": 10, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',40,16,'marti','2027-01-12','15:40','lectie','Unitatea 3. Afirmarea conștiinței culturale','Atelier de comunicare orală: monologul','[{"id": "u3:11", "fel": "lecție", "titlu": "Atelier de comunicare orală: monologul", "titluOriginal": "Atelier de comunicare orală: monologul", "sursa": "manual, p. 89", "lectia": 11, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["3.3", "3.4"]}]'::jsonb),
  ('9B','2026-2027',41,16,'marti','2027-01-12','17:25','lectie','Unitatea 3. Afirmarea conștiinței culturale','Extinderi: „Trei săptămâni în Himalaya” de Marius Chivu','[{"id": "u3:12", "fel": "lecție", "titlu": "Extinderi: „Trei săptămâni în Himalaya” de Marius Chivu", "titluOriginal": "Extinderi: „Trei săptămâni în Himalaya” de Marius Chivu", "sursa": "manual, p. 90", "lectia": 12, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',42,16,'joi','2027-01-14','13:10','lectie','Unitatea 3. Afirmarea conștiinței culturale','Originea latină și etapele limbii române','[{"id": "u3:13", "fel": "lecție", "titlu": "Originea latină și etapele limbii române", "titluOriginal": "Originea latină și etapele limbii române", "sursa": "manual, pp. 91–92", "lectia": 13, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.3"]}]'::jsonb),
  ('9B','2026-2027',43,17,'marti','2027-01-19','15:40','lectie','Unitatea 3. Afirmarea conștiinței culturale','Arhaisme, neologisme, etimologie: aplicații','[{"id": "u3:14", "fel": "lecție", "titlu": "Arhaisme, neologisme, etimologie: aplicații", "titluOriginal": "Arhaisme, neologisme, etimologie: aplicații", "sursa": "manual, pp. 92–93", "lectia": 14, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.3", "3.4"]}]'::jsonb),
  ('9B','2026-2027',44,17,'marti','2027-01-19','17:25','lectie','Unitatea 3. Afirmarea conștiinței culturale','Recapitulare','[{"id": "u3:15", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "manual, pp. 94–95", "lectia": 15, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',45,17,'joi','2027-01-21','13:10','lectie','Unitatea 3. Afirmarea conștiinței culturale','Evaluare sumativă: lectură și comprehensiune - Evaluare sumativă: redactare și produs multimodal','[{"id": "u3:16", "fel": "lecție", "titlu": "Evaluare sumativă: lectură și comprehensiune", "titluOriginal": "Evaluare sumativă: lectură și comprehensiune", "sursa": "manual, p. 96", "lectia": 16, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["1.1", "1.2", "2.1"]}, {"id": "u3:17", "fel": "lecție", "titlu": "Evaluare sumativă: redactare și produs multimodal", "titluOriginal": "Evaluare sumativă: redactare și produs multimodal", "sursa": "manual, p. 96", "lectia": 17, "unitate": "Unitatea 3. Afirmarea conștiinței culturale", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.3", "3.4"]}]'::jsonb),
  ('9B','2026-2027',46,18,'marti','2027-01-26','15:40','lectie','Unitatea 4. Modernizarea formelor literare','Prima jumătate a secolului al XIX-lea: vechi și nou','[{"id": "u4:1", "fel": "lecție", "titlu": "Prima jumătate a secolului al XIX-lea: vechi și nou", "titluOriginal": "Prima jumătate a secolului al XIX-lea: vechi și nou", "sursa": "manual, pp. 102–103", "lectia": 1, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',47,18,'marti','2027-01-26','17:25','lectie','Unitatea 4. Modernizarea formelor literare','De la clasicism la romantism','[{"id": "u4:2", "fel": "lecție", "titlu": "De la clasicism la romantism", "titluOriginal": "De la clasicism la romantism", "sursa": "manual, pp. 104–105", "lectia": 2, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',48,18,'joi','2027-01-28','13:10','lectie','Unitatea 4. Modernizarea formelor literare','Romantismul pașoptist și deschiderile europene - Puterea unei idei: „Dacia literară” și programul ei','[{"id": "u4:3", "fel": "lecție", "titlu": "Romantismul pașoptist și deschiderile europene", "titluOriginal": "Romantismul pașoptist și deschiderile europene", "sursa": "manual, pp. 106–107, grupaje de texte", "lectia": 3, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "2.1", "2.2"]}, {"id": "u4:4", "fel": "lecție", "titlu": "Puterea unei idei: „Dacia literară” și programul ei", "titluOriginal": "Puterea unei idei: „Dacia literară” și programul ei", "sursa": "manual, pp. 108–109", "lectia": 4, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',49,19,'marti','2027-02-02','15:40','lectie','Unitatea 4. Modernizarea formelor literare','Cele patru idei ale programului','[{"id": "u4:5", "fel": "lecție", "titlu": "Cele patru idei ale programului", "titluOriginal": "Cele patru idei ale programului", "sursa": "manual, pp. 108–109", "lectia": 5, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',50,19,'marti','2027-02-02','17:25','lectie','Unitatea 4. Modernizarea formelor literare','Atelier de limbă română: mărci anaforice și cataforice','[{"id": "u4:6", "fel": "lecție", "titlu": "Atelier de limbă română: mărci anaforice și cataforice", "titluOriginal": "Atelier de limbă română: mărci anaforice și cataforice", "sursa": "manual, p. 110", "lectia": 6, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["3.2"]}]'::jsonb),
  ('9B','2026-2027',51,19,'joi','2027-02-04','13:10','lectie','Unitatea 4. Modernizarea formelor literare','Extinderi: rolul programului pașoptist','[{"id": "u4:7", "fel": "lecție", "titlu": "Extinderi: rolul programului pașoptist", "titluOriginal": "Extinderi: rolul programului pașoptist", "sursa": "manual, p. 110", "lectia": 7, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.3", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',52,20,'marti','2027-02-09','15:40','lectie','Unitatea 4. Modernizarea formelor literare','„Alexandru Lăpușneanul”: intrarea în lumea textului','[{"id": "u4:8", "fel": "lecție", "titlu": "„Alexandru Lăpușneanul”: intrarea în lumea textului", "titluOriginal": "„Alexandru Lăpușneanul”: intrarea în lumea textului", "sursa": "manual, pp. 111–113", "lectia": 8, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',53,20,'marti','2027-02-09','17:25','lectie','Unitatea 4. Modernizarea formelor literare','Cele patru capitole și cele patru replici','[{"id": "u4:9", "fel": "lecție", "titlu": "Cele patru capitole și cele patru replici", "titluOriginal": "Cele patru capitole și cele patru replici", "sursa": "manual, pp. 111–115", "lectia": 9, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',54,20,'joi','2027-02-11','13:10','lectie','Unitatea 4. Modernizarea formelor literare','Discursul ca instrument al puterii. Scena de la Mitropolie','[{"id": "u4:10", "fel": "lecție", "titlu": "Discursul ca instrument al puterii. Scena de la Mitropolie", "titluOriginal": "Discursul ca instrument al puterii. Scena de la Mitropolie", "sursa": "manual, pp. 114–115", "lectia": 10, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.2", "1.3", "3.2"]}]'::jsonb),
  ('9B','2026-2027',55,21,'marti','2027-02-16','15:40','lectie','Unitatea 4. Modernizarea formelor literare','Construcția personajului romantic - Nuvela romantică: istorie și ficțiune','[{"id": "u4:11", "fel": "lecție", "titlu": "Construcția personajului romantic", "titluOriginal": "Construcția personajului romantic", "sursa": "manual, pp. 114–116", "lectia": 11, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.2", "1.3", "2.2"]}, {"id": "u4:12", "fel": "lecție", "titlu": "Nuvela romantică: istorie și ficțiune", "titluOriginal": "Nuvela romantică: istorie și ficțiune", "sursa": "manual, pp. 116–117", "lectia": 12, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',56,21,'marti','2027-02-16','17:25','lectie','Unitatea 4. Modernizarea formelor literare','Atelier de limbă română: mărcile deictice - Atelier de limbă română: împrumuturi și neologisme','[{"id": "u4:13", "fel": "lecție", "titlu": "Atelier de limbă română: mărcile deictice", "titluOriginal": "Atelier de limbă română: mărcile deictice", "sursa": "manual, p. 117", "lectia": 13, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["3.2"]}, {"id": "u4:14", "fel": "lecție", "titlu": "Atelier de limbă română: împrumuturi și neologisme", "titluOriginal": "Atelier de limbă română: împrumuturi și neologisme", "sursa": "manual, p. 118", "lectia": 14, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.3"]}]'::jsonb),
  ('9B','2026-2027',57,21,'joi','2027-02-18','13:10','lectie','Unitatea 4. Modernizarea formelor literare','Interpretare și extinderi: chipurile puterii','[{"id": "u4:15", "fel": "lecție", "titlu": "Interpretare și extinderi: chipurile puterii", "titluOriginal": "Interpretare și extinderi: chipurile puterii", "sursa": "manual, pp. 118–119", "lectia": 15, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',58,22,'marti','2027-03-02','15:40','lectie','Unitatea 4. Modernizarea formelor literare','„Monastirea Argeșului”: intrarea în text - Mitul zidirii: creație, jertfă, vină','[{"id": "u4:16", "fel": "lecție", "titlu": "„Monastirea Argeșului”: intrarea în text", "titluOriginal": "„Monastirea Argeșului”: intrarea în text", "sursa": "manual, pp. 120–121", "lectia": 16, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.1"]}, {"id": "u4:17", "fel": "lecție", "titlu": "Mitul zidirii: creație, jertfă, vină", "titluOriginal": "Mitul zidirii: creație, jertfă, vină", "sursa": "manual, pp. 121–122", "lectia": 17, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',59,22,'marti','2027-03-02','17:25','lectie','Unitatea 4. Modernizarea formelor literare','Atelier de comunicare orală: dezbaterea și negocierea','[{"id": "u4:18", "fel": "lecție", "titlu": "Atelier de comunicare orală: dezbaterea și negocierea", "titluOriginal": "Atelier de comunicare orală: dezbaterea și negocierea", "sursa": "manual, p. 123", "lectia": 18, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.3", "3.3"]}]'::jsonb),
  ('9B','2026-2027',60,22,'joi','2027-03-04','13:10','lectie','Unitatea 4. Modernizarea formelor literare','Atelier de limbă română: elipsa - Atelier de redactare: eseul argumentativ','[{"id": "u4:19", "fel": "lecție", "titlu": "Atelier de limbă română: elipsa", "titluOriginal": "Atelier de limbă română: elipsa", "sursa": "manual, p. 124", "lectia": 19, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["3.2"]}, {"id": "u4:20", "fel": "lecție", "titlu": "Atelier de redactare: eseul argumentativ", "titluOriginal": "Atelier de redactare: eseul argumentativ", "sursa": "manual, pp. 124–125", "lectia": 20, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["3.2", "3.3"]}]'::jsonb),
  ('9B','2026-2027',61,23,'marti','2027-03-09','15:40','lectie','Unitatea 4. Modernizarea formelor literare','Extinderi: rescrierile motivului zidirii','[{"id": "u4:21", "fel": "lecție", "titlu": "Extinderi: rescrierile motivului zidirii", "titluOriginal": "Extinderi: rescrierile motivului zidirii", "sursa": "manual, p. 125", "lectia": 21, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',62,23,'marti','2027-03-09','17:25','lectie','Unitatea 4. Modernizarea formelor literare','Recapitulare','[{"id": "u4:22", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "manual, pp. 126–127", "lectia": 22, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.2"]}]'::jsonb),
  ('9B','2026-2027',63,23,'joi','2027-03-11','13:10','lectie','Unitatea 4. Modernizarea formelor literare','Evaluare sumativă: test - Evaluare sumativă: prezentare orală','[{"id": "u4:23", "fel": "lecție", "titlu": "Evaluare sumativă: test", "titluOriginal": "Evaluare sumativă: test", "sursa": "manual, p. 128", "lectia": 23, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.1", "3.3"]}, {"id": "u4:24", "fel": "lecție", "titlu": "Evaluare sumativă: prezentare orală", "titluOriginal": "Evaluare sumativă: prezentare orală", "sursa": "manual, p. 128", "lectia": 24, "unitate": "Unitatea 4. Modernizarea formelor literare", "unitateId": "p4", "competenteSpecifice": ["1.3", "2.2", "3.3"]}]'::jsonb),
  ('9B','2026-2027',64,24,'marti','2027-03-16','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','A doua jumătate a secolului al XIX-lea: statul modern','[{"id": "u5:1", "fel": "lecție", "titlu": "A doua jumătate a secolului al XIX-lea: statul modern", "titluOriginal": "A doua jumătate a secolului al XIX-lea: statul modern", "sursa": "manual, pp. 139–141", "lectia": 1, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',65,24,'marti','2027-03-16','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Junimea și „Convorbiri literare” - Societate literară și sistem literar','[{"id": "u5:2", "fel": "lecție", "titlu": "Junimea și „Convorbiri literare”", "titluOriginal": "Junimea și „Convorbiri literare”", "sursa": "manual, pp. 142–143", "lectia": 2, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "2.1"]}, {"id": "u5:3", "fel": "lecție", "titlu": "Societate literară și sistem literar", "titluOriginal": "Societate literară și sistem literar", "sursa": "manual, pp. 142–143", "lectia": 3, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',66,24,'joi','2027-03-18','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Realismul european și coexistența curentelor','[{"id": "u5:4", "fel": "lecție", "titlu": "Realismul european și coexistența curentelor", "titluOriginal": "Realismul european și coexistența curentelor", "sursa": "manual, pp. 144–145", "lectia": 4, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "2.1", "2.2"]}]'::jsonb),
  ('9B','2026-2027',67,25,'marti','2027-03-23','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Lirica feminină în epoca Junimii (grupaj de texte)','[{"id": "u5:5", "fel": "lecție", "titlu": "Lirica feminină în epoca Junimii (grupaj de texte)", "titluOriginal": "Lirica feminină în epoca Junimii (grupaj de texte)", "sursa": "manual, pp. 146–147", "lectia": 5, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',68,25,'marti','2027-03-23','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Un personaj realist: cerșetorul (grupaj de texte)','[{"id": "u5:6", "fel": "lecție", "titlu": "Un personaj realist: cerșetorul (grupaj de texte)", "titluOriginal": "Un personaj realist: cerșetorul (grupaj de texte)", "sursa": "manual, pp. 146–147", "lectia": 6, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.2"]}]'::jsonb),
  ('9B','2026-2027',69,25,'joi','2027-03-25','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Titu Maiorescu și critica de direcție - „În contra direcției de astăzi în cultura română”: formele fără fond','[{"id": "u5:7", "fel": "lecție", "titlu": "Titu Maiorescu și critica de direcție", "titluOriginal": "Titu Maiorescu și critica de direcție", "sursa": "manual, pp. 148–149", "lectia": 7, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.1"]}, {"id": "u5:8", "fel": "lecție", "titlu": "„În contra direcției de astăzi în cultura română”: formele fără fond", "titluOriginal": "„În contra direcției de astăzi în cultura română”: formele fără fond", "sursa": "manual, pp. 148–150", "lectia": 8, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.1", "3.3"]}]'::jsonb),
  ('9B','2026-2027',70,26,'marti','2027-03-30','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Atelier de limbă română: propoziție, frază, text. Organizarea transfrastică','[{"id": "u5:9", "fel": "lecție", "titlu": "Atelier de limbă română: propoziție, frază, text. Organizarea transfrastică", "titluOriginal": "Atelier de limbă română: propoziție, frază, text. Organizarea transfrastică", "sursa": "manual, p. 151", "lectia": 9, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["3.2"]}]'::jsonb),
  ('9B','2026-2027',71,26,'marti','2027-03-30','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','„Comediile d-lui Caragiale”: apărarea unui scriitor','[{"id": "u5:10", "fel": "lecție", "titlu": "„Comediile d-lui Caragiale”: apărarea unui scriitor", "titluOriginal": "„Comediile d-lui Caragiale”: apărarea unui scriitor", "sursa": "manual, pp. 152–153", "lectia": 10, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',72,26,'joi','2027-04-01','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Extinderi: „O conferență” de Caragiale și „Ofelia” lui Millais','[{"id": "u5:11", "fel": "lecție", "titlu": "Extinderi: „O conferență” de Caragiale și „Ofelia” lui Millais", "titluOriginal": "Extinderi: „O conferență” de Caragiale și „Ofelia” lui Millais", "sursa": "manual, p. 153", "lectia": 11, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',73,28,'marti','2027-04-13','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Trecerea de la alfabetul chirilic la alfabetul latin','[{"id": "u5:12", "fel": "lecție", "titlu": "Trecerea de la alfabetul chirilic la alfabetul latin", "titluOriginal": "Trecerea de la alfabetul chirilic la alfabetul latin", "sursa": "manual, pp. 154–155", "lectia": 12, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["3.1", "3.3"]}]'::jsonb),
  ('9B','2026-2027',74,28,'marti','2027-04-13','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Ion Ghica: „Scrisoarea XIV. Tunsu și Jianu”','[{"id": "u5:13", "fel": "lecție", "titlu": "Ion Ghica: „Scrisoarea XIV. Tunsu și Jianu”", "titluOriginal": "Ion Ghica: „Scrisoarea XIV. Tunsu și Jianu”", "sursa": "manual, pp. 156–157", "lectia": 13, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',75,28,'joi','2027-04-15','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Memorialistica: mărturie, amintire, legendă','[{"id": "u5:14", "fel": "lecție", "titlu": "Memorialistica: mărturie, amintire, legendă", "titluOriginal": "Memorialistica: mărturie, amintire, legendă", "sursa": "manual, pp. 156–157", "lectia": 14, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',76,29,'marti','2027-04-20','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Extinderi: „Amintiri din Junimea” și „Jurnalul Annei Frank”','[{"id": "u5:15", "fel": "lecție", "titlu": "Extinderi: „Amintiri din Junimea” și „Jurnalul Annei Frank”", "titluOriginal": "Extinderi: „Amintiri din Junimea” și „Jurnalul Annei Frank”", "sursa": "manual, p. 158", "lectia": 15, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',77,29,'marti','2027-04-20','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Ioan Slavici și nuvela realistă psihologică','[{"id": "u5:16", "fel": "lecție", "titlu": "Ioan Slavici și nuvela realistă psihologică", "titluOriginal": "Ioan Slavici și nuvela realistă psihologică", "sursa": "manual, pp. 159–160", "lectia": 16, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',78,29,'joi','2027-04-22','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Lectura textului. Hanul, drumul, familia','[{"id": "u5:17", "fel": "lecție", "titlu": "Lectura textului. Hanul, drumul, familia", "titluOriginal": "Lectura textului. Hanul, drumul, familia", "sursa": "manual, pp. 160–163", "lectia": 17, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',79,30,'joi','2027-05-06','13:10','bloc propriu','Unitatea 5. Maturizarea formelor culturale și literare','Recapitulare','[{"id": "m:10", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('9B','2026-2027',80,31,'marti','2027-05-11','15:40','bloc propriu','Unitatea 5. Maturizarea formelor culturale și literare','Teză','[{"id": "m:11", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('9B','2026-2027',81,31,'marti','2027-05-11','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Aparență și esență: ce se vede și ce se ascunde - Atelier de comunicare orală: cooperare și negociere','[{"id": "u5:18", "fel": "lecție", "titlu": "Aparență și esență: ce se vede și ce se ascunde", "titluOriginal": "Aparență și esență: ce se vede și ce se ascunde", "sursa": "manual, pp. 163–165", "lectia": 18, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3"]}, {"id": "u5:19", "fel": "lecție", "titlu": "Atelier de comunicare orală: cooperare și negociere", "titluOriginal": "Atelier de comunicare orală: cooperare și negociere", "sursa": "manual, p. 166", "lectia": 19, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.3", "3.3"]}]'::jsonb),
  ('9B','2026-2027',82,31,'joi','2027-05-13','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Ironia, ezitarea și tăcerea ca strategii de comunicare - Construcția personajului realist: Ghiță','[{"id": "u5:20", "fel": "lecție", "titlu": "Ironia, ezitarea și tăcerea ca strategii de comunicare", "titluOriginal": "Ironia, ezitarea și tăcerea ca strategii de comunicare", "sursa": "manual, p. 166", "lectia": 20, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.2", "1.3", "3.3"]}, {"id": "u5:21", "fel": "lecție", "titlu": "Construcția personajului realist: Ghiță", "titluOriginal": "Construcția personajului realist: Ghiță", "sursa": "manual, pp. 167–168", "lectia": 21, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3"]}]'::jsonb),
  ('9B','2026-2027',83,32,'marti','2027-05-18','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Atelier de limbă română: dialogul formal și informal','[{"id": "u5:22", "fel": "lecție", "titlu": "Atelier de limbă română: dialogul formal și informal", "titluOriginal": "Atelier de limbă română: dialogul formal și informal", "sursa": "manual, p. 169", "lectia": 22, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["3.2", "3.3"]}]'::jsonb),
  ('9B','2026-2027',84,32,'marti','2027-05-18','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Extinderi: Crișan, Surikov, Tolstoi','[{"id": "u5:23", "fel": "lecție", "titlu": "Extinderi: Crișan, Surikov, Tolstoi", "titluOriginal": "Extinderi: Crișan, Surikov, Tolstoi", "sursa": "manual, p. 170", "lectia": 23, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',85,32,'joi','2027-05-20','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','I. L. Caragiale și comedia de moravuri','[{"id": "u5:24", "fel": "lecție", "titlu": "I. L. Caragiale și comedia de moravuri", "titluOriginal": "I. L. Caragiale și comedia de moravuri", "sursa": "manual, pp. 171–172", "lectia": 24, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('9B','2026-2027',86,33,'marti','2027-05-25','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Universul politic ca teatru al aparențelor','[{"id": "u5:25", "fel": "lecție", "titlu": "Universul politic ca teatru al aparențelor", "titluOriginal": "Universul politic ca teatru al aparențelor", "sursa": "manual, pp. 172–174", "lectia": 25, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3", "2.1"]}]'::jsonb),
  ('9B','2026-2027',87,33,'marti','2027-05-25','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Mecanismele comicului: situație și caracter - Mecanismele comicului: limbaj și nume','[{"id": "u5:26", "fel": "lecție", "titlu": "Mecanismele comicului: situație și caracter", "titluOriginal": "Mecanismele comicului: situație și caracter", "sursa": "manual, pp. 174–175", "lectia": 26, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.3", "2.1"]}, {"id": "u5:27", "fel": "lecție", "titlu": "Mecanismele comicului: limbaj și nume", "titluOriginal": "Mecanismele comicului: limbaj și nume", "sursa": "manual, pp. 175–176", "lectia": 27, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.2", "1.3", "3.3"]}]'::jsonb),
  ('9B','2026-2027',88,33,'joi','2027-05-27','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Atelier de limbă română: normă și abatere. Instrumente normative','[{"id": "u5:28", "fel": "lecție", "titlu": "Atelier de limbă română: normă și abatere. Instrumente normative", "titluOriginal": "Atelier de limbă română: normă și abatere. Instrumente normative", "sursa": "manual, p. 177", "lectia": 28, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["3.1", "3.3"]}]'::jsonb),
  ('9B','2026-2027',89,34,'joi','2027-06-03','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Text dramatic și spectacol','[{"id": "u5:29", "fel": "lecție", "titlu": "Text dramatic și spectacol", "titluOriginal": "Text dramatic și spectacol", "sursa": "manual, pp. 178–179", "lectia": 29, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.1", "3.3"]}]'::jsonb),
  ('9B','2026-2027',90,35,'marti','2027-06-08','15:40','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Extinderi: „Alegoria comediei” de Van Loo și „Tartuffe” de Molière','[{"id": "u5:30", "fel": "lecție", "titlu": "Extinderi: „Alegoria comediei” de Van Loo și „Tartuffe” de Molière", "titluOriginal": "Extinderi: „Alegoria comediei” de Van Loo și „Tartuffe” de Molière", "sursa": "manual, p. 180", "lectia": 30, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.3", "2.2"]}]'::jsonb),
  ('9B','2026-2027',91,35,'marti','2027-06-08','17:25','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Proiect individual: „Oameni ai timpului lor”','[{"id": "u5:34", "fel": "lecție", "titlu": "Proiect individual: „Oameni ai timpului lor”", "titluOriginal": "Proiect individual: „Oameni ai timpului lor”", "sursa": "manual, pp. 184–186 · 3 ore", "lectia": 34, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["2.1", "3.3", "3.4"], "comentariu": "anunțarea proiectului"}]'::jsonb),
  ('9B','2026-2027',92,35,'joi','2027-06-10','13:10','lectie','Unitatea 5. Maturizarea formelor culturale și literare','Recapitulare','[{"id": "u5:31", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "manual, pp. 181–182", "lectia": 31, "unitate": "Unitatea 5. Maturizarea formelor culturale și literare", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "2.2"]}]'::jsonb),
  ('9B','2026-2027',93,36,'marti','2027-06-15','15:40','bloc propriu','Unitatea 5. Maturizarea formelor culturale și literare','Recapitulare','[{"id": "m:5", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('9B','2026-2027',94,36,'marti','2027-06-15','17:25','bloc propriu','Unitatea 5. Maturizarea formelor culturale și literare','Evaluare','[{"id": "m:6", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare", "comentariu": "evaluarea proiectului"}]'::jsonb),
  ('9B','2026-2027',95,36,'joi','2027-06-17','13:10','bloc propriu','Unitatea 5. Maturizarea formelor culturale și literare','Evaluare','[{"id": "m:7", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare", "comentariu": "evaluare sumativă"}]'::jsonb);

-- ---------- paza pe clasa asta ----------
do $$
declare n int; lipsa int;
begin
  select count(*) into n from public.school_plan where clasa = '9B' and an_scolar = '2026-2027';
  if n <> 95 then
    raise exception 'Clasa 9B are % ore, așteptam 95. Lipirea s-a rupt.', n;
  end if;
  select count(*) into lipsa from generate_series(1, 95) g
   where not exists (select 1 from public.school_plan p
                      where p.clasa = '9B' and p.an_scolar = '2026-2027' and p.nr = g);
  if lipsa > 0 then
    raise exception 'Clasei 9B îi lipsesc % numere din șirul 1..95.', lipsa;
  end if;
  raise notice 'Clasa 9B: 95 de ore, la locul lor.';
end $$;
