-- =========================================================
-- 0097b · LICEU: planificarea clasei 10D, pe orarul din 21 septembrie
--
-- Una din cinci. Se rulează în ordine: 0097a, 0097b, 0097c, 0097d, 0097e.
-- Ultima ține paza pe toate cinci deodată.
--
-- DE CE CINCI FIȘIERE, NU UNUL. Întregul făcea 297 KB, iar SQL Editor îl
-- refuză: „request entity too large". Pe clasă iese vreo 53 KB și intră.
--
-- Punctul de pornire e `Diverse/ORAR 21 SEPT/Planificatoare/`, exportul din
-- planificatorul lui Marius. El e adevărul; documentele Word se nasc din el.
--
-- CE SE SCHIMBĂ, la toate cinci (comparat amprentă cu amprentă, nu din ochi):
--   · 9B și 11D — neschimbate. Intră totuși, ca regula să n-aibă excepții de
--     ținut minte, iar ce iese e la fel cu ce era.
--   · 11C și 11D — își mută ora de vineri, de pe 21 sept. încolo (11C de la
--     11:25 la 10:35, 11D de la 10:35 la 11:25).
--   · 10D — recapitularea inițială scade de la 4 ore la 3, „Unitatea 1. Basmul
--     cult" începe la ora 4 în loc de 5, iar cele două lecții care stăteau
--     împreună la ora 6 se despart în orele 5 și 6.
--   · 11B — se schimbă unitățile 2 și 3 (orele 21–56). Primele 20 rămân.
--   · 11C — plan nou din temelii: are acum exact planul lui 11D.
--
-- 12C ȘI 12D NU SE ATING: ele merg pe planificarea de bacalaureat (0093).
--
-- ZIUA SE SCRIE FĂRĂ DIACRITICE („marti"), ca în orar: îmbinarea dintre
-- planificare și orar se face pe ea, iar o literă deosebită ar fi rupt-o în
-- tăcere.
--
-- `blocuri` SE ȚINE CIUNTIT: rămân numele, sursa, unitatea și competențele; se
-- lasă afară `notiuni`, `activitati` și `ideeaDeRetinut` — materialul de predare,
-- nouă zecimi din greutate, pe care modulul nu-l citește nicăieri. El rămâne
-- întreg în JSON-urile din `Diverse/ORAR 21 SEPT/`.
--
-- SE ȘTERGE ȘI SE SCRIE LA LOC. Un `update` rând cu rând ar fi lăsat în urmă
-- orele care nu mai există, iar cheia unică (clasă, an, dată, ceas) s-ar fi
-- lovit de ele la 11C și 11D, unde ceasul se mută.
-- =========================================================

delete from public.school_plan where clasa = '10D' and an_scolar = '2026-2027';

insert into public.school_plan
  (clasa, an_scolar, nr, saptamana, zi, data, ora, fel, unitatea, titlu, blocuri) values
  ('10D','2026-2027',1,1,'marti','2026-09-08','17:25','bloc propriu',null,'Recapitulare','[{"id": "m:5", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',2,1,'marti','2026-09-08','18:15','bloc propriu',null,'Recapitulare','[{"id": "m:6", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',3,1,'joi','2026-09-10','14:50','bloc propriu',null,'Recapitulare','[{"id": "m:7", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',4,2,'marti','2026-09-15','16:35','lectie','Unitatea 1. Basmul cult','Modelul moștenit: basmul popular - Saltul: basmul devine literatură cultă','[{"id": "u1:1", "fel": "lecție", "titlu": "Modelul moștenit: basmul popular", "titluOriginal": "Modelul moștenit: basmul popular", "sursa": "Badea, Proza, pp. 20–21", "lectia": 1, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}, {"id": "u1:2", "fel": "lecție", "titlu": "Saltul: basmul devine literatură cultă", "titluOriginal": "Saltul: basmul devine literatură cultă", "sursa": "Crăciun, pp. 292–293", "lectia": 2, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',5,2,'marti','2026-09-15','18:15','lectie','Unitatea 1. Basmul cult','Lectura textului. Reconstituirea poveștii','[{"id": "u1:3", "fel": "lecție", "titlu": "Lectura textului. Reconstituirea poveștii", "titluOriginal": "Lectura textului. Reconstituirea poveștii", "sursa": "Pamfil – etapa înțelegerii", "lectia": 3, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',6,2,'joi','2026-09-17','14:00','lectie','Unitatea 1. Basmul cult','Registre stilistice și limbaj','[{"id": "u1:12", "fel": "lecție", "titlu": "Registre stilistice și limbaj", "titluOriginal": "Registre stilistice și limbaj", "sursa": "Crăciun, p. 296; Vianu, Arta prozatorilor", "lectia": 12, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["1.1", "2.1"]}]'::jsonb),
  ('10D','2026-2027',7,3,'marti','2026-09-22','16:35','lectie','Unitatea 1. Basmul cult','Tema. Titlul și numele eroului - Primul episod: coborârea în fântână - Al doilea episod: probele puse de Spân - Al treilea episod: demascarea Spânului','[{"id": "u1:4", "fel": "lecție", "titlu": "Tema. Titlul și numele eroului", "titluOriginal": "Tema. Titlul și numele eroului", "sursa": "Eseul, pp. 73–74", "lectia": 4, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u1:5", "fel": "lecție", "titlu": "Primul episod: coborârea în fântână", "titluOriginal": "Primul episod: coborârea în fântână", "sursa": "Eseul, pp. 74–75; Crăciun, p. 295", "lectia": 5, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u1:6", "fel": "lecție", "titlu": "Al doilea episod: probele puse de Spân", "titluOriginal": "Al doilea episod: probele puse de Spân", "sursa": "Crăciun, pp. 295–297; Eseul, p. 75", "lectia": 6, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u1:7", "fel": "lecție", "titlu": "Al treilea episod: demascarea Spânului", "titluOriginal": "Al treilea episod: demascarea Spânului", "sursa": "Eseul, p. 75", "lectia": 7, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1", "3.3"]}]'::jsonb),
  ('10D','2026-2027',8,3,'marti','2026-09-22','18:15','lectie','Unitatea 1. Basmul cult','Momentele subiectului. Incipit și final - Tehnici narative. Triplicarea supralicitată - Instanțele comunicării. Perspectiva narativă','[{"id": "u1:8", "fel": "lecție", "titlu": "Momentele subiectului. Incipit și final", "titluOriginal": "Momentele subiectului. Incipit și final", "sursa": "programă 2.1; Eseul, p. 73", "lectia": 8, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}, {"id": "u1:9", "fel": "lecție", "titlu": "Tehnici narative. Triplicarea supralicitată", "titluOriginal": "Tehnici narative. Triplicarea supralicitată", "sursa": "Eseul, p. 75; Crăciun, p. 295", "lectia": 9, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}, {"id": "u1:10", "fel": "lecție", "titlu": "Instanțele comunicării. Perspectiva narativă", "titluOriginal": "Instanțele comunicării. Perspectiva narativă", "sursa": "programă 2.1; Crăciun, pp. 297–298", "lectia": 10, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',9,3,'joi','2026-09-24','14:00','lectie','Unitatea 1. Basmul cult','Personajele: funcții, tipuri, caracterizare - Umanizarea fantasticului. Viziunea despre lume - Același basm, citit altfel: lecturile critice','[{"id": "u1:11", "fel": "lecție", "titlu": "Personajele: funcții, tipuri, caracterizare", "titluOriginal": "Personajele: funcții, tipuri, caracterizare", "sursa": "Crăciun, pp. 294–296; programă 2.1", "lectia": 11, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.1"]}, {"id": "u1:13", "fel": "lecție", "titlu": "Umanizarea fantasticului. Viziunea despre lume", "titluOriginal": "Umanizarea fantasticului. Viziunea despre lume", "sursa": "Crăciun, p. 293; Badea, p. 215", "lectia": 13, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["2.4"]}, {"id": "u1:14", "fel": "lecție", "titlu": "Același basm, citit altfel: lecturile critice", "titluOriginal": "Același basm, citit altfel: lecturile critice", "sursa": "Crăciun, pp. 294–296", "lectia": 14, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["3.2", "3.3"]}]'::jsonb),
  ('10D','2026-2027',10,4,'marti','2026-09-29','16:35','lectie','Unitatea 1. Basmul cult','Nonverbalul și paraverbalul în mesajul oral - Structura dialogului: reguli și tehnici - Argumentarea interpretărilor și a judecăților de valoare','[{"id": "u1:15", "fel": "lecție", "titlu": "Nonverbalul și paraverbalul în mesajul oral", "titluOriginal": "Nonverbalul și paraverbalul în mesajul oral", "sursa": "manual, p. 24", "lectia": 15, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["1.3"]}, {"id": "u1:16", "fel": "lecție", "titlu": "Structura dialogului: reguli și tehnici", "titluOriginal": "Structura dialogului: reguli și tehnici", "sursa": "manual, p. 25", "lectia": 16, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["1.3"]}, {"id": "u1:17", "fel": "lecție", "titlu": "Argumentarea interpretărilor și a judecăților de valoare", "titluOriginal": "Argumentarea interpretărilor și a judecăților de valoare", "sursa": "manual, p. 26", "lectia": 17, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2", "3.3"]}]'::jsonb),
  ('10D','2026-2027',11,4,'marti','2026-09-29','18:15','lectie','Unitatea 1. Basmul cult','Eseul structurat: cele patru repere - Recapitulare','[{"id": "u1:18", "fel": "lecție", "titlu": "Eseul structurat: cele patru repere", "titluOriginal": "Eseul structurat: cele patru repere", "sursa": "Eseul, pp. 73–79", "lectia": 18, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["1.4", "2.4", "3.3"]}, {"id": "u1:19", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "programă – competențele unității", "lectia": 19, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["1.4", "2.1", "2.4"], "comentariu": "nu se face și recapitulare și evaluare în aceeași oră"}]'::jsonb),
  ('10D','2026-2027',12,4,'joi','2026-10-01','14:00','lectie','Unitatea 1. Basmul cult','Evaluare','[{"id": "u1:20", "fel": "lecție", "titlu": "Evaluare", "titluOriginal": "Evaluare", "sursa": "programă – competențele unității", "lectia": 20, "unitate": "Unitatea 1. Basmul cult", "unitateId": "p1", "competenteSpecifice": ["1.4", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',13,5,'marti','2026-10-06','16:35','lectie','Unitatea 2. Nuvela','Nuvela ca specie - Slavici, moralistul. Contextul','[{"id": "u2:1", "fel": "lecție", "titlu": "Nuvela ca specie", "titluOriginal": "Nuvela ca specie", "sursa": "Badea, Proza; programă 2.1", "lectia": 1, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1"]}, {"id": "u2:2", "fel": "lecție", "titlu": "Slavici, moralistul. Contextul", "titluOriginal": "Slavici, moralistul. Contextul", "sursa": "Crăciun, pp. 330–332", "lectia": 2, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',14,5,'marti','2026-10-06','18:15','lectie','Unitatea 2. Nuvela','Lectura textului. Traseul degradării - Tema. Titlul și hanul','[{"id": "u2:3", "fel": "lecție", "titlu": "Lectura textului. Traseul degradării", "titluOriginal": "Lectura textului. Traseul degradării", "sursa": "Pamfil – etapa înțelegerii", "lectia": 3, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1"]}, {"id": "u2:4", "fel": "lecție", "titlu": "Tema. Titlul și hanul", "titluOriginal": "Tema. Titlul și hanul", "sursa": "Crăciun, pp. 332–333", "lectia": 4, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',15,5,'joi','2026-10-08','14:00','lectie','Unitatea 2. Nuvela','Scena I: sosirea lui Lică la han - Scena a II-a: Ghiță pleacă de la han - Scena a III-a: noaptea de Paști','[{"id": "u2:5", "fel": "lecție", "titlu": "Scena I: sosirea lui Lică la han", "titluOriginal": "Scena I: sosirea lui Lică la han", "sursa": "Crăciun, p. 333", "lectia": 5, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u2:6", "fel": "lecție", "titlu": "Scena a II-a: Ghiță pleacă de la han", "titluOriginal": "Scena a II-a: Ghiță pleacă de la han", "sursa": "Crăciun, pp. 333–334", "lectia": 6, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1", "3.3"]}, {"id": "u2:7", "fel": "lecție", "titlu": "Scena a III-a: noaptea de Paști", "titluOriginal": "Scena a III-a: noaptea de Paști", "sursa": "Crăciun, p. 334", "lectia": 7, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',16,7,'marti','2026-10-20','16:35','lectie','Unitatea 2. Nuvela','Construcția subiectului. Incipit și final - Perspectiva narativă și analiza psihologică - Personajele: Ghiță, Lică, Ana','[{"id": "u2:8", "fel": "lecție", "titlu": "Construcția subiectului. Incipit și final", "titluOriginal": "Construcția subiectului. Incipit și final", "sursa": "programă 2.1", "lectia": 8, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1"]}, {"id": "u2:9", "fel": "lecție", "titlu": "Perspectiva narativă și analiza psihologică", "titluOriginal": "Perspectiva narativă și analiza psihologică", "sursa": "Crăciun, pp. 334–335", "lectia": 9, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1"]}, {"id": "u2:10", "fel": "lecție", "titlu": "Personajele: Ghiță, Lică, Ana", "titluOriginal": "Personajele: Ghiță, Lică, Ana", "sursa": "Crăciun, pp. 333–334", "lectia": 10, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',17,7,'marti','2026-10-20','18:15','lectie','Unitatea 2. Nuvela','Realism psihologic și tragic clasic - Banul. Moralismul lui Slavici - Stilul direct, indirect, indirect liber','[{"id": "u2:11", "fel": "lecție", "titlu": "Realism psihologic și tragic clasic", "titluOriginal": "Realism psihologic și tragic clasic", "sursa": "Crăciun, pp. 332, 335", "lectia": 11, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["2.4"]}, {"id": "u2:12", "fel": "lecție", "titlu": "Banul. Moralismul lui Slavici", "titluOriginal": "Banul. Moralismul lui Slavici", "sursa": "Crăciun, pp. 332–333", "lectia": 12, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["3.1", "3.2", "3.3"]}, {"id": "u2:13", "fel": "lecție", "titlu": "Stilul direct, indirect, indirect liber", "titluOriginal": "Stilul direct, indirect, indirect liber", "sursa": "manual, p. 58", "lectia": 13, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1"]}]'::jsonb),
  ('10D','2026-2027',18,7,'joi','2026-10-22','14:00','lectie','Unitatea 2. Nuvela','Caracterizarea personajului - Monologul','[{"id": "u2:14", "fel": "lecție", "titlu": "Caracterizarea personajului", "titluOriginal": "Caracterizarea personajului", "sursa": "manual, p. 59", "lectia": 14, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.4", "2.1"]}, {"id": "u2:16", "fel": "lecție", "titlu": "Monologul", "titluOriginal": "Monologul", "sursa": "manual, p. 61", "lectia": 16, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.3"]}]'::jsonb),
  ('10D','2026-2027',19,8,'marti','2026-11-03','16:35','lectie','Unitatea 2. Nuvela','Eseul structurat - Cele două eseuri pe „Moara cu noroc”','[{"id": "u2:15", "fel": "lecție", "titlu": "Eseul structurat", "titluOriginal": "Eseul structurat", "sursa": "manual, p. 60; Eseul, p. 40", "lectia": 15, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.4", "3.3"]}, {"id": "u2:17", "fel": "lecție", "titlu": "Cele două eseuri pe „Moara cu noroc”", "titluOriginal": "Cele două eseuri pe „Moara cu noroc”", "sursa": "Eseul, pp. 40–52", "lectia": 17, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.4", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',20,8,'marti','2026-11-03','18:15','lectie','Unitatea 2. Nuvela','Recapitulare','[{"id": "u2:18", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "programă – competențele unității", "lectia": 18, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.4", "2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',21,8,'joi','2026-11-05','14:00','bloc propriu','Unitatea 2. Nuvela','Recapitulare','[{"id": "m:8", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',22,9,'marti','2026-11-10','16:35','lectie','Unitatea 2. Nuvela','Evaluare','[{"id": "u2:19", "fel": "lecție", "titlu": "Evaluare", "titluOriginal": "Evaluare", "sursa": "programă – competențele unității", "lectia": 19, "unitate": "Unitatea 2. Nuvela", "unitateId": "p2", "competenteSpecifice": ["1.4", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',23,9,'marti','2026-11-10','18:15','lectie','Unitatea 3. Romanul','Romanul ca specie - Filimon și începutul romanului românesc','[{"id": "u3:1", "fel": "lecție", "titlu": "Romanul ca specie", "titluOriginal": "Romanul ca specie", "sursa": "programă 2.1; Badea, Proza", "lectia": 1, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u3:2", "fel": "lecție", "titlu": "Filimon și începutul romanului românesc", "titluOriginal": "Filimon și începutul romanului românesc", "sursa": "Crăciun, pp. 157–159", "lectia": 2, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',24,9,'joi','2026-11-12','14:00','lectie','Unitatea 3. Romanul','Lectura. Cele două serii de personaje - Tema parvenirii','[{"id": "u3:3", "fel": "lecție", "titlu": "Lectura. Cele două serii de personaje", "titluOriginal": "Lectura. Cele două serii de personaje", "sursa": "Crăciun, pp. 159–160", "lectia": 3, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u3:4", "fel": "lecție", "titlu": "Tema parvenirii", "titluOriginal": "Tema parvenirii", "sursa": "Crăciun, p. 159", "lectia": 4, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',25,10,'marti','2026-11-17','16:35','lectie','Unitatea 3. Romanul','Scena I: Păturică în scara casei boierești - Scena a II-a: ruinarea binefăcătorului - Scena a III-a: jalba-n proțap și ocna','[{"id": "u3:5", "fel": "lecție", "titlu": "Scena I: Păturică în scara casei boierești", "titluOriginal": "Scena I: Păturică în scara casei boierești", "sursa": "Crăciun, pp. 160–161", "lectia": 5, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u3:6", "fel": "lecție", "titlu": "Scena a II-a: ruinarea binefăcătorului", "titluOriginal": "Scena a II-a: ruinarea binefăcătorului", "sursa": "Crăciun, pp. 159–160", "lectia": 6, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u3:7", "fel": "lecție", "titlu": "Scena a III-a: jalba-n proțap și ocna", "titluOriginal": "Scena a III-a: jalba-n proțap și ocna", "sursa": "Crăciun, p. 160", "lectia": 7, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.3"]}]'::jsonb),
  ('10D','2026-2027',26,10,'marti','2026-11-17','18:15','lectie','Unitatea 3. Romanul','Construcția. Planurile și documentul - Parabolă sau realism? - Evaluarea discursului oral','[{"id": "u3:8", "fel": "lecție", "titlu": "Construcția. Planurile și documentul", "titluOriginal": "Construcția. Planurile și documentul", "sursa": "Crăciun, pp. 158–159", "lectia": 8, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u3:10", "fel": "lecție", "titlu": "Parabolă sau realism?", "titluOriginal": "Parabolă sau realism?", "sursa": "Crăciun, pp. 158, 160", "lectia": 10, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "3.3"]}, {"id": "u3:11", "fel": "lecție", "titlu": "Evaluarea discursului oral", "titluOriginal": "Evaluarea discursului oral", "sursa": "manual, p. 82", "lectia": 11, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.3"]}]'::jsonb),
  ('10D','2026-2027',27,10,'joi','2026-11-19','14:00','lectie','Unitatea 3. Romanul','Personajele. Dinu Păturică','[{"id": "u3:9", "fel": "lecție", "titlu": "Personajele. Dinu Păturică", "titluOriginal": "Personajele. Dinu Păturică", "sursa": "Crăciun, pp. 159–161", "lectia": 9, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',28,11,'marti','2026-11-24','16:35','lectie','Unitatea 3. Romanul','Contextul: de la sămănătorism la realism dur - Geneza. Cele trei întâmplări reale','[{"id": "u4:1", "fel": "lecție", "titlu": "Contextul: de la sămănătorism la realism dur", "titluOriginal": "Contextul: de la sămănătorism la realism dur", "sursa": "Crăciun, pp. 581–582", "lectia": 1, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u4:2", "fel": "lecție", "titlu": "Geneza. Cele trei întâmplări reale", "titluOriginal": "Geneza. Cele trei întâmplări reale", "sursa": "Crăciun, pp. 582–583", "lectia": 2, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',29,11,'marti','2026-11-24','18:15','lectie','Unitatea 3. Romanul','Lectura. Cele două planuri - Tema. Pământul ca destin','[{"id": "u4:3", "fel": "lecție", "titlu": "Lectura. Cele două planuri", "titluOriginal": "Lectura. Cele două planuri", "sursa": "Crăciun, pp. 583–584", "lectia": 3, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u4:4", "fel": "lecție", "titlu": "Tema. Pământul ca destin", "titluOriginal": "Tema. Pământul ca destin", "sursa": "Crăciun, pp. 583, 584", "lectia": 4, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',30,11,'joi','2026-11-26','14:00','lectie','Unitatea 3. Romanul','Scena I: hora din incipit - Scena a II-a: sărutarea pământului - Scena a III-a: finalul. Drumul care se închide','[{"id": "u4:5", "fel": "lecție", "titlu": "Scena I: hora din incipit", "titluOriginal": "Scena I: hora din incipit", "sursa": "Crăciun, p. 583", "lectia": 5, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u4:6", "fel": "lecție", "titlu": "Scena a II-a: sărutarea pământului", "titluOriginal": "Scena a II-a: sărutarea pământului", "sursa": "Crăciun, pp. 582, 584", "lectia": 6, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u4:7", "fel": "lecție", "titlu": "Scena a III-a: finalul. Drumul care se închide", "titluOriginal": "Scena a III-a: finalul. Drumul care se închide", "sursa": "Crăciun, pp. 583–584", "lectia": 7, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',31,12,'joi','2026-12-03','14:00','lectie','Unitatea 3. Romanul','Compoziția circulară. Simetria - Perspectiva narativă. Obiectivitatea - Personajele. Ion, Ana, Florica, Vasile Baciu','[{"id": "u4:8", "fel": "lecție", "titlu": "Compoziția circulară. Simetria", "titluOriginal": "Compoziția circulară. Simetria", "sursa": "Crăciun, p. 583", "lectia": 8, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u4:9", "fel": "lecție", "titlu": "Perspectiva narativă. Obiectivitatea", "titluOriginal": "Perspectiva narativă. Obiectivitatea", "sursa": "programă 2.1; Crăciun", "lectia": 9, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u4:10", "fel": "lecție", "titlu": "Personajele. Ion, Ana, Florica, Vasile Baciu", "titluOriginal": "Personajele. Ion, Ana, Florica, Vasile Baciu", "sursa": "Crăciun, p. 584", "lectia": 10, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',32,13,'marti','2026-12-08','16:35','bloc propriu','Unitatea 3. Romanul','Recapitulare','[{"id": "m:24", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',33,13,'marti','2026-12-08','18:15','bloc propriu','Unitatea 3. Romanul','Recapitulare','[{"id": "m:25", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',34,13,'joi','2026-12-10','14:00','bloc propriu','Unitatea 3. Romanul','Teză','[{"id": "m:23", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('10D','2026-2027',35,14,'marti','2026-12-15','16:35','lectie','Unitatea 3. Romanul','Realismul dur și critica socială - Dialogul - Dezbaterea - Cele două eseuri pe „Ion”','[{"id": "u4:11", "fel": "lecție", "titlu": "Realismul dur și critica socială", "titluOriginal": "Realismul dur și critica socială", "sursa": "Crăciun, pp. 581–584", "lectia": 11, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "3.3"]}, {"id": "u4:12", "fel": "lecție", "titlu": "Dialogul", "titluOriginal": "Dialogul", "sursa": "manual, p. 93", "lectia": 12, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.3"]}, {"id": "u4:13", "fel": "lecție", "titlu": "Dezbaterea", "titluOriginal": "Dezbaterea", "sursa": "manual, p. 95", "lectia": 13, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.3", "3.1", "3.2"]}, {"id": "u4:14", "fel": "lecție", "titlu": "Cele două eseuri pe „Ion”", "titluOriginal": "Cele două eseuri pe „Ion”", "sursa": "Eseul – romanul realist obiectiv", "lectia": 14, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.4", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',36,14,'marti','2026-12-15','18:15','lectie','Unitatea 3. Romanul','Recapitulare','[{"id": "u4:15", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "programă – competențele unității", "lectia": 15, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.4", "2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',37,14,'joi','2026-12-17','14:00','lectie','Unitatea 3. Romanul','Evaluare','[{"id": "u4:16", "fel": "lecție", "titlu": "Evaluare", "titluOriginal": "Evaluare", "sursa": "programă – competențele unității", "lectia": 16, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.4", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',38,15,'marti','2026-12-22','16:35','bloc propriu','Unitatea 3. Romanul','Recapitulare','[{"id": "m:10", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',39,15,'marti','2026-12-22','18:15','bloc propriu','Unitatea 3. Romanul','Recapitulare','[{"id": "m:11", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',40,16,'marti','2027-01-12','16:35','lectie','Unitatea 3. Romanul','Romanul subiectiv. Autenticitatea - Eliade și ciclul indian','[{"id": "u5:1", "fel": "lecție", "titlu": "Romanul subiectiv. Autenticitatea", "titluOriginal": "Romanul subiectiv. Autenticitatea", "sursa": "Crăciun, pp. 612–613", "lectia": 1, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u5:2", "fel": "lecție", "titlu": "Eliade și ciclul indian", "titluOriginal": "Eliade și ciclul indian", "sursa": "Crăciun, pp. 612–613", "lectia": 2, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',41,16,'marti','2027-01-12','18:15','lectie','Unitatea 3. Romanul','Lectura. Povestea și jurnalul - Tema. Iubirea ca experiență a cunoașterii','[{"id": "u5:3", "fel": "lecție", "titlu": "Lectura. Povestea și jurnalul", "titluOriginal": "Lectura. Povestea și jurnalul", "sursa": "Pamfil – etapa înțelegerii", "lectia": 3, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u5:4", "fel": "lecție", "titlu": "Tema. Iubirea ca experiență a cunoașterii", "titluOriginal": "Tema. Iubirea ca experiență a cunoașterii", "sursa": "Crăciun, pp. 613–615", "lectia": 4, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',42,16,'joi','2027-01-14','14:00','lectie','Unitatea 3. Romanul','Scena I: prima vedere a Maitreyiei - Scena a II-a: logodna sub cerul înstelat - Scena a III-a: despărțirea','[{"id": "u5:5", "fel": "lecție", "titlu": "Scena I: prima vedere a Maitreyiei", "titluOriginal": "Scena I: prima vedere a Maitreyiei", "sursa": "Crăciun, p. 613", "lectia": 5, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u5:6", "fel": "lecție", "titlu": "Scena a II-a: logodna sub cerul înstelat", "titluOriginal": "Scena a II-a: logodna sub cerul înstelat", "sursa": "Crăciun, pp. 614–615", "lectia": 6, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u5:7", "fel": "lecție", "titlu": "Scena a III-a: despărțirea", "titluOriginal": "Scena a III-a: despărțirea", "sursa": "Crăciun, p. 615", "lectia": 7, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',43,17,'marti','2027-01-19','16:35','lectie','Unitatea 3. Romanul','Perspectiva narativă. Naratorul-personaj - Personajele. Allan, Maitreyi, Narendra Sen - Scrierea și pronunțarea numelor proprii','[{"id": "u5:8", "fel": "lecție", "titlu": "Perspectiva narativă. Naratorul-personaj", "titluOriginal": "Perspectiva narativă. Naratorul-personaj", "sursa": "Crăciun, pp. 612–613", "lectia": 8, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u5:9", "fel": "lecție", "titlu": "Personajele. Allan, Maitreyi, Narendra Sen", "titluOriginal": "Personajele. Allan, Maitreyi, Narendra Sen", "sursa": "Crăciun, pp. 613–615", "lectia": 9, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["2.1"]}, {"id": "u5:11", "fel": "lecție", "titlu": "Scrierea și pronunțarea numelor proprii", "titluOriginal": "Scrierea și pronunțarea numelor proprii", "sursa": "manual, p. 107", "lectia": 11, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.5"]}]'::jsonb),
  ('10D','2026-2027',44,17,'marti','2027-01-19','18:15','lectie','Unitatea 3. Romanul','Două civilizații. Exotism sau întâlnire?','[{"id": "u5:10", "fel": "lecție", "titlu": "Două civilizații. Exotism sau întâlnire?", "titluOriginal": "Două civilizații. Exotism sau întâlnire?", "sursa": "Crăciun, pp. 613–615", "lectia": 10, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "3.3"]}]'::jsonb),
  ('10D','2026-2027',45,17,'joi','2027-01-21','14:00','lectie','Unitatea 3. Romanul','Recapitulare','[{"id": "u5:13", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "programă – competențele unității", "lectia": 13, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.4", "2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',46,18,'marti','2027-01-26','16:35','lectie','Unitatea 3. Romanul','Evaluare','[{"id": "u5:14", "fel": "lecție", "titlu": "Evaluare", "titluOriginal": "Evaluare", "sursa": "programă – competențele unității", "lectia": 14, "unitate": "Unitatea 3. Romanul", "unitateId": "p3", "competenteSpecifice": ["1.4", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',47,18,'marti','2027-01-26','18:15','lectie','Unitatea 4. Evoluția prozei','Recenzia ca specie a criticii','[{"id": "u6:1", "fel": "lecție", "titlu": "Recenzia ca specie a criticii", "titluOriginal": "Recenzia ca specie a criticii", "sursa": "programă 3.2; manual, p. 108", "lectia": 1, "unitate": "Unitatea 4. Recenzia", "unitateId": "p4", "competenteSpecifice": ["3.2"]}]'::jsonb),
  ('10D','2026-2027',48,18,'joi','2027-01-28','14:00','lectie','Unitatea 4. Evoluția prozei','Pompiliu Constantinescu, critic interbelic - Analiza recenziei','[{"id": "u6:2", "fel": "lecție", "titlu": "Pompiliu Constantinescu, critic interbelic", "titluOriginal": "Pompiliu Constantinescu, critic interbelic", "sursa": "manual, p. 108; Crăciun", "lectia": 2, "unitate": "Unitatea 4. Recenzia", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.2"]}, {"id": "u6:3", "fel": "lecție", "titlu": "Analiza recenziei", "titluOriginal": "Analiza recenziei", "sursa": "manual, p. 108", "lectia": 3, "unitate": "Unitatea 4. Recenzia", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.2"]}]'::jsonb),
  ('10D','2026-2027',49,19,'marti','2027-02-02','16:35','lectie','Unitatea 4. Evoluția prozei','Redactarea unei recenzii','[{"id": "u6:4", "fel": "lecție", "titlu": "Redactarea unei recenzii", "titluOriginal": "Redactarea unei recenzii", "sursa": "programă 1.4, 3.3", "lectia": 4, "unitate": "Unitatea 4. Recenzia", "unitateId": "p4", "competenteSpecifice": ["1.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',50,19,'marti','2027-02-02','18:15','lectie','Unitatea 4. Evoluția prozei','Linia timpului. De la basm la romanul modern - Instanțele narative, comparativ - Fișa comparativă a prozei','[{"id": "u7:1", "fel": "lecție", "titlu": "Linia timpului. De la basm la romanul modern", "titluOriginal": "Linia timpului. De la basm la romanul modern", "sursa": "manual, p. 114; Crăciun", "lectia": 1, "unitate": "Unitatea 4. Evoluția prozei", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u7:2", "fel": "lecție", "titlu": "Instanțele narative, comparativ", "titluOriginal": "Instanțele narative, comparativ", "sursa": "programă 2.1", "lectia": 2, "unitate": "Unitatea 4. Evoluția prozei", "unitateId": "p5", "competenteSpecifice": ["2.1"]}, {"id": "u7:3", "fel": "lecție", "titlu": "Fișa comparativă a prozei", "titluOriginal": "Fișa comparativă a prozei", "sursa": "sinteză", "lectia": 3, "unitate": "Unitatea 4. Evoluția prozei", "unitateId": "p5", "competenteSpecifice": ["1.4", "2.1", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',51,19,'joi','2027-02-04','14:00','lectie','Unitatea 5. Poezia epică','Poezia epică. Fabula - Grigore Alexandrescu, fabulistul','[{"id": "u8:1", "fel": "lecție", "titlu": "Poezia epică. Fabula", "titluOriginal": "Poezia epică. Fabula", "sursa": "Badea, Poezia, pp. 119–120", "lectia": 1, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1"]}, {"id": "u8:2", "fel": "lecție", "titlu": "Grigore Alexandrescu, fabulistul", "titluOriginal": "Grigore Alexandrescu, fabulistul", "sursa": "Badea, Poezia, pp. 125–126", "lectia": 2, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1"]}]'::jsonb),
  ('10D','2026-2027',52,20,'marti','2027-02-09','16:35','bloc propriu','Unitatea 5. Poezia epică','Lectură - Tema și titlul','[{"id": "m:12", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură"}, {"id": "u8:3", "fel": "lecție", "titlu": "Tema și titlul", "titluOriginal": "Tema și titlul", "sursa": "Badea, Poezia, p. 126", "lectia": 3, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.4"]}]'::jsonb),
  ('10D','2026-2027',53,20,'marti','2027-02-09','18:15','lectie','Unitatea 5. Poezia epică','Momentul I: morala din deschidere - Momentul al II-lea: rechizitoriul ogarului - Momentul al III-lea: sentința - Structura. Prozodie și alegorie','[{"id": "u8:4", "fel": "lecție", "titlu": "Momentul I: morala din deschidere", "titluOriginal": "Momentul I: morala din deschidere", "sursa": "Badea, Poezia, pp. 126–127", "lectia": 4, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1", "3.1"]}, {"id": "u8:5", "fel": "lecție", "titlu": "Momentul al II-lea: rechizitoriul ogarului", "titluOriginal": "Momentul al II-lea: rechizitoriul ogarului", "sursa": "Badea, Poezia, p. 127", "lectia": 5, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1", "3.1"]}, {"id": "u8:6", "fel": "lecție", "titlu": "Momentul al III-lea: sentința", "titluOriginal": "Momentul al III-lea: sentința", "sursa": "Badea, Poezia, pp. 127–128", "lectia": 6, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.4"]}, {"id": "u8:7", "fel": "lecție", "titlu": "Structura. Prozodie și alegorie", "titluOriginal": "Structura. Prozodie și alegorie", "sursa": "programă 2.1, 2.3", "lectia": 7, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3", "3.2"]}]'::jsonb),
  ('10D','2026-2027',54,20,'joi','2027-02-11','14:00','lectie','Unitatea 5. Poezia epică','Stilurile funcționale ale limbii române - Texte funcționale: CV-ul - Scrisoarea de intenție și e-mailul','[{"id": "u8:8", "fel": "lecție", "titlu": "Stilurile funcționale ale limbii române", "titluOriginal": "Stilurile funcționale ale limbii române", "sursa": "manual, p. 124", "lectia": 8, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["1.1"]}, {"id": "u8:9", "fel": "lecție", "titlu": "Texte funcționale: CV-ul", "titluOriginal": "Texte funcționale: CV-ul", "sursa": "manual, p. 125; programă 1.4", "lectia": 9, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["1.4"]}, {"id": "u8:10", "fel": "lecție", "titlu": "Scrisoarea de intenție și e-mailul", "titluOriginal": "Scrisoarea de intenție și e-mailul", "sursa": "manual, p. 125; programă 1.4", "lectia": 10, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["1.4"]}]'::jsonb),
  ('10D','2026-2027',55,21,'marti','2027-02-16','16:35','lectie','Unitatea 5. Poezia epică','Recapitulare','[{"id": "u8:11", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "programă – competențele unității", "lectia": 11, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["1.4", "2.1"]}]'::jsonb),
  ('10D','2026-2027',56,21,'marti','2027-02-16','18:15','lectie','Unitatea 5. Poezia epică','Evaluare','[{"id": "u8:12", "fel": "lecție", "titlu": "Evaluare", "titluOriginal": "Evaluare", "sursa": "programă – competențele unității", "lectia": 12, "unitate": "Unitatea 5. Poezia epică", "unitateId": "p6", "competenteSpecifice": ["1.4", "2.1"]}]'::jsonb),
  ('10D','2026-2027',57,21,'joi','2027-02-18','14:00','bloc propriu','Unitatea 5. Poezia epică','Recapitulare','[{"id": "m:2", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',58,22,'marti','2027-03-02','16:35','lectie','Unitatea 7. Poezia lirică','Poezia lirică. Eul liric','[{"id": "u9:1", "fel": "lecție", "titlu": "Poezia lirică. Eul liric", "titluOriginal": "Poezia lirică. Eul liric", "sursa": "programă 2.3; Badea, Poezia", "lectia": 1, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}]'::jsonb),
  ('10D','2026-2027',59,22,'marti','2027-03-02','18:15','lectie','Unitatea 7. Poezia lirică','Eminescu. Locul poeziilor de dragoste - Contextul și simbolul florii albastre','[{"id": "u9:2", "fel": "lecție", "titlu": "Eminescu. Locul poeziilor de dragoste", "titluOriginal": "Eminescu. Locul poeziilor de dragoste", "sursa": "Crăciun, p. 242; Badea, Poezia, p. 264", "lectia": 2, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}, {"id": "u9:3", "fel": "lecție", "titlu": "Contextul și simbolul florii albastre", "titluOriginal": "Contextul și simbolul florii albastre", "sursa": "Crăciun, p. 242", "lectia": 3, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3", "2.4"]}]'::jsonb),
  ('10D','2026-2027',60,22,'joi','2027-03-04','14:00','bloc propriu','Unitatea 7. Poezia lirică','Lectură - Tema și titlul - Antiteza el / ea. Cele două lumi - Compoziția și finalul','[{"id": "m:13", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură"}, {"id": "u9:6", "fel": "lecție", "titlu": "Tema și titlul", "titluOriginal": "Tema și titlul", "sursa": "Badea, Poezia, pp. 264–265", "lectia": 6, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}, {"id": "u9:4", "fel": "lecție", "titlu": "Antiteza el / ea. Cele două lumi", "titluOriginal": "Antiteza el / ea. Cele două lumi", "sursa": "Crăciun, pp. 242–243", "lectia": 4, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}, {"id": "u9:5", "fel": "lecție", "titlu": "Compoziția și finalul", "titluOriginal": "Compoziția și finalul", "sursa": "Crăciun, p. 243", "lectia": 5, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3", "2.4"]}]'::jsonb),
  ('10D','2026-2027',61,23,'marti','2027-03-09','16:35','lectie','Unitatea 7. Poezia lirică','Structura: climax și anticlimax - Figurile de stil','[{"id": "u9:7", "fel": "lecție", "titlu": "Structura: climax și anticlimax", "titluOriginal": "Structura: climax și anticlimax", "sursa": "Badea, Poezia, p. 265", "lectia": 7, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}, {"id": "u9:8", "fel": "lecție", "titlu": "Figurile de stil", "titluOriginal": "Figurile de stil", "sursa": "manual, p. 137; programă 2.3", "lectia": 8, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}]'::jsonb),
  ('10D','2026-2027',62,23,'marti','2027-03-09','18:15','lectie','Unitatea 7. Poezia lirică','Analiza. Comentariul - „Floare albastră” și „Pe lângă plopii fără soț”, în oglindă','[{"id": "u9:9", "fel": "lecție", "titlu": "Analiza. Comentariul", "titluOriginal": "Analiza. Comentariul", "sursa": "manual, p. 140; programă 1.4", "lectia": 9, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["1.4", "2.3"]}, {"id": "u9:10", "fel": "lecție", "titlu": "„Floare albastră” și „Pe lângă plopii fără soț”, în oglindă", "titluOriginal": "„Floare albastră” și „Pe lângă plopii fără soț”, în oglindă", "sursa": "sinteză", "lectia": 10, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["1.4", "2.3", "3.3"], "comentariu": "care cele două poezii? nu le-ai menționat"}]'::jsonb),
  ('10D','2026-2027',63,23,'joi','2027-03-11','14:00','lectie','Unitatea 7. Poezia lirică','Simbolismul. Trăsături','[{"id": "u11:1", "fel": "lecție", "titlu": "Simbolismul. Trăsături", "titluOriginal": "Simbolismul. Trăsături", "sursa": "Badea, Poezia, pp. 473–474", "lectia": 1, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}]'::jsonb),
  ('10D','2026-2027',64,24,'marti','2027-03-16','16:35','bloc propriu','Unitatea 7. Poezia lirică','Lectură - Titlul, refrenul, prozodia','[{"id": "m:14", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură"}, {"id": "u11:2", "fel": "lecție", "titlu": "Titlul, refrenul, prozodia", "titluOriginal": "Titlul, refrenul, prozodia", "sursa": "Badea, Poezia, p. 474", "lectia": 2, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}]'::jsonb),
  ('10D','2026-2027',65,24,'marti','2027-03-16','18:15','lectie','Unitatea 7. Poezia lirică','Simbolul și starea','[{"id": "u11:3", "fel": "lecție", "titlu": "Simbolul și starea", "titluOriginal": "Simbolul și starea", "sursa": "Badea, Poezia, p. 474", "lectia": 3, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3", "2.4"]}]'::jsonb),
  ('10D','2026-2027',66,24,'joi','2027-03-18','14:00','lectie','Unitatea 7. Poezia lirică','Proiectul','[{"id": "u11:4", "fel": "lecție", "titlu": "Proiectul", "titluOriginal": "Proiectul", "sursa": "manual, p. 162; programă 1.4", "lectia": 4, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["1.4"]}]'::jsonb),
  ('10D','2026-2027',67,25,'marti','2027-03-23','16:35','lectie','Unitatea 7. Poezia lirică','Ce este o artă poetică','[{"id": "u12:1", "fel": "lecție", "titlu": "Ce este o artă poetică", "titluOriginal": "Ce este o artă poetică", "sursa": "Badea, Poezia, p. 583", "lectia": 1, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}]'::jsonb),
  ('10D','2026-2027',68,25,'marti','2027-03-23','18:15','bloc propriu','Unitatea 7. Poezia lirică','Lectură - Titlul și tema - Metaforele materiei mărunte','[{"id": "m:15", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură"}, {"id": "u12:2", "fel": "lecție", "titlu": "Titlul și tema", "titluOriginal": "Titlul și tema", "sursa": "Badea, Poezia, pp. 583–584", "lectia": 2, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"], "comentariu": "titlul și autorul operei. Atenție! ar trebui Titlul și tema. Incipitul apare la operele epice și dramatice"}, {"id": "u12:3", "fel": "lecție", "titlu": "Metaforele materiei mărunte", "titluOriginal": "Metaforele materiei mărunte", "sursa": "Badea, Poezia, p. 584", "lectia": 3, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3", "2.4"]}]'::jsonb),
  ('10D','2026-2027',69,25,'joi','2027-03-25','14:00','lectie','Unitatea 7. Poezia lirică','Valori stilistice ale unor categorii morfosintactice','[{"id": "u12:4", "fel": "lecție", "titlu": "Valori stilistice ale unor categorii morfosintactice", "titluOriginal": "Valori stilistice ale unor categorii morfosintactice", "sursa": "manual, p. 167; programă 1.1", "lectia": 4, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["1.1", "2.3"]}]'::jsonb),
  ('10D','2026-2027',70,26,'marti','2027-03-30','16:35','lectie','Unitatea 7. Poezia lirică','Nichita Stănescu și neomodernismul','[{"id": "u13:1", "fel": "lecție", "titlu": "Nichita Stănescu și neomodernismul", "titluOriginal": "Nichita Stănescu și neomodernismul", "sursa": "Badea, Poezia, p. 725", "lectia": 1, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}]'::jsonb),
  ('10D','2026-2027',71,26,'marti','2027-03-30','18:15','bloc propriu','Unitatea 7. Poezia lirică','Lectură - Tema și titlul - Cele două planuri și imaginile','[{"id": "m:16", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură"}, {"id": "u13:2", "fel": "lecție", "titlu": "Tema și titlul", "titluOriginal": "Tema și titlul", "sursa": "Badea, Poezia, pp. 725–726", "lectia": 2, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3"]}, {"id": "u13:3", "fel": "lecție", "titlu": "Cele două planuri și imaginile", "titluOriginal": "Cele două planuri și imaginile", "sursa": "Badea, Poezia, p. 726", "lectia": 3, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["2.3", "2.4"]}]'::jsonb),
  ('10D','2026-2027',72,26,'joi','2027-04-01','14:00','lectie','Unitatea 7. Poezia lirică','Recapitulare: cinci poezii, patru epoci','[{"id": "u13:4", "fel": "lecție", "titlu": "Recapitulare: cinci poezii, patru epoci", "titluOriginal": "Recapitulare: cinci poezii, patru epoci", "sursa": "sinteză", "lectia": 4, "unitate": "Unitatea 7. Poezia lirică", "unitateId": "p7", "competenteSpecifice": ["1.4", "2.3", "3.3"]}]'::jsonb),
  ('10D','2026-2027',73,28,'marti','2027-04-13','16:35','lectie','Unitatea 7. Poezia lirică','Studiul critic ca specie - Maiorescu și critica românească','[{"id": "u10:1", "fel": "lecție", "titlu": "Studiul critic ca specie", "titluOriginal": "Studiul critic ca specie", "sursa": "programă 3.2", "lectia": 1, "unitate": "Unitatea 8. Studiul critic", "unitateId": "p8", "competenteSpecifice": ["3.2"]}, {"id": "u10:2", "fel": "lecție", "titlu": "Maiorescu și critica românească", "titluOriginal": "Maiorescu și critica românească", "sursa": "Crăciun, pp. 216–217", "lectia": 2, "unitate": "Unitatea 8. Studiul critic", "unitateId": "p8", "competenteSpecifice": ["2.1", "3.2"]}]'::jsonb),
  ('10D','2026-2027',74,28,'marti','2027-04-13','18:15','bloc propriu','Unitatea 7. Poezia lirică','Lectură - Teza și prima parte a studiului - Partea a doua. Analiza operei','[{"id": "m:17", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură"}, {"id": "u10:3", "fel": "lecție", "titlu": "Teza și prima parte a studiului", "titluOriginal": "Teza și prima parte a studiului", "sursa": "Crăciun, pp. 216–217", "lectia": 3, "unitate": "Unitatea 8. Studiul critic", "unitateId": "p8", "competenteSpecifice": ["3.1", "3.2"]}, {"id": "u10:4", "fel": "lecție", "titlu": "Partea a doua. Analiza operei", "titluOriginal": "Partea a doua. Analiza operei", "sursa": "Crăciun, p. 217", "lectia": 4, "unitate": "Unitatea 8. Studiul critic", "unitateId": "p8", "competenteSpecifice": ["3.1", "3.2", "3.3"]}]'::jsonb),
  ('10D','2026-2027',75,28,'joi','2027-04-15','14:00','lectie','Unitatea 7. Poezia lirică','Procesul-verbal. Cererea','[{"id": "u10:5", "fel": "lecție", "titlu": "Procesul-verbal. Cererea", "titluOriginal": "Procesul-verbal. Cererea", "sursa": "manual, p. 158", "lectia": 5, "unitate": "Unitatea 8. Studiul critic", "unitateId": "p8", "competenteSpecifice": ["1.4"]}]'::jsonb),
  ('10D','2026-2027',76,29,'marti','2027-04-20','16:35','lectie','Unitatea 7. Poezia lirică','Linia timpului poetic - Fișa comparativă a poeziei','[{"id": "u14:1", "fel": "lecție", "titlu": "Linia timpului poetic", "titluOriginal": "Linia timpului poetic", "sursa": "manual, p. 176; Crăciun", "lectia": 1, "unitate": "Unitatea 9. Evoluția poeziei", "unitateId": "p9", "competenteSpecifice": ["2.3", "2.4"]}, {"id": "u14:2", "fel": "lecție", "titlu": "Fișa comparativă a poeziei", "titluOriginal": "Fișa comparativă a poeziei", "sursa": "sinteză", "lectia": 2, "unitate": "Unitatea 9. Evoluția poeziei", "unitateId": "p9", "competenteSpecifice": ["1.4", "2.3", "3.3"]}]'::jsonb),
  ('10D','2026-2027',77,29,'marti','2027-04-20','18:15','bloc propriu','Unitatea 7. Poezia lirică','Recapitulare','[{"id": "m:18", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',78,29,'joi','2027-04-22','14:00','bloc propriu','Unitatea 7. Poezia lirică','Evaluare','[{"id": "m:19", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('10D','2026-2027',79,30,'joi','2027-05-06','14:00','bloc propriu','Unitatea 10. Comedia','Recapitulare','[{"id": "m:27", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',80,31,'marti','2027-05-11','16:35','bloc propriu','Unitatea 10. Comedia','Teză','[{"id": "m:26", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('10D','2026-2027',81,31,'marti','2027-05-11','18:15','lectie','Unitatea 10. Comedia','Genul dramatic. Comedia - Caragiale și lumea lui','[{"id": "u15:1", "fel": "lecție", "titlu": "Genul dramatic. Comedia", "titluOriginal": "Genul dramatic. Comedia", "sursa": "programă 2.2; Badea, Dramaturgia", "lectia": 1, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2"]}, {"id": "u15:2", "fel": "lecție", "titlu": "Caragiale și lumea lui", "titluOriginal": "Caragiale și lumea lui", "sursa": "Crăciun, pp. 308–309", "lectia": 2, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2"]}]'::jsonb),
  ('10D','2026-2027',82,31,'joi','2027-05-13','14:00','lectie','Unitatea 10. Comedia','Lectura. Subiectul și conflictul','[{"id": "u15:3", "fel": "lecție", "titlu": "Lectura. Subiectul și conflictul", "titluOriginal": "Lectura. Subiectul și conflictul", "sursa": "Crăciun, pp. 309–310", "lectia": 3, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2"]}]'::jsonb),
  ('10D','2026-2027',83,32,'marti','2027-05-18','16:35','lectie','Unitatea 10. Comedia','Scena I: deschiderea. „Curat constituțional!” - Scena a II-a: adunarea electorală','[{"id": "u15:4", "fel": "lecție", "titlu": "Scena I: deschiderea. „Curat constituțional!”", "titluOriginal": "Scena I: deschiderea. „Curat constituțional!”", "sursa": "Crăciun, pp. 310–311", "lectia": 4, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.3", "2.2"]}, {"id": "u15:5", "fel": "lecție", "titlu": "Scena a II-a: adunarea electorală", "titluOriginal": "Scena a II-a: adunarea electorală", "sursa": "Crăciun, p. 310", "lectia": 5, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2", "3.1"]}]'::jsonb),
  ('10D','2026-2027',84,32,'marti','2027-05-18','18:15','lectie','Unitatea 10. Comedia','Scena a III-a: finalul. Împăcarea ridicolă - Personajele. Tipătescu, Trahanache, Zoe - Lumea pe dos. Carnavalul - Caracterizarea personajului în textul dramatic','[{"id": "u15:6", "fel": "lecție", "titlu": "Scena a III-a: finalul. Împăcarea ridicolă", "titluOriginal": "Scena a III-a: finalul. Împăcarea ridicolă", "sursa": "Crăciun, pp. 310–311", "lectia": 6, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2", "2.4"]}, {"id": "u15:7", "fel": "lecție", "titlu": "Personajele. Tipătescu, Trahanache, Zoe", "titluOriginal": "Personajele. Tipătescu, Trahanache, Zoe", "sursa": "Crăciun, p. 311", "lectia": 7, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2"]}, {"id": "u15:8", "fel": "lecție", "titlu": "Lumea pe dos. Carnavalul", "titluOriginal": "Lumea pe dos. Carnavalul", "sursa": "Crăciun, pp. 309–311", "lectia": 8, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["2.2", "3.2"]}, {"id": "u15:9", "fel": "lecție", "titlu": "Caracterizarea personajului în textul dramatic", "titluOriginal": "Caracterizarea personajului în textul dramatic", "sursa": "manual, p. 194", "lectia": 9, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.4", "2.2"]}]'::jsonb),
  ('10D','2026-2027',85,32,'joi','2027-05-20','14:00','lectie','Unitatea 10. Comedia','Structuri și tehnici argumentative - Niveluri de constituire a mesajului - Hipercorectitudinea. Etimologia populară','[{"id": "u15:10", "fel": "lecție", "titlu": "Structuri și tehnici argumentative", "titluOriginal": "Structuri și tehnici argumentative", "sursa": "manual, p. 195", "lectia": 10, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["3.1", "3.3"]}, {"id": "u15:11", "fel": "lecție", "titlu": "Niveluri de constituire a mesajului", "titluOriginal": "Niveluri de constituire a mesajului", "sursa": "manual, p. 197", "lectia": 11, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.1", "1.5"]}, {"id": "u15:12", "fel": "lecție", "titlu": "Hipercorectitudinea. Etimologia populară", "titluOriginal": "Hipercorectitudinea. Etimologia populară", "sursa": "manual, p. 198", "lectia": 12, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.5"]}]'::jsonb),
  ('10D','2026-2027',86,33,'marti','2027-05-25','16:35','lectie','Unitatea 10. Comedia','Cele două eseuri pe „O scrisoare pierdută”','[{"id": "u15:13", "fel": "lecție", "titlu": "Cele două eseuri pe „O scrisoare pierdută”", "titluOriginal": "Cele două eseuri pe „O scrisoare pierdută”", "sursa": "Eseul – textul dramatic", "lectia": 13, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.4", "2.2", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',87,33,'marti','2027-05-25','18:15','lectie','Unitatea 10. Comedia','Cronica de spectacol - Analiza cronicii - Redactarea unei cronici','[{"id": "u16:1", "fel": "lecție", "titlu": "Cronica de spectacol", "titluOriginal": "Cronica de spectacol", "sursa": "programă 3.2; manual, p. 200", "lectia": 1, "unitate": "Unitatea 11. Cronica de spectacol", "unitateId": "p11", "competenteSpecifice": ["3.2"]}, {"id": "u16:2", "fel": "lecție", "titlu": "Analiza cronicii", "titluOriginal": "Analiza cronicii", "sursa": "manual, p. 200", "lectia": 2, "unitate": "Unitatea 11. Cronica de spectacol", "unitateId": "p11", "competenteSpecifice": ["3.1", "3.2"]}, {"id": "u16:3", "fel": "lecție", "titlu": "Redactarea unei cronici", "titluOriginal": "Redactarea unei cronici", "sursa": "programă 1.4, 3.3", "lectia": 3, "unitate": "Unitatea 11. Cronica de spectacol", "unitateId": "p11", "competenteSpecifice": ["1.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',88,33,'joi','2027-05-27','14:00','lectie','Unitatea 10. Comedia','Recapitulare','[{"id": "u15:14", "fel": "lecție", "titlu": "Recapitulare", "titluOriginal": "Recapitulare", "sursa": "programă – competențele unității", "lectia": 14, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.4", "2.2", "2.4"]}]'::jsonb),
  ('10D','2026-2027',89,34,'joi','2027-06-03','14:00','lectie','Unitatea 10. Comedia','Evaluare','[{"id": "u15:15", "fel": "lecție", "titlu": "Evaluare", "titluOriginal": "Evaluare", "sursa": "programă – competențele unității", "lectia": 15, "unitate": "Unitatea 10. Comedia", "unitateId": "p10", "competenteSpecifice": ["1.4", "2.2", "2.4", "3.3"]}]'::jsonb),
  ('10D','2026-2027',90,35,'marti','2027-06-08','16:35','bloc propriu','Unitatea 12. Drama','Lectură - Drama ca specie','[{"id": "m:20", "fel": "bloc propriu", "tip": "altul", "titlu": "Lectură", "comentariu": "Titlul și autorul operei"}, {"id": "u17:1", "fel": "lecție", "titlu": "Drama ca specie", "titluOriginal": "Drama ca specie", "sursa": "programă 2.2", "lectia": 1, "unitate": "Unitatea 12. Drama", "unitateId": "p12", "competenteSpecifice": ["2.2"]}]'::jsonb),
  ('10D','2026-2027',91,35,'marti','2027-06-08','18:15','lectie','Unitatea 12. Drama','Evoluția dramaturgiei în literatura română','[{"id": "u18:1", "fel": "lecție", "titlu": "Evoluția dramaturgiei în literatura română", "titluOriginal": "Evoluția dramaturgiei în literatura română", "sursa": "manual, p. 224; Crăciun", "lectia": 1, "unitate": "Unitatea 13. Evoluția dramaturgiei", "unitateId": "p13", "competenteSpecifice": ["2.2", "2.4"]}]'::jsonb),
  ('10D','2026-2027',92,35,'joi','2027-06-10','14:00','lectie','Unitatea 12. Drama','Interviul publicistic - Interviul de angajare','[{"id": "u17:2", "fel": "lecție", "titlu": "Interviul publicistic", "titluOriginal": "Interviul publicistic", "sursa": "manual, p. 221", "lectia": 2, "unitate": "Unitatea 12. Drama", "unitateId": "p12", "competenteSpecifice": ["1.3", "1.4"]}, {"id": "u17:3", "fel": "lecție", "titlu": "Interviul de angajare", "titluOriginal": "Interviul de angajare", "sursa": "manual, p. 222; programă 1.3", "lectia": 3, "unitate": "Unitatea 12. Drama", "unitateId": "p12", "competenteSpecifice": ["1.3", "1.4"]}]'::jsonb),
  ('10D','2026-2027',93,36,'marti','2027-06-15','16:35','bloc propriu',null,'Recapitulare','[{"id": "m:21", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',94,36,'marti','2027-06-15','18:15','bloc propriu',null,'Recapitulare','[{"id": "m:22", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('10D','2026-2027',95,36,'joi','2027-06-17','14:00','lectie',null,'Recapitulare finală a anului','[{"id": "u18:2", "fel": "lecție", "titlu": "Recapitulare finală a anului", "titluOriginal": "Recapitulare finală a anului", "sursa": "sinteză", "lectia": 2, "unitate": "Unitatea 13. Evoluția dramaturgiei", "unitateId": "p13", "competenteSpecifice": ["1.4", "2.1", "2.2", "2.3", "2.4", "3.3"]}]'::jsonb);

-- ---------- paza pe clasa asta ----------
do $$
declare n int; lipsa int;
begin
  select count(*) into n from public.school_plan where clasa = '10D' and an_scolar = '2026-2027';
  if n <> 95 then
    raise exception 'Clasa 10D are % ore, așteptam 95. Lipirea s-a rupt.', n;
  end if;
  select count(*) into lipsa from generate_series(1, 95) g
   where not exists (select 1 from public.school_plan p
                      where p.clasa = '10D' and p.an_scolar = '2026-2027' and p.nr = g);
  if lipsa > 0 then
    raise exception 'Clasei 10D îi lipsesc % numere din șirul 1..95.', lipsa;
  end if;
  raise notice 'Clasa 10D: 95 de ore, la locul lor.';
end $$;
