-- =========================================================
-- 0097c · LICEU: planificarea clasei 11B, pe orarul din 21 septembrie
--
-- Una din cinci. Se rulează în ordine: 0097a, 0097b, 0097c, 0097d, 0097e.
-- Ultima ține paza pe toate cinci deodată.
--
-- DE CE CINCI FIȘIERE, NU UNUL. Întregul făcea 297 KB, iar SQL Editor îl
-- refuză: „request entity too large". Pe clasă iese vreo 53 KB și intră.
--
-- Punctul de pornire e `Diverse/ORAR 21 SEPT/Planificatoare/`, exportul din
-- planificatorul lui Marius. El e adevărul; documentele Word se nasc din el.
--
-- CE SE SCHIMBĂ, la toate cinci (comparat amprentă cu amprentă, nu din ochi):
--   · 9B și 11D — neschimbate. Intră totuși, ca regula să n-aibă excepții de
--     ținut minte, iar ce iese e la fel cu ce era.
--   · 11C și 11D — își mută ora de vineri, de pe 21 sept. încolo (11C de la
--     11:25 la 10:35, 11D de la 10:35 la 11:25).
--   · 10D — recapitularea inițială scade de la 4 ore la 3, „Unitatea 1. Basmul
--     cult" începe la ora 4 în loc de 5, iar cele două lecții care stăteau
--     împreună la ora 6 se despart în orele 5 și 6.
--   · 11B — se schimbă unitățile 2 și 3 (orele 21–56). Primele 20 rămân.
--   · 11C — plan nou din temelii: are acum exact planul lui 11D.
--
-- 12C ȘI 12D NU SE ATING: ele merg pe planificarea de bacalaureat (0093).
--
-- ZIUA SE SCRIE FĂRĂ DIACRITICE („marti"), ca în orar: îmbinarea dintre
-- planificare și orar se face pe ea, iar o literă deosebită ar fi rupt-o în
-- tăcere.
--
-- `blocuri` SE ȚINE CIUNTIT: rămân numele, sursa, unitatea și competențele; se
-- lasă afară `notiuni`, `activitati` și `ideeaDeRetinut` — materialul de predare,
-- nouă zecimi din greutate, pe care modulul nu-l citește nicăieri. El rămâne
-- întreg în JSON-urile din `Diverse/ORAR 21 SEPT/`.
--
-- SE ȘTERGE ȘI SE SCRIE LA LOC. Un `update` rând cu rând ar fi lăsat în urmă
-- orele care nu mai există, iar cheia unică (clasă, an, dată, ceas) s-ar fi
-- lovit de ele la 11C și 11D, unde ceasul se mută.
-- =========================================================

delete from public.school_plan where clasa = '11B' and an_scolar = '2026-2027';

insert into public.school_plan
  (clasa, an_scolar, nr, saptamana, zi, data, ora, fel, unitatea, titlu, blocuri) values
  ('11B','2026-2027',1,1,'luni','2026-09-07','8:00','bloc propriu','Recapitulare inițială','Recapitulare','[{"id": "m:6", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',2,1,'miercuri','2026-09-09','12:15','bloc propriu','Recapitulare inițială','Recapitulare','[{"id": "m:7", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',3,1,'vineri','2026-09-11','12:15','bloc propriu','Recapitulare inițială','Recapitulare','[{"id": "m:8", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',4,2,'luni','2026-09-14','8:00','lectie','Unitatea 1. Fundamente','Limbă, limbaj, lingvistică. Limba română națională - Structura etimologică a lexicului. Fondul autohton geto-dacic - Latina, baza lingvistică a limbii române. Romanizarea Daciei - Limba română, limbă romanică. Familii de limbi. Etimologie și etimon','[{"id": "u1:1", "fel": "lecție", "titlu": "Limbă, limbaj, lingvistică. Limba română națională", "titluOriginal": "Limbă, limbaj, lingvistică. Limba română națională", "sursa": "manual, pp. 4–5", "lectia": 1, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.3", "3.2"]}, {"id": "u1:2", "fel": "lecție", "titlu": "Structura etimologică a lexicului. Fondul autohton geto-dacic", "titluOriginal": "Structura etimologică a lexicului. Fondul autohton geto-dacic", "sursa": "manual, pp. 5–6", "lectia": 2, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.2", "3.4"]}, {"id": "u1:3", "fel": "lecție", "titlu": "Latina, baza lingvistică a limbii române. Romanizarea Daciei", "titluOriginal": "Latina, baza lingvistică a limbii române. Romanizarea Daciei", "sursa": "manual, pp. 6–7", "lectia": 3, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2", "4.1"]}, {"id": "u1:4", "fel": "lecție", "titlu": "Limba română, limbă romanică. Familii de limbi. Etimologie și etimon", "titluOriginal": "Limba română, limbă romanică. Familii de limbi. Etimologie și etimon", "sursa": "manual, pp. 6–7 și 9", "lectia": 4, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "3.3", "3.4"]}]'::jsonb),
  ('11B','2026-2027',5,2,'miercuri','2026-09-16','12:15','lectie','Unitatea 1. Fundamente','Fondul principal lexical. Elementul migrator și contactul dintre limbi - Latinitatea limbii române. Împrumuturi, formații românești, calcuri','[{"id": "u1:5", "fel": "lecție", "titlu": "Fondul principal lexical. Elementul migrator și contactul dintre limbi", "titluOriginal": "Fondul principal lexical. Elementul migrator și contactul dintre limbi", "sursa": "manual, pp. 7–8", "lectia": 5, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.2", "2.1"]}, {"id": "u1:6", "fel": "lecție", "titlu": "Latinitatea limbii române. Împrumuturi, formații românești, calcuri", "titluOriginal": "Latinitatea limbii române. Împrumuturi, formații românești, calcuri", "sursa": "manual, pp. 7–9", "lectia": 6, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.4", "3.1"]}]'::jsonb),
  ('11B','2026-2027',6,2,'vineri','2026-09-18','12:15','lectie','Unitatea 1. Fundamente','Apariția scrisului în limba română. Scrisoarea lui Neacșu (1521) - Reforma și primele tipărituri. Scrierile rotacizante','[{"id": "u1:7", "fel": "lecție", "titlu": "Apariția scrisului în limba română. Scrisoarea lui Neacșu (1521)", "titluOriginal": "Apariția scrisului în limba română. Scrisoarea lui Neacșu (1521)", "sursa": "manual, pp. 10–11", "lectia": 7, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.1", "1.1", "3.1"]}, {"id": "u1:8", "fel": "lecție", "titlu": "Reforma și primele tipărituri. Scrierile rotacizante", "titluOriginal": "Reforma și primele tipărituri. Scrierile rotacizante", "sursa": "manual, pp. 11–12", "lectia": 8, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11B','2026-2027',7,3,'luni','2026-09-21','8:00','lectie','Unitatea 1. Fundamente','Diaconul Coresi. Fixarea bazei limbii române literare - Primele texte juridice. Nașterea stilului administrativ','[{"id": "u1:9", "fel": "lecție", "titlu": "Diaconul Coresi. Fixarea bazei limbii române literare", "titluOriginal": "Diaconul Coresi. Fixarea bazei limbii române literare", "sursa": "manual, p. 12", "lectia": 9, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2", "4.1"]}, {"id": "u1:10", "fel": "lecție", "titlu": "Primele texte juridice. Nașterea stilului administrativ", "titluOriginal": "Primele texte juridice. Nașterea stilului administrativ", "sursa": "manual, p. 13", "lectia": 10, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.4", "2.1"]}]'::jsonb),
  ('11B','2026-2027',8,3,'miercuri','2026-09-23','12:15','lectie','Unitatea 1. Fundamente','Limba literară, registrele și stilurile funcționale','[{"id": "u1:14", "fel": "lecție", "titlu": "Limba literară, registrele și stilurile funcționale", "titluOriginal": "Limba literară, registrele și stilurile funcționale", "sursa": "manual, pp. 17–18", "lectia": 14, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.3", "2.1"]}]'::jsonb),
  ('11B','2026-2027',9,3,'vineri','2026-09-25','12:15','lectie','Unitatea 1. Fundamente','Latinitate și dacism. Dacii și geții. Cultura geto-dacă','[{"id": "u1:15", "fel": "lecție", "titlu": "Latinitate și dacism. Dacii și geții. Cultura geto-dacă", "titluOriginal": "Latinitate și dacism. Dacii și geții. Cultura geto-dacă", "sursa": "manual, pp. 19–20", "lectia": 15, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2", "3.4"]}]'::jsonb),
  ('11B','2026-2027',10,4,'luni','2026-09-28','8:00','lectie','Unitatea 1. Fundamente','B.P. Hasdeu, „Perit-au dacii?”. Reabilitarea substratului dacic - Hasdeu: legea circulației cuvintelor. Cihac și teoriile imigraționiste','[{"id": "u1:18", "fel": "lecție", "titlu": "B.P. Hasdeu, „Perit-au dacii?”. Reabilitarea substratului dacic", "titluOriginal": "B.P. Hasdeu, „Perit-au dacii?”. Reabilitarea substratului dacic", "sursa": "manual, pp. 24–25", "lectia": 18, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.1", "4.1", "4.2"]}, {"id": "u1:19", "fel": "lecție", "titlu": "Hasdeu: legea circulației cuvintelor. Cihac și teoriile imigraționiste", "titluOriginal": "Hasdeu: legea circulației cuvintelor. Cihac și teoriile imigraționiste", "sursa": "manual, pp. 25–27", "lectia": 19, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "4.1", "4.2"]}]'::jsonb),
  ('11B','2026-2027',11,4,'miercuri','2026-09-30','12:15','lectie','Unitatea 1. Fundamente','Vasile Pârvan, „Getica”. Mitologia pământului românesc','[{"id": "u1:20", "fel": "lecție", "titlu": "Vasile Pârvan, „Getica”. Mitologia pământului românesc", "titluOriginal": "Vasile Pârvan, „Getica”. Mitologia pământului românesc", "sursa": "manual, pp. 28–31", "lectia": 20, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.2", "3.2"]}]'::jsonb),
  ('11B','2026-2027',12,4,'vineri','2026-10-02','12:15','lectie','Unitatea 1. Fundamente','Lucian Blaga, „Revolta fondului nostru nelatin”. Mircea Vulcănescu. Concluzii','[{"id": "u1:21", "fel": "lecție", "titlu": "Lucian Blaga, „Revolta fondului nostru nelatin”. Mircea Vulcănescu. Concluzii", "titluOriginal": "Lucian Blaga, „Revolta fondului nostru nelatin”. Mircea Vulcănescu. Concluzii", "sursa": "manual, pp. 32–34", "lectia": 21, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.2", "2.3", "4.2"]}]'::jsonb),
  ('11B','2026-2027',13,5,'miercuri','2026-10-07','12:15','lectie','Unitatea 1. Fundamente','Vasile Alecsandri, „Cântecul gintei latine”. Concursul de la Montpellier','[{"id": "u1:23", "fel": "lecție", "titlu": "Vasile Alecsandri, „Cântecul gintei latine”. Concursul de la Montpellier", "titluOriginal": "Vasile Alecsandri, „Cântecul gintei latine”. Concursul de la Montpellier", "sursa": "manual, pp. 37–38", "lectia": 23, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.3", "3.3"]}]'::jsonb),
  ('11B','2026-2027',14,5,'vineri','2026-10-09','12:15','lectie','Unitatea 1. Fundamente','Eminescu, „Memento mori”. Mit, istorie și vizionarism romantic - Denotație și conotație','[{"id": "u1:24", "fel": "lecție", "titlu": "Eminescu, „Memento mori”. Mit, istorie și vizionarism romantic", "titluOriginal": "Eminescu, „Memento mori”. Mit, istorie și vizionarism romantic", "sursa": "manual, pp. 39–41", "lectia": 24, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.2", "3.1", "3.2"]}, {"id": "u1:26", "fel": "lecție", "titlu": "Denotație și conotație", "titluOriginal": "Denotație și conotație", "sursa": "manual, pp. 46–47", "lectia": 26, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "2.1", "2.3"]}]'::jsonb),
  ('11B','2026-2027',15,7,'luni','2026-10-19','8:00','lectie','Unitatea 1. Fundamente','Stilul și calitățile lui generale (I). Corectitudinea','[{"id": "u1:27", "fel": "lecție", "titlu": "Stilul și calitățile lui generale (I). Corectitudinea", "titluOriginal": "Stilul și calitățile lui generale (I). Corectitudinea", "sursa": "manual, p. 48", "lectia": 27, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.2", "1.4", "2.3"]}]'::jsonb),
  ('11B','2026-2027',16,7,'miercuri','2026-10-21','12:15','lectie','Unitatea 1. Fundamente','Mitul jertfei și mitul întemeierii: „Miorița” și „Monastirea Argeșului”','[{"id": "u1:29", "fel": "lecție", "titlu": "Mitul jertfei și mitul întemeierii: „Miorița” și „Monastirea Argeșului”", "titluOriginal": "Mitul jertfei și mitul întemeierii: „Miorița” și „Monastirea Argeșului”", "sursa": "Gh. Crăciun, „Istoria literaturii române pentru elevi și profesori”; aprofundare", "lectia": 29, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["2.2", "3.2", "3.3"]}]'::jsonb),
  ('11B','2026-2027',17,7,'vineri','2026-10-23','12:15','lectie','Unitatea 1. Fundamente','Studiu pe text: două pravile, două variante literare (1646 și 1652)','[{"id": "u1:31", "fel": "lecție", "titlu": "Studiu pe text: două pravile, două variante literare (1646 și 1652)", "titluOriginal": "Studiu pe text: două pravile, două variante literare (1646 și 1652)", "sursa": "manual, pp. 11 și 13; aprofundare", "lectia": 31, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["1.1", "1.2", "3.1"]}]'::jsonb),
  ('11B','2026-2027',18,8,'luni','2026-11-02','8:00','lectie','Unitatea 1. Fundamente','Sinteză: drumul limbii române literare, de la Coresi la Școala Ardeleană','[{"id": "u1:32", "fel": "lecție", "titlu": "Sinteză: drumul limbii române literare, de la Coresi la Școala Ardeleană", "titluOriginal": "Sinteză: drumul limbii române literare, de la Coresi la Școala Ardeleană", "sursa": "manual, p. 15 și Gh. Crăciun; aprofundare", "lectia": 32, "unitate": "Unitatea 1. Fundamente", "unitateId": "p1", "competenteSpecifice": ["3.1", "3.2", "1.4"]}]'::jsonb),
  ('11B','2026-2027',19,8,'miercuri','2026-11-04','12:15','bloc propriu','Unitatea 1. Fundamente','Recapitulare','[{"id": "m:9", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',20,8,'vineri','2026-11-06','12:15','bloc propriu','Unitatea 1. Fundamente','Evaluare','[{"id": "m:10", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('11B','2026-2027',21,9,'luni','2026-11-09','8:00','lectie','Unitatea 2. Perioada veche','Religiozitatea făpturii umane. Rolul religiei în Țările Române - Literatura religioasă în limba română. O nouă elită intelectuală - Cazania lui Varlaam, carte românească de învățătură - Noul Testament de la Bălgrad și concepția despre limbă a lui Simion Ștefan','[{"id": "u2:1", "fel": "lecție", "titlu": "Religiozitatea făpturii umane. Rolul religiei în Țările Române", "titluOriginal": "Religiozitatea făpturii umane. Rolul religiei în Țările Române", "sursa": "manual, pp. 50–51", "lectia": 1, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["3.1", "3.2"]}, {"id": "u2:2", "fel": "lecție", "titlu": "Literatura religioasă în limba română. O nouă elită intelectuală", "titluOriginal": "Literatura religioasă în limba română. O nouă elită intelectuală", "sursa": "manual, p. 51", "lectia": 2, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["3.1", "3.2"]}, {"id": "u2:3", "fel": "lecție", "titlu": "Cazania lui Varlaam, carte românească de învățătură", "titluOriginal": "Cazania lui Varlaam, carte românească de învățătură", "sursa": "manual, pp. 51–53", "lectia": 3, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "3.1"]}, {"id": "u2:4", "fel": "lecție", "titlu": "Noul Testament de la Bălgrad și concepția despre limbă a lui Simion Ștefan", "titluOriginal": "Noul Testament de la Bălgrad și concepția despre limbă a lui Simion Ștefan", "sursa": "manual, pp. 53–54", "lectia": 4, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["1.2", "2.2", "4.1"]}]'::jsonb),
  ('11B','2026-2027',22,9,'miercuri','2026-11-11','12:15','lectie','Unitatea 2. Perioada veche','Sensul religios al existenței la Grigore Ureche','[{"id": "u2:5", "fel": "lecție", "titlu": "Sensul religios al existenței la Grigore Ureche", "titluOriginal": "Sensul religios al existenței la Grigore Ureche", "sursa": "manual, pp. 54–55", "lectia": 5, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.2", "3.1"]}]'::jsonb),
  ('11B','2026-2027',23,9,'vineri','2026-11-13','12:15','lectie','Unitatea 2. Perioada veche','Miron Costin și fragilitatea făpturii umane. Poemul „Viața lumii”','[{"id": "u2:6", "fel": "lecție", "titlu": "Miron Costin și fragilitatea făpturii umane. Poemul „Viața lumii”", "titluOriginal": "Miron Costin și fragilitatea făpturii umane. Poemul „Viața lumii”", "sursa": "manual, pp. 55–58", "lectia": 6, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.2", "2.3"]}]'::jsonb),
  ('11B','2026-2027',24,10,'luni','2026-11-16','8:00','lectie','Unitatea 2. Perioada veche','Psaltirea în versuri a lui Dosoftei - Biblia de la București, 1688 - Didahiile lui Antim Ivireanul și stilul oratoric - Concluziile studiului de caz. Pictură și literatură','[{"id": "u2:7", "fel": "lecție", "titlu": "Psaltirea în versuri a lui Dosoftei", "titluOriginal": "Psaltirea în versuri a lui Dosoftei", "sursa": "manual, pp. 59–60", "lectia": 7, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.2", "3.1"]}, {"id": "u2:8", "fel": "lecție", "titlu": "Biblia de la București, 1688", "titluOriginal": "Biblia de la București, 1688", "sursa": "manual, pp. 60–61", "lectia": 8, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["1.2", "3.2", "3.4"]}, {"id": "u2:9", "fel": "lecție", "titlu": "Didahiile lui Antim Ivireanul și stilul oratoric", "titluOriginal": "Didahiile lui Antim Ivireanul și stilul oratoric", "sursa": "manual, pp. 61–63", "lectia": 9, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "1.3", "2.3"]}, {"id": "u2:10", "fel": "lecție", "titlu": "Concluziile studiului de caz. Pictură și literatură", "titluOriginal": "Concluziile studiului de caz. Pictură și literatură", "sursa": "manual, pp. 63–64", "lectia": 10, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["3.2", "3.3", "2.2"]}]'::jsonb),
  ('11B','2026-2027',25,10,'miercuri','2026-11-18','12:15','lectie','Unitatea 2. Perioada veche','Norma literară - Variante literare libere','[{"id": "u2:11", "fel": "lecție", "titlu": "Norma literară", "titluOriginal": "Norma literară", "sursa": "manual, p. 65", "lectia": 11, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["1.1", "1.2"]}, {"id": "u2:12", "fel": "lecție", "titlu": "Variante literare libere", "titluOriginal": "Variante literare libere", "sursa": "manual, p. 66", "lectia": 12, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["1.1", "1.2", "2.1"]}]'::jsonb),
  ('11B','2026-2027',26,10,'vineri','2026-11-20','12:15','lectie','Unitatea 2. Perioada veche','Preliminarii. Grigore Ureche și romanitatea limbii','[{"id": "u2:13", "fel": "lecție", "titlu": "Preliminarii. Grigore Ureche și romanitatea limbii", "titluOriginal": "Preliminarii. Grigore Ureche și romanitatea limbii", "sursa": "manual, pp. 67–68", "lectia": 13, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["1.1", "3.1", "3.2"]}]'::jsonb),
  ('11B','2026-2027',27,11,'luni','2026-11-23','8:00','lectie','Unitatea 2. Perioada veche','Miron Costin, „De neamul moldovenilor” - Stolnicul Constantin Cantacuzino și argumentul continuității','[{"id": "u2:14", "fel": "lecție", "titlu": "Miron Costin, „De neamul moldovenilor”", "titluOriginal": "Miron Costin, „De neamul moldovenilor”", "sursa": "manual, pp. 68–69", "lectia": 14, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "3.1", "4.1"]}, {"id": "u2:15", "fel": "lecție", "titlu": "Stolnicul Constantin Cantacuzino și argumentul continuității", "titluOriginal": "Stolnicul Constantin Cantacuzino și argumentul continuității", "sursa": "manual, p. 69", "lectia": 15, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["4.1", "4.2", "3.1"]}]'::jsonb),
  ('11B','2026-2027',28,11,'miercuri','2026-11-25','12:15','lectie','Unitatea 2. Perioada veche','Neologismele','[{"id": "u2:18", "fel": "lecție", "titlu": "Neologismele", "titluOriginal": "Neologismele", "sursa": "manual, pp. 75–76", "lectia": 18, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["1.1", "1.2", "1.4"]}]'::jsonb),
  ('11B','2026-2027',29,11,'vineri','2026-11-27','12:15','lectie','Unitatea 2. Perioada veche','Umanismul european și umanismul românesc','[{"id": "u2:19", "fel": "lecție", "titlu": "Umanismul european și umanismul românesc", "titluOriginal": "Umanismul european și umanismul românesc", "sursa": "manual, pp. 77–80", "lectia": 19, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["3.1", "3.2", "3.3"]}]'::jsonb),
  ('11B','2026-2027',30,12,'miercuri','2026-12-02','12:15','lectie','Unitatea 2. Perioada veche','Iluminismul european și Școala Ardeleană','[{"id": "u2:20", "fel": "lecție", "titlu": "Iluminismul european și Școala Ardeleană", "titluOriginal": "Iluminismul european și Școala Ardeleană", "sursa": "manual, pp. 81–83", "lectia": 20, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["3.1", "3.2", "3.4"]}]'::jsonb),
  ('11B','2026-2027',31,12,'vineri','2026-12-04','12:15','lectie','Unitatea 2. Perioada veche','Portretul lui Ștefan cel Mare la Grigore Ureche. Studiu pe text','[{"id": "u2:22", "fel": "lecție", "titlu": "Portretul lui Ștefan cel Mare la Grigore Ureche. Studiu pe text", "titluOriginal": "Portretul lui Ștefan cel Mare la Grigore Ureche. Studiu pe text", "sursa": "manual, pp. 54–55; Gh. Crăciun, „Istoria literaturii române pentru elevi și profesori”; aprofundare", "lectia": 22, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.3", "3.3"]}]'::jsonb),
  ('11B','2026-2027',32,13,'luni','2026-12-07','8:00','bloc propriu','Unitatea 2. Perioada veche','Recapitulare','[{"id": "m:12", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',33,13,'miercuri','2026-12-09','12:15','bloc propriu','Unitatea 2. Perioada veche','Teză','[{"id": "m:11", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('11B','2026-2027',34,13,'vineri','2026-12-11','12:15','lectie','Unitatea 2. Perioada veche','„Viața lumii”: fortuna labilis și codul moral. Studiu pe text - Dosoftei și Antim Ivireanul, două trepte ale limbajului religios','[{"id": "u2:23", "fel": "lecție", "titlu": "„Viața lumii”: fortuna labilis și codul moral. Studiu pe text", "titluOriginal": "„Viața lumii”: fortuna labilis și codul moral. Studiu pe text", "sursa": "manual, pp. 55–58; aprofundare", "lectia": 23, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.1", "2.3", "4.1"]}, {"id": "u2:24", "fel": "lecție", "titlu": "Dosoftei și Antim Ivireanul, două trepte ale limbajului religios", "titluOriginal": "Dosoftei și Antim Ivireanul, două trepte ale limbajului religios", "sursa": "manual, pp. 59–63; aprofundare", "lectia": 24, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["2.2", "2.3", "1.3"]}]'::jsonb),
  ('11B','2026-2027',35,14,'luni','2026-12-14','8:00','lectie','Unitatea 2. Perioada veche','Umanism și iluminism, o comparație','[{"id": "u2:26", "fel": "lecție", "titlu": "Umanism și iluminism, o comparație", "titluOriginal": "Umanism și iluminism, o comparație", "sursa": "manual, pp. 77–83; aprofundare", "lectia": 26, "unitate": "Unitatea 2. Perioada veche", "unitateId": "p2", "competenteSpecifice": ["3.2", "4.1", "4.2"]}]'::jsonb),
  ('11B','2026-2027',36,14,'miercuri','2026-12-16','12:15','bloc propriu','Unitatea 2. Perioada veche','Recapitulare','[{"id": "m:13", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',37,14,'vineri','2026-12-18','12:15','bloc propriu','Unitatea 2. Perioada veche','Evaluare','[{"id": "m:14", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('11B','2026-2027',38,15,'luni','2026-12-21','8:00','bloc propriu','Unitatea 2. Perioada veche','Recapitulare','[{"id": "m:15", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',39,16,'luni','2027-01-11','8:00','lectie','Unitatea 3. Perioada modernă','Epoca pașoptistă. Cadrul istoric și rolul literaturii - Între clasicism și romantism. Coexistența curentelor','[{"id": "u3:1", "fel": "lecție", "titlu": "Epoca pașoptistă. Cadrul istoric și rolul literaturii", "titluOriginal": "Epoca pașoptistă. Cadrul istoric și rolul literaturii", "sursa": "manual, pp. 85–86", "lectia": 1, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "2.1"]}, {"id": "u3:2", "fel": "lecție", "titlu": "Între clasicism și romantism. Coexistența curentelor", "titluOriginal": "Între clasicism și romantism. Coexistența curentelor", "sursa": "manual, p. 86", "lectia": 2, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.2", "3.1", "3.3"]}]'::jsonb),
  ('11B','2026-2027',40,16,'miercuri','2027-01-13','12:15','lectie','Unitatea 3. Perioada modernă','„Introducție” la „Dacia literară”. Textul-program al generației - Ideile programatice și orientările literaturii pașoptiste','[{"id": "u3:3", "fel": "lecție", "titlu": "„Introducție” la „Dacia literară”. Textul-program al generației", "titluOriginal": "„Introducție” la „Dacia literară”. Textul-program al generației", "sursa": "manual, p. 87", "lectia": 3, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "1.1", "3.1"]}, {"id": "u3:4", "fel": "lecție", "titlu": "Ideile programatice și orientările literaturii pașoptiste", "titluOriginal": "Ideile programatice și orientările literaturii pașoptiste", "sursa": "manual, pp. 87–88", "lectia": 4, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "1.4"]}]'::jsonb),
  ('11B','2026-2027',41,16,'vineri','2027-01-15','12:15','lectie','Unitatea 3. Perioada modernă','Forme hibride ale civilizației românești - Ion Ghica, memorialist. Stilul epistolar și „Băltărețu”','[{"id": "u3:5", "fel": "lecție", "titlu": "Forme hibride ale civilizației românești", "titluOriginal": "Forme hibride ale civilizației românești", "sursa": "manual, p. 89", "lectia": 5, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "2.2"]}, {"id": "u3:6", "fel": "lecție", "titlu": "Ion Ghica, memorialist. Stilul epistolar și „Băltărețu”", "titluOriginal": "Ion Ghica, memorialist. Stilul epistolar și „Băltărețu”", "sursa": "manual, pp. 89–92", "lectia": 6, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.2", "3.1"]}]'::jsonb),
  ('11B','2026-2027',42,17,'luni','2027-01-18','8:00','lectie','Unitatea 3. Perioada modernă','Oralitatea narațiunii. Tradiții ale prozei memorialistice - Stilul direct','[{"id": "u3:7", "fel": "lecție", "titlu": "Oralitatea narațiunii. Tradiții ale prozei memorialistice", "titluOriginal": "Oralitatea narațiunii. Tradiții ale prozei memorialistice", "sursa": "manual, pp. 93–94", "lectia": 7, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1", "2.2"]}, {"id": "u3:8", "fel": "lecție", "titlu": "Stilul direct", "titluOriginal": "Stilul direct", "sursa": "manual, p. 95", "lectia": 8, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["1.1", "1.2", "1.4"]}]'::jsonb),
  ('11B','2026-2027',43,17,'miercuri','2027-01-20','12:15','lectie','Unitatea 3. Perioada modernă','România, între Orient și Occident. Termenii dezbaterii','[{"id": "u3:9", "fel": "lecție", "titlu": "România, între Orient și Occident. Termenii dezbaterii", "titluOriginal": "România, între Orient și Occident. Termenii dezbaterii", "sursa": "manual, pp. 96–97 și 101–102", "lectia": 9, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["4.1", "4.2", "3.2"]}]'::jsonb),
  ('11B','2026-2027',44,17,'vineri','2027-01-22','12:15','lectie','Unitatea 3. Perioada modernă','Anton Pann și lumea „Poveștii vorbii” - Ion Barbu, „Isarlâk”. Dimensiunea balcanică a liricii','[{"id": "u3:10", "fel": "lecție", "titlu": "Anton Pann și lumea „Poveștii vorbii”", "titluOriginal": "Anton Pann și lumea „Poveștii vorbii”", "sursa": "manual, pp. 97–99", "lectia": 10, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.3", "1.3"]}, {"id": "u3:11", "fel": "lecție", "titlu": "Ion Barbu, „Isarlâk”. Dimensiunea balcanică a liricii", "titluOriginal": "Ion Barbu, „Isarlâk”. Dimensiunea balcanică a liricii", "sursa": "manual, pp. 99–101", "lectia": 11, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.2", "2.3", "3.3"]}]'::jsonb),
  ('11B','2026-2027',45,18,'luni','2027-01-25','8:00','lectie','Unitatea 3. Perioada modernă','Valoarea literaturii populare. Cele patru mituri fundamentale - „Miorița”. Situare contextuală, acțiune și problematică','[{"id": "u3:13", "fel": "lecție", "titlu": "Valoarea literaturii populare. Cele patru mituri fundamentale", "titluOriginal": "Valoarea literaturii populare. Cele patru mituri fundamentale", "sursa": "manual, p. 104", "lectia": 13, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "3.4"]}, {"id": "u3:14", "fel": "lecție", "titlu": "„Miorița”. Situare contextuală, acțiune și problematică", "titluOriginal": "„Miorița”. Situare contextuală, acțiune și problematică", "sursa": "manual, pp. 104–105", "lectia": 14, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.3", "3.1"]}]'::jsonb),
  ('11B','2026-2027',46,18,'miercuri','2027-01-27','12:15','lectie','Unitatea 3. Perioada modernă','„Miorița”. Structură, compoziție și marile interpretări','[{"id": "u3:15", "fel": "lecție", "titlu": "„Miorița”. Structură, compoziție și marile interpretări", "titluOriginal": "„Miorița”. Structură, compoziție și marile interpretări", "sursa": "manual, pp. 106–107", "lectia": 15, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.2", "2.3", "4.2"]}]'::jsonb),
  ('11B','2026-2027',47,18,'vineri','2027-01-29','12:15','lectie','Unitatea 3. Perioada modernă','Receptarea unui text non-artistic. Tudor Vianu','[{"id": "u3:17", "fel": "lecție", "titlu": "Receptarea unui text non-artistic. Tudor Vianu", "titluOriginal": "Receptarea unui text non-artistic. Tudor Vianu", "sursa": "manual, pp. 111–112", "lectia": 17, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["1.1", "2.1", "1.4"]}]'::jsonb),
  ('11B','2026-2027',48,19,'luni','2027-02-01','8:00','bloc propriu','Unitatea 3. Perioada modernă','Recapitulare','[{"id": "m:16", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',49,19,'miercuri','2027-02-03','12:15','lectie','Unitatea 3. Perioada modernă','Test de evaluare. De la pașoptism la literatura populară','[{"id": "u3:18", "fel": "lecție", "titlu": "Test de evaluare. De la pașoptism la literatura populară", "titluOriginal": "Test de evaluare. De la pașoptism la literatura populară", "sursa": "manual, p. 113", "lectia": 18, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["1.4", "2.1", "4.1"]}]'::jsonb),
  ('11B','2026-2027',50,19,'vineri','2027-02-05','12:15','lectie','Unitatea 3. Perioada modernă','Criticismul junimist. Maiorescu, „În contra direcției de astăzi în cultura română”','[{"id": "u3:19", "fel": "lecție", "titlu": "Criticismul junimist. Maiorescu, „În contra direcției de astăzi în cultura română”", "titluOriginal": "Criticismul junimist. Maiorescu, „În contra direcției de astăzi în cultura română”", "sursa": "manual, pp. 114–115", "lectia": 19, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.1", "4.1"]}]'::jsonb),
  ('11B','2026-2027',51,20,'luni','2027-02-08','8:00','lectie','Unitatea 3. Perioada modernă','De la cultura eroică la cultura critică - Teoria formelor fără fond. Autonomia valorilor și replica sincronismului','[{"id": "u3:20", "fel": "lecție", "titlu": "De la cultura eroică la cultura critică", "titluOriginal": "De la cultura eroică la cultura critică", "sursa": "manual, pp. 115–116", "lectia": 20, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["3.1", "3.2", "4.2"]}, {"id": "u3:21", "fel": "lecție", "titlu": "Teoria formelor fără fond. Autonomia valorilor și replica sincronismului", "titluOriginal": "Teoria formelor fără fond. Autonomia valorilor și replica sincronismului", "sursa": "manual, pp. 117–119", "lectia": 21, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["4.1", "4.2", "3.2"]}]'::jsonb),
  ('11B','2026-2027',52,20,'miercuri','2027-02-10','12:15','lectie','Unitatea 3. Perioada modernă','Stilul și calitățile lui generale (II). Claritatea','[{"id": "u3:22", "fel": "lecție", "titlu": "Stilul și calitățile lui generale (II). Claritatea", "titluOriginal": "Stilul și calitățile lui generale (II). Claritatea", "sursa": "manual, pp. 120–121", "lectia": 22, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["1.2", "1.4", "1.1"]}]'::jsonb),
  ('11B','2026-2027',53,20,'vineri','2027-02-12','12:15','lectie','Unitatea 3. Perioada modernă','Studiu pe text: „Introducție” la „Dacia literară”, anatomia unui manifest','[{"id": "u3:23", "fel": "lecție", "titlu": "Studiu pe text: „Introducție” la „Dacia literară”, anatomia unui manifest", "titluOriginal": "Studiu pe text: „Introducție” la „Dacia literară”, anatomia unui manifest", "sursa": "manual, p. 87; aprofundare", "lectia": 23, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "4.1", "1.4"]}]'::jsonb),
  ('11B','2026-2027',54,21,'luni','2027-02-15','8:00','lectie','Unitatea 3. Perioada modernă','Junimea, o societate a spiritului critic. Retorica lui Maiorescu','[{"id": "u3:27", "fel": "lecție", "titlu": "Junimea, o societate a spiritului critic. Retorica lui Maiorescu", "titluOriginal": "Junimea, o societate a spiritului critic. Retorica lui Maiorescu", "sursa": "manual, pp. 114–118; aprofundare", "lectia": 27, "unitate": "Unitatea 3. Perioada modernă", "unitateId": "p3", "competenteSpecifice": ["2.1", "4.1", "3.4"]}]'::jsonb),
  ('11B','2026-2027',55,21,'miercuri','2027-02-17','12:15','bloc propriu','Unitatea 3. Perioada modernă','Recapitulare','[{"id": "m:17", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',56,21,'vineri','2027-02-19','12:15','bloc propriu','Unitatea 3. Perioada modernă','Evaluare','[{"id": "m:18", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('11B','2026-2027',57,22,'luni','2027-03-01','8:00','lectie','Unitatea 4. Curente literare','Curentul literar. Apariție, afirmare, evoluție - Romantismul european. Cristalizare și estetică','[{"id": "u4:1", "fel": "lecție", "titlu": "Curentul literar. Apariție, afirmare, evoluție", "titluOriginal": "Curentul literar. Apariție, afirmare, evoluție", "sursa": "manual, pp. 132–133", "lectia": 1, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.2", "1.1"]}, {"id": "u4:2", "fel": "lecție", "titlu": "Romantismul european. Cristalizare și estetică", "titluOriginal": "Romantismul european. Cristalizare și estetică", "sursa": "manual, pp. 133–134", "lectia": 2, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.3", "2.2"]}]'::jsonb),
  ('11B','2026-2027',58,22,'miercuri','2027-03-03','12:15','lectie','Unitatea 4. Curente literare','Romantismul românesc. Gr. Alexandrescu, „Umbra lui Mircea. La Cozia”','[{"id": "u4:3", "fel": "lecție", "titlu": "Romantismul românesc. Gr. Alexandrescu, „Umbra lui Mircea. La Cozia”", "titluOriginal": "Romantismul românesc. Gr. Alexandrescu, „Umbra lui Mircea. La Cozia”", "sursa": "manual, pp. 135–137", "lectia": 3, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.1", "2.2"]}]'::jsonb),
  ('11B','2026-2027',59,22,'vineri','2027-03-05','12:15','lectie','Unitatea 4. Curente literare','Universul operei eminesciene. Marile teme - Formația poetului. Teme și motive eminesciene. Sinteză','[{"id": "u4:4", "fel": "lecție", "titlu": "Universul operei eminesciene. Marile teme", "titluOriginal": "Universul operei eminesciene. Marile teme", "sursa": "manual, p. 138", "lectia": 4, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.3", "3.1"]}, {"id": "u4:5", "fel": "lecție", "titlu": "Formația poetului. Teme și motive eminesciene. Sinteză", "titluOriginal": "Formația poetului. Teme și motive eminesciene. Sinteză", "sursa": "manual, pp. 138–139", "lectia": 5, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.2", "2.1"]}]'::jsonb),
  ('11B','2026-2027',60,23,'luni','2027-03-08','8:00','lectie','Unitatea 4. Curente literare','„Epigonii”. Panorama valorilor și rechizitoriul prezentului - Concepția poetului despre poezie și misiunea poetului','[{"id": "u4:6", "fel": "lecție", "titlu": "„Epigonii”. Panorama valorilor și rechizitoriul prezentului", "titluOriginal": "„Epigonii”. Panorama valorilor și rechizitoriul prezentului", "sursa": "manual, pp. 140, 142–143", "lectia": 6, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "4.1"]}, {"id": "u4:7", "fel": "lecție", "titlu": "Concepția poetului despre poezie și misiunea poetului", "titluOriginal": "Concepția poetului despre poezie și misiunea poetului", "sursa": "manual, pp. 141, 143", "lectia": 7, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.2", "2.3", "1.4"]}]'::jsonb),
  ('11B','2026-2027',61,23,'miercuri','2027-03-10','12:15','lectie','Unitatea 4. Curente literare','„Luceafărul”. Geneza și lirica rolurilor','[{"id": "u4:8", "fel": "lecție", "titlu": "„Luceafărul”. Geneza și lirica rolurilor", "titluOriginal": "„Luceafărul”. Geneza și lirica rolurilor", "sursa": "manual, pp. 144–146", "lectia": 8, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.3", "2.2"]}]'::jsonb),
  ('11B','2026-2027',62,23,'vineri','2027-03-12','12:15','lectie','Unitatea 4. Curente literare','„Luceafărul”. Tema romantică a geniului. Vocile poemului','[{"id": "u4:9", "fel": "lecție", "titlu": "„Luceafărul”. Tema romantică a geniului. Vocile poemului", "titluOriginal": "„Luceafărul”. Tema romantică a geniului. Vocile poemului", "sursa": "manual, pp. 146–147", "lectia": 9, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.2", "2.3", "4.1"]}]'::jsonb),
  ('11B','2026-2027',63,24,'luni','2027-03-15','8:00','bloc propriu','Unitatea 4. Curente literare','Interpretarea textului „Luceafărul”','[{"id": "m:19", "fel": "bloc propriu", "tip": "altul", "titlu": "Interpretarea textului „Luceafărul”"}]'::jsonb),
  ('11B','2026-2027',64,24,'miercuri','2027-03-17','12:15','bloc propriu','Unitatea 4. Curente literare','„Luceafărul”. Considerații critice','[{"id": "m:20", "fel": "bloc propriu", "tip": "altul", "titlu": "„Luceafărul”. Considerații critice"}]'::jsonb),
  ('11B','2026-2027',65,24,'vineri','2027-03-19','12:15','lectie','Unitatea 4. Curente literare','„Floare albastră”. Cele două lumi','[{"id": "u4:10", "fel": "lecție", "titlu": "„Floare albastră”. Cele două lumi", "titluOriginal": "„Floare albastră”. Cele două lumi", "sursa": "manual, pp. 148–150", "lectia": 10, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "3.3"]}]'::jsonb),
  ('11B','2026-2027',66,25,'luni','2027-03-22','8:00','lectie','Unitatea 4. Curente literare','Stil și limbaj în „Floare albastră”. „Peste vârfuri”','[{"id": "u4:11", "fel": "lecție", "titlu": "Stil și limbaj în „Floare albastră”. „Peste vârfuri”", "titluOriginal": "Stil și limbaj în „Floare albastră”. „Peste vârfuri”. Evaluarea unității", "sursa": "manual, pp. 150–153", "lectia": 11, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["1.4", "2.1", "2.3"]}]'::jsonb),
  ('11B','2026-2027',67,25,'miercuri','2027-03-24','12:15','bloc propriu','Unitatea 4. Curente literare','Interpretare','[{"id": "m:21", "fel": "bloc propriu", "tip": "altul", "titlu": "Interpretare"}]'::jsonb),
  ('11B','2026-2027',68,25,'vineri','2027-03-26','12:15','bloc propriu','Unitatea 4. Curente literare','Interpretare','[{"id": "m:22", "fel": "bloc propriu", "tip": "altul", "titlu": "Interpretare"}]'::jsonb),
  ('11B','2026-2027',69,26,'luni','2027-03-29','8:00','lectie','Unitatea 4. Curente literare','Realismul. De la mimesis la curentul literar - Realism și romantism. Precursorii și școala realistă','[{"id": "u4:12", "fel": "lecție", "titlu": "Realismul. De la mimesis la curentul literar", "titluOriginal": "Realismul. De la mimesis la curentul literar", "sursa": "manual, pp. 154–155", "lectia": 12, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.3", "1.1"]}, {"id": "u4:13", "fel": "lecție", "titlu": "Realism și romantism. Precursorii și școala realistă", "titluOriginal": "Realism și romantism. Precursorii și școala realistă", "sursa": "manual, pp. 155–156", "lectia": 13, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.3", "3.4"]}]'::jsonb),
  ('11B','2026-2027',70,26,'miercuri','2027-03-31','12:15','lectie','Unitatea 4. Curente literare','Retorica realismului. Romanul, banii, perspectiva, personajul - Realismul în literaturile naționale și în literatura română','[{"id": "u4:15", "fel": "lecție", "titlu": "Retorica realismului. Romanul, banii, perspectiva, personajul", "titluOriginal": "Retorica realismului. Romanul, banii, perspectiva, personajul", "sursa": "manual, pp. 157–158", "lectia": 15, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.2", "4.1"]}, {"id": "u4:16", "fel": "lecție", "titlu": "Realismul în literaturile naționale și în literatura română", "titluOriginal": "Realismul în literaturile naționale și în literatura română", "sursa": "manual, pp. 158–160", "lectia": 16, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.2", "2.2"]}]'::jsonb),
  ('11B','2026-2027',71,26,'vineri','2027-04-02','12:15','lectie','Unitatea 4. Curente literare','Curentele literare. Sinteză','[{"id": "u4:17", "fel": "lecție", "titlu": "Curentele literare. Sinteză", "titluOriginal": "Curentele literare. Sinteză", "sursa": "manual, p. 161", "lectia": 17, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.2", "4.1", "1.4"]}]'::jsonb),
  ('11B','2026-2027',72,28,'luni','2027-04-12','8:00','lectie','Unitatea 4. Curente literare','Realism și naturalism. Caragiale, „În vreme de război”','[{"id": "u4:18", "fel": "lecție", "titlu": "Realism și naturalism. Caragiale, „În vreme de război”", "titluOriginal": "Realism și naturalism. Caragiale, „În vreme de război”", "sursa": "manual, pp. 162–164", "lectia": 18, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "4.1"]}]'::jsonb),
  ('11B','2026-2027',73,28,'miercuri','2027-04-14','12:15','lectie','Unitatea 4. Curente literare','„În vreme de război”. Cazul de conștiință și structura narativă - Relația autor–narator','[{"id": "u4:19", "fel": "lecție", "titlu": "„În vreme de război”. Cazul de conștiință și structura narativă", "titluOriginal": "„În vreme de război”. Cazul de conștiință și structura narativă", "sursa": "manual, pp. 164–165", "lectia": 19, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.3", "4.1", "1.4"]}, {"id": "u4:20", "fel": "lecție", "titlu": "Relația autor–narator", "titluOriginal": "Relația autor–narator", "sursa": "manual, p. 166", "lectia": 20, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "2.1", "1.4"]}]'::jsonb),
  ('11B','2026-2027',74,28,'vineri','2027-04-16','12:15','lectie','Unitatea 4. Curente literare','Stilul indirect. Stilul indirect liber - Dialogul și monologul interior','[{"id": "u4:21", "fel": "lecție", "titlu": "Stilul indirect. Stilul indirect liber", "titluOriginal": "Stilul indirect. Stilul indirect liber", "sursa": "manual, p. 167", "lectia": 21, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "2.1"]}, {"id": "u4:22", "fel": "lecție", "titlu": "Dialogul și monologul interior", "titluOriginal": "Dialogul și monologul interior", "sursa": "manual, p. 168", "lectia": 22, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "1.3", "1.4"]}]'::jsonb),
  ('11B','2026-2027',75,29,'luni','2027-04-19','8:00','lectie','Unitatea 4. Curente literare','Argumentul și argumentarea','[{"id": "u4:23", "fel": "lecție", "titlu": "Argumentul și argumentarea", "titluOriginal": "Argumentul și argumentarea", "sursa": "manual, p. 169", "lectia": 23, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["4.1", "1.4", "1.3"]}]'::jsonb),
  ('11B','2026-2027',76,29,'miercuri','2027-04-21','12:15','lectie','Unitatea 4. Curente literare','Simbolismul. Conștiința estetică modernă. Simbolismul românesc - Estetica simbolismului. Gândirea analogică, sinestezia, simbolul - Sugestia, muzicalitatea, versul liber. Tematica simbolistă','[{"id": "u4:25", "fel": "lecție", "titlu": "Simbolismul. Conștiința estetică modernă. Simbolismul românesc", "titluOriginal": "Simbolismul. Conștiința estetică modernă. Simbolismul românesc", "sursa": "manual, pp. 171–172", "lectia": 25, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.1", "3.2", "3.3"]}, {"id": "u4:26", "fel": "lecție", "titlu": "Estetica simbolismului. Gândirea analogică, sinestezia, simbolul", "titluOriginal": "Estetica simbolismului. Gândirea analogică, sinestezia, simbolul", "sursa": "manual, pp. 172–173", "lectia": 26, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.3", "1.1"]}, {"id": "u4:27", "fel": "lecție", "titlu": "Sugestia, muzicalitatea, versul liber. Tematica simbolistă", "titluOriginal": "Sugestia, muzicalitatea, versul liber. Tematica simbolistă", "sursa": "manual, pp. 173–174", "lectia": 27, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "3.4"]}]'::jsonb),
  ('11B','2026-2027',77,29,'vineri','2027-04-23','12:15','lectie','Unitatea 4. Curente literare','Ștefan Petică, „Când viorile tăcură” - Ion Minulescu, „Romanța celor trei corăbii”','[{"id": "u4:28", "fel": "lecție", "titlu": "Ștefan Petică, „Când viorile tăcură”", "titluOriginal": "Ștefan Petică, „Când viorile tăcură”", "sursa": "manual, pp. 175–176", "lectia": 28, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.3", "1.3"]}, {"id": "u4:29", "fel": "lecție", "titlu": "Ion Minulescu, „Romanța celor trei corăbii”", "titluOriginal": "Ion Minulescu, „Romanța celor trei corăbii”", "sursa": "manual, pp. 177–178", "lectia": 29, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "1.3"]}]'::jsonb),
  ('11B','2026-2027',78,30,'miercuri','2027-05-05','12:15','bloc propriu','Unitatea 4. Curente literare','Recapitulare','[{"id": "m:24", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',79,30,'vineri','2027-05-07','12:15','bloc propriu','Unitatea 4. Curente literare','Recapitulare','[{"id": "m:25", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',80,31,'luni','2027-05-10','8:00','bloc propriu','Unitatea 4. Curente literare','Teză','[{"id": "m:23", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('11B','2026-2027',81,31,'miercuri','2027-05-12','12:15','lectie','Unitatea 4. Curente literare','Simbolismul european. Configurarea conceptului - Primatul imaginației. Baudelaire - Imaginea poetului pur. Mallarmé - Tentația absolutului. Rimbaud și lirismul post-baudelairian','[{"id": "u4:30", "fel": "lecție", "titlu": "Simbolismul european. Configurarea conceptului", "titluOriginal": "Simbolismul european. Configurarea conceptului", "sursa": "manual, pp. 179–180", "lectia": 30, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.3", "3.1", "3.4"]}, {"id": "u4:31", "fel": "lecție", "titlu": "Primatul imaginației. Baudelaire", "titluOriginal": "Primatul imaginației. Baudelaire", "sursa": "manual, p. 181", "lectia": 31, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.3", "2.2"]}, {"id": "u4:32", "fel": "lecție", "titlu": "Imaginea poetului pur. Mallarmé", "titluOriginal": "Imaginea poetului pur. Mallarmé", "sursa": "manual, pp. 182–183", "lectia": 32, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.2", "2.3", "1.4"]}, {"id": "u4:33", "fel": "lecție", "titlu": "Tentația absolutului. Rimbaud și lirismul post-baudelairian", "titluOriginal": "Tentația absolutului. Rimbaud și lirismul post-baudelairian", "sursa": "manual, pp. 184–185", "lectia": 33, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.3", "2.2"]}]'::jsonb),
  ('11B','2026-2027',82,31,'vineri','2027-05-14','12:15','lectie','Unitatea 4. Curente literare','Poezia erosului rural. Coșbuc, „Numai una!” - Idila coșbuciană. Lirismul obiectiv și versificația','[{"id": "u4:34", "fel": "lecție", "titlu": "Poezia erosului rural. Coșbuc, „Numai una!”", "titluOriginal": "Poezia erosului rural. Coșbuc, „Numai una!”", "sursa": "manual, pp. 186–187", "lectia": 34, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.1", "2.3"]}, {"id": "u4:35", "fel": "lecție", "titlu": "Idila coșbuciană. Lirismul obiectiv și versificația", "titluOriginal": "Idila coșbuciană. Lirismul obiectiv și versificația", "sursa": "manual, pp. 188–190", "lectia": 35, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "4.2"]}]'::jsonb),
  ('11B','2026-2027',83,32,'luni','2027-05-17','8:00','lectie','Unitatea 4. Curente literare','Studiu pe text: floarea albastră, de la Novalis la Eminescu - Stilul și calitățile lui generale (III). Proprietatea','[{"id": "u4:37", "fel": "lecție", "titlu": "Studiu pe text: floarea albastră, de la Novalis la Eminescu", "titluOriginal": "Studiu pe text: floarea albastră, de la Novalis la Eminescu", "sursa": "manual, pp. 148–151; aprofundare", "lectia": 37, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["3.3", "2.2", "2.3"]}, {"id": "u4:36", "fel": "lecție", "titlu": "Stilul și calitățile lui generale (III). Proprietatea", "titluOriginal": "Stilul și calitățile lui generale (III). Proprietatea", "sursa": "manual, pp. 191–192", "lectia": 36, "unitate": "Unitatea 4. Curente literare", "unitateId": "p4", "competenteSpecifice": ["1.1", "1.2", "1.4"]}]'::jsonb),
  ('11B','2026-2027',84,32,'miercuri','2027-05-19','12:15','bloc propriu','Unitatea 4. Curente literare','Recapitulare','[{"id": "m:26", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',85,32,'vineri','2027-05-21','12:15','bloc propriu','Unitatea 4. Curente literare','Evaluare','[{"id": "m:27", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('11B','2026-2027',86,33,'luni','2027-05-24','8:00','lectie','Unitatea 4. Curente literare','Orientări tematice în romanul interbelic. Harta unui deceniu și jumătate - Între subiectiv și obiectiv. Ibrăileanu, Lovinescu și modelul Proust','[{"id": "u5:1", "fel": "lecție", "titlu": "Orientări tematice în romanul interbelic. Harta unui deceniu și jumătate", "titluOriginal": "Orientări tematice în romanul interbelic. Harta unui deceniu și jumătate", "sursa": "manual, p. 193", "lectia": 1, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["3.1", "3.2", "2.1"]}, {"id": "u5:2", "fel": "lecție", "titlu": "Între subiectiv și obiectiv. Ibrăileanu, Lovinescu și modelul Proust", "titluOriginal": "Între subiectiv și obiectiv. Ibrăileanu, Lovinescu și modelul Proust", "sursa": "manual, pp. 193–194", "lectia": 2, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["3.1", "2.2", "1.2"]}]'::jsonb),
  ('11B','2026-2027',87,33,'miercuri','2027-05-26','12:15','lectie','Unitatea 5. Interbelic','Mircea Eliade. Profil spiritual, experiența Indiei, romanul experienței','[{"id": "u5:6", "fel": "lecție", "titlu": "Mircea Eliade. Profil spiritual, experiența Indiei, romanul experienței", "titluOriginal": "Mircea Eliade. Profil spiritual, experiența Indiei, romanul experienței", "sursa": "manual, pp. 198, 200", "lectia": 6, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["3.1", "3.3", "1.4"]}]'::jsonb),
  ('11B','2026-2027',88,33,'vineri','2027-05-28','12:15','lectie','Unitatea 5. Interbelic','„Maitreyi”, un roman non-fictiv. Autenticitate, erotism, exotism - Structura compozițională și labirintul dragostei','[{"id": "u5:7", "fel": "lecție", "titlu": "„Maitreyi”, un roman non-fictiv. Autenticitate, erotism, exotism", "titluOriginal": "„Maitreyi”, un roman non-fictiv. Autenticitate, erotism, exotism", "sursa": "manual, pp. 198–201", "lectia": 7, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.2", "3.4"]}, {"id": "u5:8", "fel": "lecție", "titlu": "Structura compozițională și labirintul dragostei", "titluOriginal": "Structura compozițională și labirintul dragostei", "sursa": "manual, pp. 202–203", "lectia": 8, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["2.1", "1.1", "1.4"]}]'::jsonb),
  ('11B','2026-2027',89,34,'luni','2027-05-31','8:00','lectie','Unitatea 5. Interbelic','Semnificația mitologică a iubirii. Replica Maitreyiei Devi - Stilul și calitățile lui generale (IV). Concizia','[{"id": "u5:9", "fel": "lecție", "titlu": "Semnificația mitologică a iubirii. Replica Maitreyiei Devi", "titluOriginal": "Semnificația mitologică a iubirii. Replica Maitreyiei Devi", "sursa": "manual, pp. 203–204", "lectia": 9, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["2.3", "3.3", "4.1"]}, {"id": "u5:11", "fel": "lecție", "titlu": "Stilul și calitățile lui generale (IV). Concizia", "titluOriginal": "Stilul și calitățile lui generale (IV). Concizia", "sursa": "manual, pp. 208–210", "lectia": 11, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["1.1", "1.2", "1.4"]}]'::jsonb),
  ('11B','2026-2027',90,34,'miercuri','2027-06-02','12:15','lectie','Unitatea 5. Interbelic','Modele epice în romanul interbelic. Cele șapte direcții - Polemici critice: Camil Petrescu și G. Călinescu despre roman','[{"id": "u5:12", "fel": "lecție", "titlu": "Modele epice în romanul interbelic. Cele șapte direcții", "titluOriginal": "Modele epice în romanul interbelic. Cele șapte direcții", "sursa": "manual, p. 211", "lectia": 12, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["3.1", "3.2", "2.2"]}, {"id": "u5:13", "fel": "lecție", "titlu": "Polemici critice: Camil Petrescu și G. Călinescu despre roman", "titluOriginal": "Polemici critice: Camil Petrescu și G. Călinescu despre roman", "sursa": "manual, pp. 212–213", "lectia": 13, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["4.1", "4.2", "3.1"]}]'::jsonb),
  ('11B','2026-2027',91,34,'vineri','2027-06-04','12:15','lectie','Unitatea 5. Interbelic','Studiu comparat: romanul doric și romanul ionic','[{"id": "u5:18", "fel": "lecție", "titlu": "Studiu comparat: romanul doric și romanul ionic", "titluOriginal": "Studiu comparat: romanul doric și romanul ionic", "sursa": "manual, pp. 211, 214; aprofundare", "lectia": 18, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["2.2", "3.2", "4.2"]}]'::jsonb),
  ('11B','2026-2027',92,35,'luni','2027-06-07','8:00','lectie','Unitatea 5. Interbelic','Sinteză: modernitatea romanului românesc interbelic','[{"id": "u5:19", "fel": "lecție", "titlu": "Sinteză: modernitatea romanului românesc interbelic", "titluOriginal": "Sinteză: modernitatea romanului românesc interbelic", "sursa": "manual, pp. 193–215; aprofundare", "lectia": 19, "unitate": "Unitatea 5. Interbelic", "unitateId": "p5", "competenteSpecifice": ["3.2", "4.1", "1.4"]}]'::jsonb),
  ('11B','2026-2027',93,35,'miercuri','2027-06-09','12:15','bloc propriu','Unitatea 5. Interbelic','Recapitulare','[{"id": "m:28", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',94,35,'vineri','2027-06-11','12:15','bloc propriu','Unitatea 5. Interbelic','Evaluare','[{"id": "m:29", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('11B','2026-2027',95,36,'luni','2027-06-14','8:00','bloc propriu','Recapitulare finală','Recapitulare','[{"id": "m:30", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',96,36,'miercuri','2027-06-16','12:15','bloc propriu','Recapitulare finală','Recapitulare','[{"id": "m:31", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11B','2026-2027',97,36,'vineri','2027-06-18','12:15','bloc propriu','Recapitulare finală','Recapitulare','[{"id": "m:32", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb);

-- ---------- paza pe clasa asta ----------
do $$
declare n int; lipsa int;
begin
  select count(*) into n from public.school_plan where clasa = '11B' and an_scolar = '2026-2027';
  if n <> 97 then
    raise exception 'Clasa 11B are % ore, așteptam 97. Lipirea s-a rupt.', n;
  end if;
  select count(*) into lipsa from generate_series(1, 97) g
   where not exists (select 1 from public.school_plan p
                      where p.clasa = '11B' and p.an_scolar = '2026-2027' and p.nr = g);
  if lipsa > 0 then
    raise exception 'Clasei 11B îi lipsesc % numere din șirul 1..97.', lipsa;
  end if;
  raise notice 'Clasa 11B: 97 de ore, la locul lor.';
end $$;
