-- =========================================================
-- 0097d · LICEU: planificarea clasei 11C, pe orarul din 21 septembrie
--
-- Una din cinci. Se rulează în ordine: 0097a, 0097b, 0097c, 0097d, 0097e.
-- Ultima ține paza pe toate cinci deodată.
--
-- DE CE CINCI FIȘIERE, NU UNUL. Întregul făcea 297 KB, iar SQL Editor îl
-- refuză: „request entity too large". Pe clasă iese vreo 53 KB și intră.
--
-- Punctul de pornire e `Diverse/ORAR 21 SEPT/Planificatoare/`, exportul din
-- planificatorul lui Marius. El e adevărul; documentele Word se nasc din el.
--
-- CE SE SCHIMBĂ, la toate cinci (comparat amprentă cu amprentă, nu din ochi):
--   · 9B și 11D — neschimbate. Intră totuși, ca regula să n-aibă excepții de
--     ținut minte, iar ce iese e la fel cu ce era.
--   · 11C și 11D — își mută ora de vineri, de pe 21 sept. încolo (11C de la
--     11:25 la 10:35, 11D de la 10:35 la 11:25).
--   · 10D — recapitularea inițială scade de la 4 ore la 3, „Unitatea 1. Basmul
--     cult" începe la ora 4 în loc de 5, iar cele două lecții care stăteau
--     împreună la ora 6 se despart în orele 5 și 6.
--   · 11B — se schimbă unitățile 2 și 3 (orele 21–56). Primele 20 rămân.
--   · 11C — plan nou din temelii: are acum exact planul lui 11D.
--
-- 12C ȘI 12D NU SE ATING: ele merg pe planificarea de bacalaureat (0093).
--
-- ZIUA SE SCRIE FĂRĂ DIACRITICE („marti"), ca în orar: îmbinarea dintre
-- planificare și orar se face pe ea, iar o literă deosebită ar fi rupt-o în
-- tăcere.
--
-- `blocuri` SE ȚINE CIUNTIT: rămân numele, sursa, unitatea și competențele; se
-- lasă afară `notiuni`, `activitati` și `ideeaDeRetinut` — materialul de predare,
-- nouă zecimi din greutate, pe care modulul nu-l citește nicăieri. El rămâne
-- întreg în JSON-urile din `Diverse/ORAR 21 SEPT/`.
--
-- SE ȘTERGE ȘI SE SCRIE LA LOC. Un `update` rând cu rând ar fi lăsat în urmă
-- orele care nu mai există, iar cheia unică (clasă, an, dată, ceas) s-ar fi
-- lovit de ele la 11C și 11D, unde ceasul se mută.
-- =========================================================

delete from public.school_plan where clasa = '11C' and an_scolar = '2026-2027';

insert into public.school_plan
  (clasa, an_scolar, nr, saptamana, zi, data, ora, fel, unitatea, titlu, blocuri) values
  ('11C','2026-2027',1,1,'miercuri','2026-09-09','11:25','lectie','Unitatea 1. Recapitulare','Prezentarea manualului, a programei și a bibliografiei','[{"id": "u1:1", "fel": "lecție", "titlu": "Prezentarea manualului, a programei și a bibliografiei", "titluOriginal": "Prezentarea manualului, a programei și a bibliografiei", "sursa": "manual, Argument, p. 5", "lectia": 1, "unitate": "Unitatea 1. Recapitulare", "unitateId": "p1", "competenteSpecifice": ["1.3", "3.2"]}]'::jsonb),
  ('11C','2026-2027',2,1,'vineri','2026-09-11','9:45','lectie','Unitatea 1. Recapitulare','Recapitulare: genul epic – concepte operaționale','[{"id": "u1:2", "fel": "lecție", "titlu": "Recapitulare: genul epic – concepte operaționale", "titluOriginal": "Recapitulare: genul epic – concepte operaționale", "sursa": "achiziții din clasele a IX-a și a X-a", "lectia": 2, "unitate": "Unitatea 1. Recapitulare", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',3,1,'vineri','2026-09-11','11:25','lectie','Unitatea 1. Recapitulare','Recapitulare: genul liric și genul dramatic – concepte operaționale','[{"id": "u1:3", "fel": "lecție", "titlu": "Recapitulare: genul liric și genul dramatic – concepte operaționale", "titluOriginal": "Recapitulare: genul liric și genul dramatic – concepte operaționale", "sursa": "achiziții din clasele a IX-a și a X-a", "lectia": 3, "unitate": "Unitatea 1. Recapitulare", "unitateId": "p1", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',4,2,'miercuri','2026-09-16','11:25','lectie','Unitatea 2. Fundamente ale culturii române','Originile și evoluția limbii române (I). Substrat, strat, adstrat','[{"id": "u2:1", "fel": "lecție", "titlu": "Originile și evoluția limbii române (I). Substrat, strat, adstrat", "titluOriginal": "Originile și evoluția limbii române (I). Substrat, strat, adstrat", "sursa": "manual, pp. 7–12", "lectia": 1, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["1.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',5,2,'vineri','2026-09-18','9:45','bloc propriu','Unitatea 2. Fundamente ale culturii române','Influențele lingvistice','[{"id": "m:14", "fel": "bloc propriu", "tip": "altul", "titlu": "Influențele lingvistice"}]'::jsonb),
  ('11C','2026-2027',6,2,'vineri','2026-09-18','11:25','bloc propriu','Unitatea 2. Fundamente ale culturii române','Fondul latin al limbii române','[{"id": "m:13", "fel": "bloc propriu", "tip": "altul", "titlu": "Fondul latin al limbii române"}]'::jsonb),
  ('11C','2026-2027',7,3,'miercuri','2026-09-23','11:25','lectie','Unitatea 2. Fundamente ale culturii române','Originile și evoluția limbii române (II). Primele atestări și primele texte','[{"id": "u2:2", "fel": "lecție", "titlu": "Originile și evoluția limbii române (II). Primele atestări și primele texte", "titluOriginal": "Originile și evoluția limbii române (II). Primele atestări și primele texte", "sursa": "manual, pp. 7–12", "lectia": 2, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["1.1", "2.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',8,3,'vineri','2026-09-25','9:45','lectie','Unitatea 2. Fundamente ale culturii române','Latinitate și dacism (I). Termenii dezbaterii','[{"id": "u2:5", "fel": "lecție", "titlu": "Latinitate și dacism (I). Termenii dezbaterii", "titluOriginal": "Latinitate și dacism (I). Termenii dezbaterii", "sursa": "manual, pp. 15–20", "lectia": 5, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["2.2", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',9,3,'vineri','2026-09-25','10:35','lectie','Unitatea 2. Fundamente ale culturii române','Latinitate și dacism (II). Linia latinistă - Latinitate și dacism (III). Linia dacistă','[{"id": "u2:6", "fel": "lecție", "titlu": "Latinitate și dacism (II). Linia latinistă", "titluOriginal": "Latinitate și dacism (II). Linia latinistă", "sursa": "manual, pp. 15–20; texte de epocă", "lectia": 6, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["2.1", "3.1", "3.2"]}, {"id": "u2:7", "fel": "lecție", "titlu": "Latinitate și dacism (III). Linia dacistă", "titluOriginal": "Latinitate și dacism (III). Linia dacistă", "sursa": "manual, pp. 15–20; texte de epocă", "lectia": 7, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["2.2", "3.1", "3.3"]}]'::jsonb),
  ('11C','2026-2027',10,4,'miercuri','2026-09-30','11:25','lectie','Unitatea 2. Fundamente ale culturii române','Latinitate și dacism (IV). Prezentarea proiectelor și dezbatere','[{"id": "u2:8", "fel": "lecție", "titlu": "Latinitate și dacism (IV). Prezentarea proiectelor și dezbatere", "titluOriginal": "Latinitate și dacism (IV). Prezentarea proiectelor și dezbatere", "sursa": "lucrul grupelor", "lectia": 8, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["1.3", "4.1", "4.2"]}]'::jsonb),
  ('11C','2026-2027',11,4,'vineri','2026-10-02','9:45','lectie','Unitatea 2. Fundamente ale culturii române','Aplicații: eseul argumentativ pe tema identității culturale','[{"id": "u2:9", "fel": "lecție", "titlu": "Aplicații: eseul argumentativ pe tema identității culturale", "titluOriginal": "Aplicații: eseul argumentativ pe tema identității culturale", "sursa": "programa, domeniul limbă și comunicare", "lectia": 9, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["1.4", "4.1"]}]'::jsonb),
  ('11C','2026-2027',12,4,'vineri','2026-10-02','10:35','lectie','Unitatea 2. Fundamente ale culturii române','Limbă și comunicare: noile norme lingvistice conform DOOM (I). Ortografie - Limbă și comunicare: noile norme lingvistice conform DOOM (II). Ortoepie și morfologie','[{"id": "u2:3", "fel": "lecție", "titlu": "Limbă și comunicare: noile norme lingvistice conform DOOM (I). Ortografie", "titluOriginal": "Limbă și comunicare: noile norme lingvistice conform DOOM (I). Ortografie", "sursa": "manual, pp. 13–14", "lectia": 3, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["1.2", "4.1"]}, {"id": "u2:4", "fel": "lecție", "titlu": "Limbă și comunicare: noile norme lingvistice conform DOOM (II). Ortoepie și morfologie", "titluOriginal": "Limbă și comunicare: noile norme lingvistice conform DOOM (II). Ortoepie și morfologie", "sursa": "manual, pp. 13–14", "lectia": 4, "unitate": "Unitatea 2. Fundamente ale culturii române", "unitateId": "p2", "competenteSpecifice": ["1.2", "4.1"]}]'::jsonb),
  ('11C','2026-2027',13,5,'miercuri','2026-10-07','11:25','lectie','Unitatea 3. Perioada veche','Perioada veche – repere. Cultura scrisă în spațiul românesc - Studiu de caz 2: Dimensiunea religioasă a existenței (I). Cartea sfântă în limba română - Studiu de caz 2 (II). Cazania lui Varlaam. Didahiile lui Antim Ivireanul - Literatura și pictura religioasă','[{"id": "u3:1", "fel": "lecție", "titlu": "Perioada veche – repere. Cultura scrisă în spațiul românesc", "titluOriginal": "Perioada veche – repere. Cultura scrisă în spațiul românesc", "sursa": "manual, pp. 21–30; N. Cartojan, „Istoria literaturii române vechi”", "lectia": 1, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.1", "3.2"]}, {"id": "u3:2", "fel": "lecție", "titlu": "Studiu de caz 2: Dimensiunea religioasă a existenței (I). Cartea sfântă în limba română", "titluOriginal": "Studiu de caz 2: Dimensiunea religioasă a existenței (I). Cartea sfântă în limba română", "sursa": "manual, pp. 21–25", "lectia": 2, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.2", "3.2"]}, {"id": "u3:3", "fel": "lecție", "titlu": "Studiu de caz 2 (II). Cazania lui Varlaam. Didahiile lui Antim Ivireanul", "titluOriginal": "Studiu de caz 2 (II). Cazania lui Varlaam. Didahiile lui Antim Ivireanul", "sursa": "manual, pp. 21–25", "lectia": 3, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["1.3", "2.1", "4.1"]}, {"id": "u3:5", "fel": "lecție", "titlu": "Literatura și pictura religioasă", "titluOriginal": "Literatura și pictura religioasă", "sursa": "manual, pp. 29–30", "lectia": 5, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.2", "3.3"]}]'::jsonb),
  ('11C','2026-2027',14,5,'vineri','2026-10-09','9:45','lectie','Unitatea 3. Perioada veche','Studiu de caz 3: Formarea conștiinței istorice (I). Cronicarii moldoveni','[{"id": "u3:6", "fel": "lecție", "titlu": "Studiu de caz 3: Formarea conștiinței istorice (I). Cronicarii moldoveni", "titluOriginal": "Studiu de caz 3: Formarea conștiinței istorice (I). Cronicarii moldoveni", "sursa": "manual, pp. 31–38", "lectia": 6, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.2", "3.2"]}]'::jsonb),
  ('11C','2026-2027',15,5,'vineri','2026-10-09','10:35','lectie','Unitatea 3. Perioada veche','Studiu de caz 3 (II). Cronicarii munteni. Dimitrie Cantemir - Limbă și comunicare: norma literară – aspecte evolutive','[{"id": "u3:7", "fel": "lecție", "titlu": "Studiu de caz 3 (II). Cronicarii munteni. Dimitrie Cantemir", "titluOriginal": "Studiu de caz 3 (II). Cronicarii munteni. Dimitrie Cantemir", "sursa": "manual, pp. 31–38", "lectia": 7, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.1", "4.2"]}, {"id": "u3:9", "fel": "lecție", "titlu": "Limbă și comunicare: norma literară – aspecte evolutive", "titluOriginal": "Limbă și comunicare: norma literară – aspecte evolutive", "sursa": "manual, pp. 47–50", "lectia": 9, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["1.2", "3.1"]}]'::jsonb),
  ('11C','2026-2027',16,7,'miercuri','2026-10-21','11:25','lectie','Unitatea 3. Perioada veche','Umanismul (prezentare sintetică) - Iluminismul și Școala Ardeleană (prezentare sintetică)','[{"id": "u3:10", "fel": "lecție", "titlu": "Umanismul (prezentare sintetică)", "titluOriginal": "Umanismul (prezentare sintetică)", "sursa": "manual, pp. 51–54", "lectia": 10, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "2.2", "3.1"]}, {"id": "u3:11", "fel": "lecție", "titlu": "Iluminismul și Școala Ardeleană (prezentare sintetică)", "titluOriginal": "Iluminismul și Școala Ardeleană (prezentare sintetică)", "sursa": "manual, pp. 51–54", "lectia": 11, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',17,7,'vineri','2026-10-23','9:45','lectie','Unitatea 3. Perioada veche','Recapitulare: fundamente și perioada veche','[{"id": "u3:12", "fel": "lecție", "titlu": "Recapitulare: fundamente și perioada veche", "titluOriginal": "Recapitulare: fundamente și perioada veche", "sursa": "recapitulare", "lectia": 12, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["2.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',18,7,'vineri','2026-10-23','10:35','lectie','Unitatea 3. Perioada veche','Evaluare: fundamente și perioada veche','[{"id": "u3:13", "fel": "lecție", "titlu": "Evaluare: fundamente și perioada veche", "titluOriginal": "Evaluare: fundamente și perioada veche", "sursa": "test sumativ", "lectia": 13, "unitate": "Unitatea 3. Perioada veche", "unitateId": "p3", "competenteSpecifice": ["1.2", "2.1", "4.1"]}]'::jsonb),
  ('11C','2026-2027',19,8,'miercuri','2026-11-04','11:25','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Studiu de caz 4: Rolul literaturii în perioada pașoptistă (I). Contextul - Studiu de caz 4 (II). Articolele programatice - Forme hibride ale civilizației românești la mijlocul secolului al XIX-lea','[{"id": "u4:1", "fel": "lecție", "titlu": "Studiu de caz 4: Rolul literaturii în perioada pașoptistă (I). Contextul", "titluOriginal": "Studiu de caz 4: Rolul literaturii în perioada pașoptistă (I). Contextul", "sursa": "manual, pp. 55–60", "lectia": 1, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.1", "3.2"]}, {"id": "u4:2", "fel": "lecție", "titlu": "Studiu de caz 4 (II). Articolele programatice", "titluOriginal": "Studiu de caz 4 (II). Articolele programatice", "sursa": "manual, pp. 55–60", "lectia": 2, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.3", "2.1", "4.1"]}, {"id": "u4:4", "fel": "lecție", "titlu": "Forme hibride ale civilizației românești la mijlocul secolului al XIX-lea", "titluOriginal": "Forme hibride ale civilizației românești la mijlocul secolului al XIX-lea", "sursa": "manual, pp. 61–68", "lectia": 4, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "3.1"]}]'::jsonb),
  ('11C','2026-2027',20,8,'vineri','2026-11-06','9:45','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','„Chirița în provinție” de Vasile Alecsandri (I). Autorul, specia, contextul','[{"id": "u4:5", "fel": "lecție", "titlu": "„Chirița în provinție” de Vasile Alecsandri (I). Autorul, specia, contextul", "titluOriginal": "„Chirița în provinție” de Vasile Alecsandri (I). Autorul, specia, contextul", "sursa": "manual, pp. 61–68", "lectia": 5, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.1"]}]'::jsonb),
  ('11C','2026-2027',21,8,'vineri','2026-11-06','10:35','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','„Chirița în provinție” (II). Temă, structură, conflict - „Chirița în provinție” (III). Personajul Chirița. Tipologia parvenitului','[{"id": "u4:6", "fel": "lecție", "titlu": "„Chirița în provinție” (II). Temă, structură, conflict", "titluOriginal": "„Chirița în provinție” (II). Temă, structură, conflict", "sursa": "manual, pp. 61–68", "lectia": 6, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.3"]}, {"id": "u4:7", "fel": "lecție", "titlu": "„Chirița în provinție” (III). Personajul Chirița. Tipologia parvenitului", "titluOriginal": "„Chirița în provinție” (III). Personajul Chirița. Tipologia parvenitului", "sursa": "manual, pp. 61–68", "lectia": 7, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',22,9,'miercuri','2026-11-11','11:25','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','„Chirița în provinție” (IV). Limbajul și sursele comicului - Limbă și comunicare: uzul diversificat al limbii literare. Registre stilistice - Limbă și comunicare: variante literare libere','[{"id": "u4:8", "fel": "lecție", "titlu": "„Chirița în provinție” (IV). Limbajul și sursele comicului", "titluOriginal": "„Chirița în provinție” (IV). Limbajul și sursele comicului", "sursa": "manual, pp. 61–68", "lectia": 8, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.2", "2.3"]}, {"id": "u4:9", "fel": "lecție", "titlu": "Limbă și comunicare: uzul diversificat al limbii literare. Registre stilistice", "titluOriginal": "Limbă și comunicare: uzul diversificat al limbii literare. Registre stilistice", "sursa": "manual, pp. 69–70", "lectia": 9, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.2", "1.3"]}, {"id": "u4:10", "fel": "lecție", "titlu": "Limbă și comunicare: variante literare libere", "titluOriginal": "Limbă și comunicare: variante literare libere", "sursa": "manual, pp. 71–74", "lectia": 10, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.2"]}]'::jsonb),
  ('11C','2026-2027',23,9,'vineri','2026-11-13','9:45','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Dezbatere: România, între Orient și Occident (I). Pregătirea','[{"id": "u4:11", "fel": "lecție", "titlu": "Dezbatere: România, între Orient și Occident (I). Pregătirea", "titluOriginal": "Dezbatere: România, între Orient și Occident (I). Pregătirea", "sursa": "manual, pp. 75–80", "lectia": 11, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.3", "3.4", "4.1"]}]'::jsonb),
  ('11C','2026-2027',24,9,'vineri','2026-11-13','10:35','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Dezbatere: România, între Orient și Occident (II). Desfășurarea','[{"id": "u4:12", "fel": "lecție", "titlu": "Dezbatere: România, între Orient și Occident (II). Desfășurarea", "titluOriginal": "Dezbatere: România, între Orient și Occident (II). Desfășurarea", "sursa": "manual, pp. 75–80", "lectia": 12, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["4.1", "4.2"]}]'::jsonb),
  ('11C','2026-2027',25,10,'miercuri','2026-11-18','11:25','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Descoperirea literaturii populare','[{"id": "u4:13", "fel": "lecție", "titlu": "Descoperirea literaturii populare", "titluOriginal": "Descoperirea literaturii populare", "sursa": "manual, pp. 81–83", "lectia": 13, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2", "3.2"]}]'::jsonb),
  ('11C','2026-2027',26,10,'vineri','2026-11-20','9:45','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','„Meșterul Manole” (baladă populară) (I). Specia, tema, structura','[{"id": "u4:14", "fel": "lecție", "titlu": "„Meșterul Manole” (baladă populară) (I). Specia, tema, structura", "titluOriginal": "„Meșterul Manole” (baladă populară) (I). Specia, tema, structura", "sursa": "manual, pp. 84–91", "lectia": 14, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "2.2"]}]'::jsonb),
  ('11C','2026-2027',27,10,'vineri','2026-11-20','10:35','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','„Meșterul Manole” (II). Personajele și semnificațiile mitului - Limbă și comunicare: structuri discursive – textul informativ','[{"id": "u4:15", "fel": "lecție", "titlu": "„Meșterul Manole” (II). Personajele și semnificațiile mitului", "titluOriginal": "„Meșterul Manole” (II). Personajele și semnificațiile mitului", "sursa": "manual, pp. 84–91", "lectia": 15, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.2", "2.3", "3.3"]}, {"id": "u4:16", "fel": "lecție", "titlu": "Limbă și comunicare: structuri discursive – textul informativ", "titluOriginal": "Limbă și comunicare: structuri discursive – textul informativ", "sursa": "manual, pp. 102–104", "lectia": 16, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.4", "4.1"]}]'::jsonb),
  ('11C','2026-2027',28,11,'miercuri','2026-11-25','11:25','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Studiu de caz 5: Criticismul junimist (I). Societatea și revista','[{"id": "u4:17", "fel": "lecție", "titlu": "Studiu de caz 5: Criticismul junimist (I). Societatea și revista", "titluOriginal": "Studiu de caz 5: Criticismul junimist (I). Societatea și revista", "sursa": "manual, pp. 105–111; Iacob Negruzzi, „Amintiri din Junimea”", "lectia": 17, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',29,11,'vineri','2026-11-27','9:45','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Studiu de caz 5 (II). Maiorescu și teoria formelor fără fond','[{"id": "u4:18", "fel": "lecție", "titlu": "Studiu de caz 5 (II). Maiorescu și teoria formelor fără fond", "titluOriginal": "Studiu de caz 5 (II). Maiorescu și teoria formelor fără fond", "sursa": "manual, pp. 105–111", "lectia": 18, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.3", "2.1", "4.2"]}]'::jsonb),
  ('11C','2026-2027',30,11,'vineri','2026-11-27','10:35','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Limbă și comunicare: eseul structurat și eseul liber – etapele redactării','[{"id": "u4:20", "fel": "lecție", "titlu": "Limbă și comunicare: eseul structurat și eseul liber – etapele redactării", "titluOriginal": "Limbă și comunicare: eseul structurat și eseul liber – etapele redactării", "sursa": "programa, domeniul limbă și comunicare; „Eseul”, Editura Art", "lectia": 20, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.4", "4.1"]}]'::jsonb),
  ('11C','2026-2027',31,12,'miercuri','2026-12-02','11:25','lectie','Unitatea 4. Perioada modernă: secolul al XIX-lea','Limbă și comunicare: strategii folosite în monolog și în dialog - Limbă și comunicare: adecvarea discursului oral la situații de comunicare diverse','[{"id": "u4:21", "fel": "lecție", "titlu": "Limbă și comunicare: strategii folosite în monolog și în dialog", "titluOriginal": "Limbă și comunicare: strategii folosite în monolog și în dialog", "sursa": "manual, p. 112", "lectia": 21, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.3", "4.1"]}, {"id": "u4:22", "fel": "lecție", "titlu": "Limbă și comunicare: adecvarea discursului oral la situații de comunicare diverse", "titluOriginal": "Limbă și comunicare: adecvarea discursului oral la situații de comunicare diverse", "sursa": "manual, pp. 113–114", "lectia": 22, "unitate": "Unitatea 4. Perioada modernă: secolul al XIX-lea", "unitateId": "p4", "competenteSpecifice": ["1.3", "4.1"]}]'::jsonb),
  ('11C','2026-2027',32,12,'vineri','2026-12-04','9:45','bloc propriu','Unitatea 4. Perioada modernă: secolul al XIX-lea','Recapitulare','[{"id": "m:3", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11C','2026-2027',33,12,'vineri','2026-12-04','10:35','bloc propriu','Unitatea 4. Perioada modernă: secolul al XIX-lea','Recapitulare','[{"id": "m:12", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11C','2026-2027',34,13,'miercuri','2026-12-09','11:25','bloc propriu','Unitatea 4. Perioada modernă: secolul al XIX-lea','Teză','[{"id": "m:11", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('11C','2026-2027',35,13,'vineri','2026-12-11','9:45','lectie','Unitatea 5. Romantismul','Romantismul – curent cultural european - Romantismul românesc – etape, teme, reprezentanți','[{"id": "u5:1", "fel": "lecție", "titlu": "Romantismul – curent cultural european", "titluOriginal": "Romantismul – curent cultural european", "sursa": "manual, pp. 123–124", "lectia": 1, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.2", "3.3"]}, {"id": "u5:2", "fel": "lecție", "titlu": "Romantismul românesc – etape, teme, reprezentanți", "titluOriginal": "Romantismul românesc – etape, teme, reprezentanți", "sursa": "manual, pp. 123–124", "lectia": 2, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.2"]}]'::jsonb),
  ('11C','2026-2027',36,13,'vineri','2026-12-11','10:35','lectie','Unitatea 5. Romantismul','„Alexandru Lăpușneanul” (I). Autorul, specia, sursele','[{"id": "u5:3", "fel": "lecție", "titlu": "„Alexandru Lăpușneanul” (I). Autorul, specia, sursele", "titluOriginal": "„Alexandru Lăpușneanul” (I). Autorul, specia, sursele", "sursa": "manual, pp. 125–137", "lectia": 3, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',37,14,'miercuri','2026-12-16','11:25','lectie','Unitatea 5. Romantismul','„Alexandru Lăpușneanul” (II). Structura. Cele patru capitole și mottourile','[{"id": "u5:4", "fel": "lecție", "titlu": "„Alexandru Lăpușneanul” (II). Structura. Cele patru capitole și mottourile", "titluOriginal": "„Alexandru Lăpușneanul” (II). Structura. Cele patru capitole și mottourile", "sursa": "manual, pp. 125–137", "lectia": 4, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',38,14,'vineri','2026-12-18','9:45','lectie','Unitatea 5. Romantismul','„Alexandru Lăpușneanul” (III). Personajul principal','[{"id": "u5:5", "fel": "lecție", "titlu": "„Alexandru Lăpușneanul” (III). Personajul principal", "titluOriginal": "„Alexandru Lăpușneanul” (III). Personajul principal", "sursa": "manual, pp. 125–137; N. Manolescu, „Istoria critică”", "lectia": 5, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',39,14,'vineri','2026-12-18','10:35','lectie','Unitatea 5. Romantismul','„Alexandru Lăpușneanul” (IV). Doamna Ruxanda, Moțoc, Spancioc și Stroici','[{"id": "u5:6", "fel": "lecție", "titlu": "„Alexandru Lăpușneanul” (IV). Doamna Ruxanda, Moțoc, Spancioc și Stroici", "titluOriginal": "„Alexandru Lăpușneanul” (IV). Doamna Ruxanda, Moțoc, Spancioc și Stroici", "sursa": "manual, pp. 125–137", "lectia": 6, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',40,16,'miercuri','2027-01-13','11:25','lectie','Unitatea 5. Romantismul','„Alexandru Lăpușneanul” (V). Scene-cheie și arta narativă','[{"id": "u5:7", "fel": "lecție", "titlu": "„Alexandru Lăpușneanul” (V). Scene-cheie și arta narativă", "titluOriginal": "„Alexandru Lăpușneanul” (V). Scene-cheie și arta narativă", "sursa": "manual, pp. 125–137; T. Vianu, „Arta prozatorilor români”", "lectia": 7, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',41,16,'vineri','2027-01-15','9:45','lectie','Unitatea 5. Romantismul','Limbă și comunicare: registre stilistice – registrul arhaic al limbii','[{"id": "u5:8", "fel": "lecție", "titlu": "Limbă și comunicare: registre stilistice – registrul arhaic al limbii", "titluOriginal": "Limbă și comunicare: registre stilistice – registrul arhaic al limbii", "sursa": "manual, pp. 138–140", "lectia": 8, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["1.2", "1.3"]}]'::jsonb),
  ('11C','2026-2027',42,16,'vineri','2027-01-15','10:35','lectie','Unitatea 5. Romantismul','„Floare albastră” (I). Idila romantică. Contextul și geneza','[{"id": "u5:9", "fel": "lecție", "titlu": "„Floare albastră” (I). Idila romantică. Contextul și geneza", "titluOriginal": "„Floare albastră” (I). Idila romantică. Contextul și geneza", "sursa": "ediția Eminescu; „Convorbiri literare”, 1873; Gh. Crăciun, „Istoria literaturii române”", "lectia": 9, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.2", "3.2"]}]'::jsonb),
  ('11C','2026-2027',43,17,'miercuri','2027-01-20','11:25','lectie','Unitatea 5. Romantismul','„Floare albastră” (II). Structura și cele două voci lirice','[{"id": "u5:10", "fel": "lecție", "titlu": "„Floare albastră” (II). Structura și cele două voci lirice", "titluOriginal": "„Floare albastră” (II). Structura și cele două voci lirice", "sursa": "ediția Eminescu", "lectia": 10, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',44,17,'vineri','2027-01-22','9:45','lectie','Unitatea 5. Romantismul','„Floare albastră” (III). Motive romantice și semnificații','[{"id": "u5:11", "fel": "lecție", "titlu": "„Floare albastră” (III). Motive romantice și semnificații", "titluOriginal": "„Floare albastră” (III). Motive romantice și semnificații", "sursa": "ediția Eminescu; Emil Alexandrescu, „Literatura română în analize și sinteze”", "lectia": 11, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.2", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',45,17,'vineri','2027-01-22','10:35','lectie','Unitatea 5. Romantismul','„Floare albastră” (IV). Expresivitate și prozodie - Limbă și comunicare: figuri de stil și procedee de expresivitate','[{"id": "u5:12", "fel": "lecție", "titlu": "„Floare albastră” (IV). Expresivitate și prozodie", "titluOriginal": "„Floare albastră” (IV). Expresivitate și prozodie", "sursa": "ediția Eminescu", "lectia": 12, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["1.2", "2.3"]}, {"id": "u5:13", "fel": "lecție", "titlu": "Limbă și comunicare: figuri de stil și procedee de expresivitate", "titluOriginal": "Limbă și comunicare: figuri de stil și procedee de expresivitate", "sursa": "manual, pp. 148–150 și 170–174", "lectia": 13, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["1.2", "2.3"]}]'::jsonb),
  ('11C','2026-2027',46,18,'miercuri','2027-01-27','11:25','lectie','Unitatea 5. Romantismul','„Odă (în metru antic)” (I). Specia, prozodia, clasicism și romantism','[{"id": "u5:14", "fel": "lecție", "titlu": "„Odă (în metru antic)” (I). Specia, prozodia, clasicism și romantism", "titluOriginal": "„Odă (în metru antic)” (I). Specia, prozodia, clasicism și romantism", "sursa": "manual, pp. 151–153", "lectia": 14, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.2", "3.2"]}]'::jsonb),
  ('11C','2026-2027',47,18,'vineri','2027-01-29','9:45','lectie','Unitatea 5. Romantismul','„Odă (în metru antic)” (II). Tema cunoașterii de sine. Miturile - Limbă și comunicare: expresivitatea unor structuri morfologice și sintactice','[{"id": "u5:15", "fel": "lecție", "titlu": "„Odă (în metru antic)” (II). Tema cunoașterii de sine. Miturile", "titluOriginal": "„Odă (în metru antic)” (II). Tema cunoașterii de sine. Miturile", "sursa": "manual, pp. 151–153", "lectia": 15, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.2", "2.3", "4.2"]}, {"id": "u5:16", "fel": "lecție", "titlu": "Limbă și comunicare: expresivitatea unor structuri morfologice și sintactice", "titluOriginal": "Limbă și comunicare: expresivitatea unor structuri morfologice și sintactice", "sursa": "manual, p. 154", "lectia": 16, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["1.2", "2.3"]}]'::jsonb),
  ('11C','2026-2027',48,18,'vineri','2027-01-29','10:35','lectie','Unitatea 5. Romantismul','„Luceafărul” (I). Geneza, izvoarele, specia','[{"id": "u5:17", "fel": "lecție", "titlu": "„Luceafărul” (I). Geneza, izvoarele, specia", "titluOriginal": "„Luceafărul” (I). Geneza, izvoarele, specia", "sursa": "manual, pp. 159–169", "lectia": 17, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',49,19,'miercuri','2027-02-03','11:25','lectie','Unitatea 5. Romantismul','„Luceafărul” (II). Structura: cele patru tablouri','[{"id": "u5:18", "fel": "lecție", "titlu": "„Luceafărul” (II). Structura: cele patru tablouri", "titluOriginal": "„Luceafărul” (II). Structura: cele patru tablouri", "sursa": "manual, pp. 159–169", "lectia": 18, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',50,19,'vineri','2027-02-05','9:45','lectie','Unitatea 5. Romantismul','„Luceafărul” (III). Hyperion și condiția geniului','[{"id": "u5:19", "fel": "lecție", "titlu": "„Luceafărul” (III). Hyperion și condiția geniului", "titluOriginal": "„Luceafărul” (III). Hyperion și condiția geniului", "sursa": "manual, pp. 159–169", "lectia": 19, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.2", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',51,19,'vineri','2027-02-05','10:35','lectie','Unitatea 5. Romantismul','„Luceafărul” (IV). Cătălina și Cătălin. Antiteza romantică','[{"id": "u5:20", "fel": "lecție", "titlu": "„Luceafărul” (IV). Cătălina și Cătălin. Antiteza romantică", "titluOriginal": "„Luceafărul” (IV). Cătălina și Cătălin. Antiteza romantică", "sursa": "manual, pp. 159–169", "lectia": 20, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',52,20,'miercuri','2027-02-10','11:25','lectie','Unitatea 5. Romantismul','„Luceafărul” (V). Alegoria și interpretările critice - Limbă și comunicare: denotație și conotație','[{"id": "u5:21", "fel": "lecție", "titlu": "„Luceafărul” (V). Alegoria și interpretările critice", "titluOriginal": "„Luceafărul” (V). Alegoria și interpretările critice", "sursa": "manual, pp. 159–169; G. Călinescu, N. Manolescu", "lectia": 21, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.3", "4.1", "4.2"]}, {"id": "u5:22", "fel": "lecție", "titlu": "Limbă și comunicare: denotație și conotație", "titluOriginal": "Limbă și comunicare: denotație și conotație", "sursa": "manual, p. 170", "lectia": 22, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["1.2", "2.3"]}]'::jsonb),
  ('11C','2026-2027',53,20,'vineri','2027-02-12','9:45','bloc propriu','Unitatea 5. Romantismul','Recapitulare','[{"id": "m:4", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11C','2026-2027',54,20,'vineri','2027-02-12','10:35','lectie','Unitatea 5. Romantismul','Evaluare: romantismul','[{"id": "u5:23", "fel": "lecție", "titlu": "Evaluare: romantismul", "titluOriginal": "Recapitulare și evaluare: romantismul", "sursa": "recapitulare și test sumativ", "lectia": 23, "unitate": "Unitatea 5. Romantismul", "unitateId": "p5", "competenteSpecifice": ["2.1", "2.3", "4.1"]}]'::jsonb),
  ('11C','2026-2027',55,21,'miercuri','2027-02-17','11:25','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','Realismul – curent literar - Realismul românesc. Slavici și nuvela realist-psihologică','[{"id": "u6:1", "fel": "lecție", "titlu": "Realismul – curent literar", "titluOriginal": "Realismul – curent literar", "sursa": "manual, pp. 175–176", "lectia": 1, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.2", "3.3"]}, {"id": "u6:2", "fel": "lecție", "titlu": "Realismul românesc. Slavici și nuvela realist-psihologică", "titluOriginal": "Realismul românesc. Slavici și nuvela realist-psihologică", "sursa": "manual, pp. 175–176; N. Manolescu, „Istoria critică”", "lectia": 2, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "3.1", "4.2"]}]'::jsonb),
  ('11C','2026-2027',56,21,'vineri','2027-02-19','9:45','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Moara cu noroc” (I). Tema, titlul, incipitul și finalul','[{"id": "u6:3", "fel": "lecție", "titlu": "„Moara cu noroc” (I). Tema, titlul, incipitul și finalul", "titluOriginal": "„Moara cu noroc” (I). Tema, titlul, incipitul și finalul", "sursa": "I. Slavici, „Novele din popor”; Emil Alexandrescu, „Literatura română în analize și sinteze”", "lectia": 3, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',57,21,'vineri','2027-02-19','10:35','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Moara cu noroc” (II). Structura, conflictul, cronotopul','[{"id": "u6:4", "fel": "lecție", "titlu": "„Moara cu noroc” (II). Structura, conflictul, cronotopul", "titluOriginal": "„Moara cu noroc” (II). Structura, conflictul, cronotopul", "sursa": "I. Slavici, „Novele din popor”", "lectia": 4, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',58,22,'miercuri','2027-03-03','11:25','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Moara cu noroc” (III). Ghiță – evoluția unui personaj - „Moara cu noroc” (IV). Lică, Ana, bătrâna','[{"id": "u6:5", "fel": "lecție", "titlu": "„Moara cu noroc” (III). Ghiță – evoluția unui personaj", "titluOriginal": "„Moara cu noroc” (III). Ghiță – evoluția unui personaj", "sursa": "I. Slavici, „Novele din popor”", "lectia": 5, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3", "4.2"]}, {"id": "u6:6", "fel": "lecție", "titlu": "„Moara cu noroc” (IV). Lică, Ana, bătrâna", "titluOriginal": "„Moara cu noroc” (IV). Lică, Ana, bătrâna", "sursa": "I. Slavici, „Novele din popor”", "lectia": 6, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',59,22,'vineri','2027-03-05','9:45','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Moara cu noroc” (V). Scene-cheie și perspectiva narativă','[{"id": "u6:7", "fel": "lecție", "titlu": "„Moara cu noroc” (V). Scene-cheie și perspectiva narativă", "titluOriginal": "„Moara cu noroc” (V). Scene-cheie și perspectiva narativă", "sursa": "I. Slavici, „Novele din popor”; T. Vianu, „Arta prozatorilor români”", "lectia": 7, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',60,22,'vineri','2027-03-05','10:35','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Moara cu noroc” (VI). Dimensiunea psihologică și morală. Sinteză - Limbă și comunicare: structuri discursive argumentative. Textul argumentativ','[{"id": "u6:8", "fel": "lecție", "titlu": "„Moara cu noroc” (VI). Dimensiunea psihologică și morală. Sinteză", "titluOriginal": "„Moara cu noroc” (VI). Dimensiunea psihologică și morală. Sinteză", "sursa": "I. Slavici, „Novele din popor”; N. Manolescu, „Istoria critică”", "lectia": 8, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.3", "4.1", "4.2"]}, {"id": "u6:9", "fel": "lecție", "titlu": "Limbă și comunicare: structuri discursive argumentative. Textul argumentativ", "titluOriginal": "Limbă și comunicare: structuri discursive argumentative. Textul argumentativ", "sursa": "manual, p. 186", "lectia": 9, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["1.4", "4.1"]}]'::jsonb),
  ('11C','2026-2027',61,23,'miercuri','2027-03-10','11:25','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','Simbolismul – curent literar european - Simbolismul românesc. Macedonski și revista „Literatorul”','[{"id": "u6:10", "fel": "lecție", "titlu": "Simbolismul – curent literar european", "titluOriginal": "Simbolismul – curent literar european", "sursa": "manual, pp. 189–190; Lidia Bote, „Simbolismul românesc”", "lectia": 10, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.2", "3.3"]}, {"id": "u6:11", "fel": "lecție", "titlu": "Simbolismul românesc. Macedonski și revista „Literatorul”", "titluOriginal": "Simbolismul românesc. Macedonski și revista „Literatorul”", "sursa": "manual, pp. 189–190; Lidia Bote, „Simbolismul românesc”", "lectia": 11, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',62,23,'vineri','2027-03-12','9:45','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Noaptea de decemvrie” (I). Specia, tema, structura - „Noaptea de decemvrie” (II). Alegoria drumului. Cei doi călători','[{"id": "u6:12", "fel": "lecție", "titlu": "„Noaptea de decemvrie” (I). Specia, tema, structura", "titluOriginal": "„Noaptea de decemvrie” (I). Specia, tema, structura", "sursa": "manual, pp. 191–198", "lectia": 12, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3"]}, {"id": "u6:13", "fel": "lecție", "titlu": "„Noaptea de decemvrie” (II). Alegoria drumului. Cei doi călători", "titluOriginal": "„Noaptea de decemvrie” (II). Alegoria drumului. Cei doi călători", "sursa": "manual, pp. 191–198", "lectia": 13, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.2", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',63,23,'vineri','2027-03-12','10:35','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„Noaptea de decemvrie” (III). Simboluri, muzicalitate, cromatică','[{"id": "u6:14", "fel": "lecție", "titlu": "„Noaptea de decemvrie” (III). Simboluri, muzicalitate, cromatică", "titluOriginal": "„Noaptea de decemvrie” (III). Simboluri, muzicalitate, cromatică", "sursa": "manual, pp. 191–198", "lectia": 14, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["1.2", "2.3"]}]'::jsonb),
  ('11C','2026-2027',64,24,'miercuri','2027-03-17','11:25','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','„La Polul Nord” de Iuliu Cezar Săvescu. Extindere: „Acuarelă” de Ion Minulescu - Limbă și comunicare: neologismele','[{"id": "u6:15", "fel": "lecție", "titlu": "„La Polul Nord” de Iuliu Cezar Săvescu. Extindere: „Acuarelă” de Ion Minulescu", "titluOriginal": "„La Polul Nord” de Iuliu Cezar Săvescu. Extindere: „Acuarelă” de Ion Minulescu", "sursa": "manual, pp. 199–200", "lectia": 15, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.2", "2.3"]}, {"id": "u6:16", "fel": "lecție", "titlu": "Limbă și comunicare: neologismele", "titluOriginal": "Limbă și comunicare: neologismele", "sursa": "manual, pp. 201–202", "lectia": 16, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["1.2", "4.1"]}]'::jsonb),
  ('11C','2026-2027',65,24,'vineri','2027-03-19','9:45','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','Studiu de caz 7: Simbolismul european (I). Baudelaire și corespondențele','[{"id": "u6:17", "fel": "lecție", "titlu": "Studiu de caz 7: Simbolismul european (I). Baudelaire și corespondențele", "titluOriginal": "Studiu de caz 7: Simbolismul european (I). Baudelaire și corespondențele", "sursa": "manual, pp. 203–208", "lectia": 17, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.2", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',66,24,'vineri','2027-03-19','10:35','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','Studiu de caz 7 (II). Verlaine, Rimbaud, Mallarmé. Artele poetice','[{"id": "u6:18", "fel": "lecție", "titlu": "Studiu de caz 7 (II). Verlaine, Rimbaud, Mallarmé. Artele poetice", "titluOriginal": "Studiu de caz 7 (II). Verlaine, Rimbaud, Mallarmé. Artele poetice", "sursa": "manual, pp. 203–208", "lectia": 18, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.2", "3.1", "3.3"]}]'::jsonb),
  ('11C','2026-2027',67,25,'miercuri','2027-03-24','11:25','lectie','Unitatea 6. Realismul, simbolismul, prelungiri','Prelungiri ale romantismului și clasicismului. Contextul - „De demult…” de Octavian Goga','[{"id": "u6:20", "fel": "lecție", "titlu": "Prelungiri ale romantismului și clasicismului. Contextul", "titluOriginal": "Prelungiri ale romantismului și clasicismului. Contextul", "sursa": "manual, pp. 209–210", "lectia": 20, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "3.1", "3.2"]}, {"id": "u6:21", "fel": "lecție", "titlu": "„De demult…” de Octavian Goga", "titluOriginal": "„De demult…” de Octavian Goga", "sursa": "manual, pp. 211–214", "lectia": 21, "unitate": "Unitatea 6. Realismul, simbolismul, prelungiri", "unitateId": "p6", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',68,25,'vineri','2027-03-26','9:45','bloc propriu','Unitatea 6. Realismul, simbolismul, prelungiri','Recapitulare','[{"id": "m:5", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11C','2026-2027',69,25,'vineri','2027-03-26','10:35','bloc propriu','Unitatea 6. Realismul, simbolismul, prelungiri','Evaluare','[{"id": "m:6", "fel": "bloc propriu", "tip": "evaluare", "titlu": "Evaluare"}]'::jsonb),
  ('11C','2026-2027',70,26,'miercuri','2027-03-31','11:25','lectie','Unitatea 7. Perioada interbelică','Perioada interbelică. Contextul cultural - Orientări tematice în romanul interbelic. Tipologia','[{"id": "u7:1", "fel": "lecție", "titlu": "Perioada interbelică. Contextul cultural", "titluOriginal": "Perioada interbelică. Contextul cultural", "sursa": "manual, pp. 215–216", "lectia": 1, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "3.1", "3.2"]}, {"id": "u7:2", "fel": "lecție", "titlu": "Orientări tematice în romanul interbelic. Tipologia", "titluOriginal": "Orientări tematice în romanul interbelic. Tipologia", "sursa": "manual, pp. 215–216", "lectia": 2, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.2"]}]'::jsonb),
  ('11C','2026-2027',71,26,'vineri','2027-04-02','9:45','lectie','Unitatea 7. Perioada interbelică','Romanul psihologic. Camil Petrescu și autenticitatea','[{"id": "u7:3", "fel": "lecție", "titlu": "Romanul psihologic. Camil Petrescu și autenticitatea", "titluOriginal": "Romanul psihologic. Camil Petrescu și autenticitatea", "sursa": "manual, pp. 217–228", "lectia": 3, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',72,26,'vineri','2027-04-02','10:35','lectie','Unitatea 7. Perioada interbelică','„Ultima noapte…” (I). Titlul, structura, cele două cărți','[{"id": "u7:4", "fel": "lecție", "titlu": "„Ultima noapte…” (I). Titlul, structura, cele două cărți", "titluOriginal": "„Ultima noapte…” (I). Titlul, structura, cele două cărți", "sursa": "manual, pp. 217–228", "lectia": 4, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',73,28,'miercuri','2027-04-14','11:25','lectie','Unitatea 7. Perioada interbelică','„Ultima noapte…” (II). Incipitul și discuția de la popotă - „Ultima noapte…” (III). Ștefan Gheorghidiu, personaj-narator','[{"id": "u7:5", "fel": "lecție", "titlu": "„Ultima noapte…” (II). Incipitul și discuția de la popotă", "titluOriginal": "„Ultima noapte…” (II). Incipitul și discuția de la popotă", "sursa": "manual, pp. 217–228", "lectia": 5, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3", "4.2"]}, {"id": "u7:6", "fel": "lecție", "titlu": "„Ultima noapte…” (III). Ștefan Gheorghidiu, personaj-narator", "titluOriginal": "„Ultima noapte…” (III). Ștefan Gheorghidiu, personaj-narator", "sursa": "manual, pp. 217–228", "lectia": 6, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',74,28,'vineri','2027-04-16','9:45','lectie','Unitatea 7. Perioada interbelică','„Ultima noapte…” (IV). Ela. Relația dintre cele două personaje - „Ultima noapte…” (V). Experiența războiului','[{"id": "u7:7", "fel": "lecție", "titlu": "„Ultima noapte…” (IV). Ela. Relația dintre cele două personaje", "titluOriginal": "„Ultima noapte…” (IV). Ela. Relația dintre cele două personaje", "sursa": "manual, pp. 217–228; N. Manolescu, „Istoria critică”", "lectia": 7, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3", "4.2"]}, {"id": "u7:8", "fel": "lecție", "titlu": "„Ultima noapte…” (V). Experiența războiului", "titluOriginal": "„Ultima noapte…” (V). Experiența războiului", "sursa": "manual, pp. 217–228", "lectia": 8, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.2", "2.3"]}]'::jsonb),
  ('11C','2026-2027',75,28,'vineri','2027-04-16','10:35','lectie','Unitatea 7. Perioada interbelică','„Ultima noapte…” (VI). Perspectiva narativă și tehnicile analizei','[{"id": "u7:9", "fel": "lecție", "titlu": "„Ultima noapte…” (VI). Perspectiva narativă și tehnicile analizei", "titluOriginal": "„Ultima noapte…” (VI). Perspectiva narativă și tehnicile analizei", "sursa": "manual, pp. 217–228", "lectia": 9, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',76,29,'miercuri','2027-04-21','11:25','lectie','Unitatea 7. Perioada interbelică','„Ultima noapte…” (VII). Sinteză și interpretări critice','[{"id": "u7:10", "fel": "lecție", "titlu": "„Ultima noapte…” (VII). Sinteză și interpretări critice", "titluOriginal": "„Ultima noapte…” (VII). Sinteză și interpretări critice", "sursa": "manual, pp. 217–228; critică literară", "lectia": 10, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.3", "4.1", "4.2"]}]'::jsonb),
  ('11C','2026-2027',77,29,'vineri','2027-04-23','9:45','lectie','Unitatea 7. Perioada interbelică','Romanul experienței. Mircea Eliade și generația ʼ27','[{"id": "u7:11", "fel": "lecție", "titlu": "Romanul experienței. Mircea Eliade și generația ʼ27", "titluOriginal": "Romanul experienței. Mircea Eliade și generația ʼ27", "sursa": "M. Eliade, „Maitreyi”; Gh. Crăciun, „Istoria literaturii române”", "lectia": 11, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "3.1", "3.2"]}]'::jsonb),
  ('11C','2026-2027',78,29,'vineri','2027-04-23','10:35','lectie','Unitatea 7. Perioada interbelică','„Maitreyi” (I). Geneza, titlul, structura','[{"id": "u7:12", "fel": "lecție", "titlu": "„Maitreyi” (I). Geneza, titlul, structura", "titluOriginal": "„Maitreyi” (I). Geneza, titlul, structura", "sursa": "M. Eliade, „Maitreyi”", "lectia": 12, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',79,30,'miercuri','2027-05-05','11:25','lectie','Unitatea 7. Perioada interbelică','„Maitreyi” (II). Allan – naratorul și limitele lui - „Maitreyi” (III). Maitreyi. Cele două lumi','[{"id": "u7:13", "fel": "lecție", "titlu": "„Maitreyi” (II). Allan – naratorul și limitele lui", "titluOriginal": "„Maitreyi” (II). Allan – naratorul și limitele lui", "sursa": "M. Eliade, „Maitreyi”; N. Manolescu, „Istoria critică”", "lectia": 13, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3", "4.2"]}, {"id": "u7:14", "fel": "lecție", "titlu": "„Maitreyi” (III). Maitreyi. Cele două lumi", "titluOriginal": "„Maitreyi” (III). Maitreyi. Cele două lumi", "sursa": "M. Eliade, „Maitreyi”", "lectia": 14, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.2", "2.3", "3.3"]}]'::jsonb),
  ('11C','2026-2027',80,30,'vineri','2027-05-07','9:45','lectie','Unitatea 7. Perioada interbelică','„Maitreyi” (IV). Finalul. Sinteză','[{"id": "u7:15", "fel": "lecție", "titlu": "„Maitreyi” (IV). Finalul. Sinteză", "titluOriginal": "„Maitreyi” (IV). Finalul. Sinteză", "sursa": "M. Eliade, „Maitreyi”", "lectia": 15, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.3", "4.1"]}]'::jsonb),
  ('11C','2026-2027',81,30,'vineri','2027-05-07','10:35','bloc propriu','Unitatea 7. Perioada interbelică','Recapitulare','[{"id": "m:9", "fel": "bloc propriu", "tip": "recapitulare", "titlu": "Recapitulare"}]'::jsonb),
  ('11C','2026-2027',82,31,'miercuri','2027-05-12','11:25','bloc propriu','Unitatea 7. Perioada interbelică','Teză','[{"id": "m:8", "fel": "bloc propriu", "tip": "teza", "titlu": "Teză"}]'::jsonb),
  ('11C','2026-2027',83,31,'vineri','2027-05-14','9:45','lectie','Unitatea 7. Perioada interbelică','Romanul balzacian. G. Călinescu și doctrina realismului - „Enigma Otiliei” (I). Tema, structura, incipitul și finalul','[{"id": "u7:16", "fel": "lecție", "titlu": "Romanul balzacian. G. Călinescu și doctrina realismului", "titluOriginal": "Romanul balzacian. G. Călinescu și doctrina realismului", "sursa": "manual, pp. 237–246", "lectia": 16, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.2", "3.1"]}, {"id": "u7:17", "fel": "lecție", "titlu": "„Enigma Otiliei” (I). Tema, structura, incipitul și finalul", "titluOriginal": "„Enigma Otiliei” (I). Tema, structura, incipitul și finalul", "sursa": "manual, pp. 237–246", "lectia": 17, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',84,31,'vineri','2027-05-14','10:35','lectie','Unitatea 7. Perioada interbelică','„Enigma Otiliei” (II). Felix și Otilia','[{"id": "u7:18", "fel": "lecție", "titlu": "„Enigma Otiliei” (II). Felix și Otilia", "titluOriginal": "„Enigma Otiliei” (II). Felix și Otilia", "sursa": "manual, pp. 237–246", "lectia": 18, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3", "4.2"]}]'::jsonb),
  ('11C','2026-2027',85,32,'miercuri','2027-05-19','11:25','lectie','Unitatea 7. Perioada interbelică','„Enigma Otiliei” (III). Moș Costache, Stănică Rațiu, clanul Tulea','[{"id": "u7:19", "fel": "lecție", "titlu": "„Enigma Otiliei” (III). Moș Costache, Stănică Rațiu, clanul Tulea", "titluOriginal": "„Enigma Otiliei” (III). Moș Costache, Stănică Rațiu, clanul Tulea", "sursa": "manual, pp. 237–246", "lectia": 19, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',86,32,'vineri','2027-05-21','9:45','lectie','Unitatea 7. Perioada interbelică','„Enigma Otiliei” (IV). Realism și modernitate. Sinteză','[{"id": "u7:20", "fel": "lecție", "titlu": "„Enigma Otiliei” (IV). Realism și modernitate. Sinteză", "titluOriginal": "„Enigma Otiliei” (IV). Realism și modernitate. Sinteză", "sursa": "manual, pp. 237–246; N. Manolescu, „Istoria critică”", "lectia": 20, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.2", "2.3", "4.1"]}]'::jsonb),
  ('11C','2026-2027',87,32,'vineri','2027-05-21','10:35','lectie','Unitatea 7. Perioada interbelică','Limbă și comunicare: structuri discursive narative și descriptive','[{"id": "u7:21", "fel": "lecție", "titlu": "Limbă și comunicare: structuri discursive narative și descriptive", "titluOriginal": "Limbă și comunicare: structuri discursive narative și descriptive", "sursa": "manual, pp. 247–252", "lectia": 21, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["1.4", "2.3"]}]'::jsonb),
  ('11C','2026-2027',88,33,'miercuri','2027-05-26','11:25','lectie','Unitatea 7. Perioada interbelică','Studiu de caz 8: Modele epice în romanul interbelic (I). Doric, ionic, corintic','[{"id": "u7:22", "fel": "lecție", "titlu": "Studiu de caz 8: Modele epice în romanul interbelic (I). Doric, ionic, corintic", "titluOriginal": "Studiu de caz 8: Modele epice în romanul interbelic (I). Doric, ionic, corintic", "sursa": "manual, pp. 255 și urm.; N. Manolescu, „Arca lui Noe” și „Istoria critică”", "lectia": 22, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.2", "3.1", "4.2"]}]'::jsonb),
  ('11C','2026-2027',89,33,'vineri','2027-05-28','9:45','lectie','Unitatea 7. Perioada interbelică','Recapitulare: perioada interbelică','[{"id": "u7:24", "fel": "lecție", "titlu": "Recapitulare: perioada interbelică", "titluOriginal": "Recapitulare: perioada interbelică", "sursa": "recapitulare", "lectia": 24, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',90,33,'vineri','2027-05-28','10:35','lectie','Unitatea 7. Perioada interbelică','Evaluare: perioada interbelică','[{"id": "u7:25", "fel": "lecție", "titlu": "Evaluare: perioada interbelică", "titluOriginal": "Evaluare: perioada interbelică", "sursa": "test sumativ", "lectia": 25, "unitate": "Unitatea 7. Perioada interbelică", "unitateId": "p7", "competenteSpecifice": ["2.3", "4.1"]}]'::jsonb),
  ('11C','2026-2027',91,34,'miercuri','2027-06-02','11:25','lectie','Unitatea 8. Recapitulare finală','Recapitulare: curentele culturale și literare','[{"id": "u8:1", "fel": "lecție", "titlu": "Recapitulare: curentele culturale și literare", "titluOriginal": "Recapitulare: curentele culturale și literare", "sursa": "recapitulare", "lectia": 1, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["2.1", "2.2"]}]'::jsonb),
  ('11C','2026-2027',92,34,'vineri','2027-06-04','9:45','lectie','Unitatea 8. Recapitulare finală','Recapitulare: textele de bază – poezia','[{"id": "u8:2", "fel": "lecție", "titlu": "Recapitulare: textele de bază – poezia", "titluOriginal": "Recapitulare: textele de bază – poezia", "sursa": "recapitulare", "lectia": 2, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',93,34,'vineri','2027-06-04','10:35','lectie','Unitatea 8. Recapitulare finală','Recapitulare: textele de bază – proza','[{"id": "u8:3", "fel": "lecție", "titlu": "Recapitulare: textele de bază – proza", "titluOriginal": "Recapitulare: textele de bază – proza", "sursa": "recapitulare", "lectia": 3, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["2.1", "2.3"]}]'::jsonb),
  ('11C','2026-2027',94,35,'miercuri','2027-06-09','11:25','lectie','Unitatea 8. Recapitulare finală','Recapitulare: dramaturgia și literatura populară','[{"id": "u8:4", "fel": "lecție", "titlu": "Recapitulare: dramaturgia și literatura populară", "titluOriginal": "Recapitulare: dramaturgia și literatura populară", "sursa": "recapitulare", "lectia": 4, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["2.1", "2.2"]}]'::jsonb),
  ('11C','2026-2027',95,35,'vineri','2027-06-11','9:45','lectie','Unitatea 8. Recapitulare finală','Recapitulare: studiile de caz și dezbaterea','[{"id": "u8:5", "fel": "lecție", "titlu": "Recapitulare: studiile de caz și dezbaterea", "titluOriginal": "Recapitulare: studiile de caz și dezbaterea", "sursa": "recapitulare", "lectia": 5, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["2.2", "3.2", "4.2"]}]'::jsonb),
  ('11C','2026-2027',96,35,'vineri','2027-06-11','10:35','lectie','Unitatea 8. Recapitulare finală','Eseul structurat – exersare pe subiecte de bacalaureat','[{"id": "u8:6", "fel": "lecție", "titlu": "Eseul structurat – exersare pe subiecte de bacalaureat", "titluOriginal": "Eseul structurat – exersare pe subiecte de bacalaureat", "sursa": "„Eseul”, Editura Art; modele de subiecte", "lectia": 6, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["1.4", "4.1"]}]'::jsonb),
  ('11C','2026-2027',97,36,'miercuri','2027-06-16','11:25','bloc propriu','Unitatea 8. Recapitulare finală','Activitate remedială','[{"id": "m:7", "fel": "bloc propriu", "tip": "remedial", "titlu": "Activitate remedială"}]'::jsonb),
  ('11C','2026-2027',98,36,'vineri','2027-06-18','9:45','lectie','Unitatea 8. Recapitulare finală','Evaluare finală','[{"id": "u8:7", "fel": "lecție", "titlu": "Evaluare finală", "titluOriginal": "Evaluare finală", "sursa": "test sumativ, model de subiect de bacalaureat", "lectia": 7, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["1.2", "2.3", "4.1"]}]'::jsonb),
  ('11C','2026-2027',99,36,'vineri','2027-06-18','10:35','lectie','Unitatea 8. Recapitulare finală','Discutarea evaluării finale. Bilanțul anului. Lecturi pentru vară','[{"id": "u8:8", "fel": "lecție", "titlu": "Discutarea evaluării finale. Bilanțul anului. Lecturi pentru vară", "titluOriginal": "Discutarea evaluării finale. Bilanțul anului. Lecturi pentru vară", "sursa": "lucrările elevilor", "lectia": 8, "unitate": "Unitatea 8. Recapitulare finală", "unitateId": "p8", "competenteSpecifice": ["2.3", "4.2"]}]'::jsonb);

-- ---------- paza pe clasa asta ----------
do $$
declare n int; lipsa int;
begin
  select count(*) into n from public.school_plan where clasa = '11C' and an_scolar = '2026-2027';
  if n <> 99 then
    raise exception 'Clasa 11C are % ore, așteptam 99. Lipirea s-a rupt.', n;
  end if;
  select count(*) into lipsa from generate_series(1, 99) g
   where not exists (select 1 from public.school_plan p
                      where p.clasa = '11C' and p.an_scolar = '2026-2027' and p.nr = g);
  if lipsa > 0 then
    raise exception 'Clasei 11C îi lipsesc % numere din șirul 1..99.', lipsa;
  end if;
  raise notice 'Clasa 11C: 99 de ore, la locul lor.';
end $$;
